### ISSUE TITLE
末尾逗号可以去掉吗，一点生成就会在末尾加个逗号占用token数量

### ISSUE THREAD

**Issue by lost9999** [Physton/sd-webui-prompt-all-in-one#10]

**Comment by Physton** [comment]
如果去掉了末尾逗号，点击lora模型，自动加载进来就会出现问题。

**Comment by Physton** [comment]
在原版输入框中，连续点击多个lora模型，webui没有自动没给加,号，会导致无效。

**Comment by lost9999** [comment]
> 在原版输入框中，连续点击多个lora模型，webui没有自动没给加,号，会导致无效。

lora模型加载进来就会生效的，不加逗号也没事，另外你可以看看prompt formatter这个插件，你这个插件和它有格式上的冲突

**Comment by Physton** [comment]
明白了，后续解决这个问题。另外请提供下具体冲突的问题详细

**Comment by lost9999** [comment]
> prompt formatter会自动优化prompt格式，默认都是逗号后面不带空格，结尾不带逗号，每次这个优化完，一点运行你这插件又给改回去了

**Comment by lost9999** [comment]
比如用prompt formatter优化后是这样的：8k,analog style,modelshoot style,(photorealistic:1.4),vibrant details,best quality,masterpiece,1girl,goddess,aesthetic,sexy,school Uniform,Pleated skirt,(Thigh socks:1.2),Leather shoes,beautiful detailed shiny skin,large breasts,After school,street,perfect figure,creamy filter,cinematic lighting,best shadow,FilmG <lora:FilmG2:0.6:PALETTE>
点击运行后prompt就变成这样的：8k, analog style, modelshoot style, (photorealistic:1.4), vibrant details, best quality, masterpiece, 1girl, goddess, aesthetic, sexy, school Uniform, Pleated skirt, (Thigh socks:1.2), Leather shoes, beautiful detailed shiny skin, large breasts, After school, street, perfect figure, creamy filter, cinematic lighting, best shadow, FilmG <lora:FilmG2:0.6:PALETTE>,

**Comment by Physton** [comment]
了解了

**Comment by lost9999** [comment]
再提个功能上的建议：有没有办法实现回车之后出现多个翻译结果供用户选择呢，因为一个词往往会有多种不同的翻译结果，有时候默认的翻译结果并不是用户想要的，如果能实现这一点，那将会极大提升插件的实用性

**Comment by lost9999** [comment]
比如我输入内裤这个词，翻译默认的翻译结果是underwear，但我想要的其实是panties这个词，这个在网页版的翻译中是可以看到多种释义的，看看能否实现这个功能呢

**Comment by Physton** [comment]
我会考虑的

**Comment by lost9999** [comment]
> 逗号后面的空格去掉了，但是最后一个逗号还是先保留，我发现连续点击Embedding也会出问题。带想到更好的解决办法再说。

辛苦了
