### ISSUE TITLE
The sd installed on google colab cannot be used

### ISSUE THREAD

**Issue by mnrr01** [Physton/sd-webui-prompt-all-in-one#101]
My SD is installed on google colab, and I installed it using the URL in the extension according to the process. After the display is successful, all restarts (including the background), but the interface does not change after the restart, and the content of the plug-in is not displayed. I updated the latest version of sd on cloab and reinstalled, but it still hasn't changed.

**Comment by Physton** [comment]
![P2JBO5U`BVDKIK4FI5E0R{Y](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/8cfd4c02-9f0d-48ab-b4b3-d8f652a90f6e)

**Comment by Physton** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81
