### ISSUE TITLE
VLAD分支下会一直显示没有安装阿里翻译SDK

### ISSUE THREAD

**Issue by jobbingxu** [Physton/sd-webui-prompt-all-in-one#102]
实际已安装
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/128159623/3afbe415-6ac6-4e31-969d-9313441e38af)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/128159623/3a0d6fd9-35a4-43ce-928d-5f114d717bcb)

**Comment by Physton** [comment]
实际点阿里云翻译的测试按钮，会报没有aliyun-sdk包吗？

**Comment by Physton** [comment]
我安装了VLAD分支，确实会有这个问题。现在已经修复了。

**Comment by jobbingxu** [comment]
大佬神速!
