### ISSUE TITLE
[sd-webui-tagcomplete] - After moving a tag you can't move any tags until you reloadui

### ISSUE THREAD

**Issue by Terroosh** [Physton/sd-webui-prompt-all-in-one#103]
![break](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/55752005/32ac2db8-a212-4bd4-bce9-c36a7d05aafb)

Using latest sd-webui-prompt-all-in-one and  a1111-sd-webui-tagcomplete 
I also tried older versions of both and the bug still happens. 
Only happens if a1111-sd-webui-tagcomplete is enabled.

I use https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/89f9faa63388756314e8a1d96cf86bf5e0663045

![1](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/55752005/ad874b59-0e74-4a87-ba6f-7e2cda71381d)

**Comment by Physton** [comment]
I have submitted a new version. Please update and try again to see if the issue has been resolved.

**Comment by Terroosh** [comment]
> I have submitted a new version. Please update and try again to see if the issue has been resolved.

Fixed, ty!
