### ISSUE TITLE
tags目录在哪？

### ISSUE THREAD

**Issue by fqw123** [Physton/sd-webui-prompt-all-in-one#104]
tags目录在哪？

**Comment by Physton** [comment]
自己建立

**Comment by fqw123** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/43577558/6e9c0484-716a-459b-b690-12640a8d44a3)
想问一下，这列数字是咋来的，我本地有danbooru.csv文件，没看到有相关的
