### ISSUE TITLE
Paste from favorites

### ISSUE THREAD

**Issue by mikheys** [Physton/sd-webui-prompt-all-in-one#106]
Good afternoon. I noticed that the insert from the favorites replaces the previously entered prompt, and is not supplemented.

**Comment by Physton** [comment]
![Snipaste_2023-06-01_00-47-54](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/27052e79-25b7-45de-aec8-0e938a04faab)

**Comment by mikheys** [comment]
Understood. It was disabled in the theme settings)

**Comment by Physton** [comment]
👌🏻
