### ISSUE TITLE
有没有可能，可以在每个拆分的单词的选项中，添加一个收藏的功能？

### ISSUE THREAD

**Issue by tianyacao99** [Physton/sd-webui-prompt-all-in-one#107]
首先非常感谢作者这款强大的插件，让我这个英语学渣现在用SD也能得心应手。
大家在使用过程中，模仿别人的作品时，应该也会经常发现一些很好用的词语，单纯靠中文输入再翻译不一定能复现这个词或语句。如果能在学习别人的作品过程中，可以很方便的一键收集归纳这些关键词，相信大家的创造能力能得到很大的提升。
收藏关键词时，可以自定义分类，保存的本地文件可以自己用记事本打开进行编辑。用的时候导进去分好类的关键词，就可以一键输入。
比如动态提示词插件Dynamic prompts的wildcards，可以很好的实现在分类的关键词中进行随机抽取，但不方便添加和编辑。
大多时候我们还是更倾向于选择自己喜欢的关键词。如果prompt-all-in-one插件能实现一键收藏分类，我感觉会更完美。如果能实现这一功能，我非常愿意请大神喝几杯咖啡。

**Comment by Physton** [comment]
1. 鼠标移动到每个关键词上，有关键词收藏。
2. 鼠标按住框选多个关键词，有批量收藏到一个合集。
3. 目前不支持分类收藏。

**Comment by tianyacao99** [comment]
奇怪了，每次我都会更新到最新版本，但是都没有看到你说的在每个拆分的关键词上有收藏选项，刚刚更新了再看还是只有调节权重那几个功能。如果你说的是历史记录里的收藏功能，这个我倒是知道的。

**Comment by Physton** [comment]
你把扩展主题逐个关了再看看
