### ISSUE TITLE
does not work via argument "--data-dir"

### ISSUE THREAD

**Issue by Sotonya** [Physton/sd-webui-prompt-all-in-one#108]

**Comment by Physton** [comment]
After testing, I found that almost all third-party extensions do not work under the argument "--data-dir", except for the extensions in the "extensions-builtin" folder. This is a problem with the  [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui). You may need to submit an issue to the  [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) repository.
![Snipaste_2023-06-03_10-22-59](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/118b3e3f-c2d7-4796-a4fd-3ee31efc6b4a)
![Snipaste_2023-06-03_10-23-08](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/732a9c09-331f-4afd-a4de-e002c2eb0adf)
![Snipaste_2023-06-03_10-23-16](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/49a895f0-2c50-406c-8aeb-4eb54f7a3ece)

**Comment by Physton** [comment]
I only added the argument "--data-dir", there may be other arguments that need to be added, but I don't know.

**Comment by Physton** [comment]
A solution has been found, please refer to the reply in #113.
