### ISSUE TITLE
lora权重重新调回1以后:1会消失

### ISSUE THREAD

**Issue by higekibaka** [Physton/sd-webui-prompt-all-in-one#109]
请问这个可以优化下吗，举例<lora:GreekClothes>会变成这样

**Comment by Physton** [comment]
已添加支持：
<img width="385" alt="Snipaste_2023-06-03_12-54-40" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/75d16e25-ddd4-4702-948d-a5736df11590">
