### ISSUE TITLE
启动SD报错，控制台没有报错提示，但是SD界面右上角有提示

### ISSUE THREAD

**Issue by ntf-Cinema4D-sd** [Physton/sd-webui-prompt-all-in-one#11]
这是错误信息，求解

![微信图片_20230512123512](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/72090841/1d72dad9-1f05-49f2-a6c2-4362b97bd585)

**Comment by Physton** [comment]
更新webui的环境到最新的版本，至少是2023年第13周

**Comment by ntf-Cinema4D-sd** [comment]
感谢回复！

现在我用的SD是最新版，以下是版本号。
python: 3.10.10  •  torch: 2.0.0+cu118  •  xformers: N/A  •  gradio: 3.28.1  •  commit: [5ab7f213]

准确的说，我的故障问题是：
启动SD可以正常出现操作面板，但点击reload UI重启SD后它会报错，上图红色报错信息出现在右上角，操作面板也消失。。

**Comment by Physton** [comment]
如果是正常启动，扩展是能用的。但是reload ui后有问题是吧？

**Comment by ntf-Cinema4D-sd** [comment]
> 如果是正常启动，扩展是可以使用的。但是reload ui后有问题是吧？

是的，“重新加载前端” 或者使用 “应用更改并重载前端” 都会出问题

**Comment by Physton** [comment]
感谢你的反馈，我会尽快修复

**Comment by ntf-Cinema4D-sd** [comment]
> 感谢你的反馈，我会尽快修复

好的，期待解决方案，辛苦！

**Comment by Physton** [comment]
我试了很多次，都没有复现你所说的问题，这是我的环境：
![Snipaste_2023-05-12_14-43-52](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/94d65ed6-4174-46f5-aff9-5c6eaf7accca)

**Comment by ntf-Cinema4D-sd** [comment]
> 我试了很多次，都没有复现你所说的问题，这是我的环境： ![Snipaste_2023-05-12_14-43-52](https://user-images.githubusercontent.com/12066768/237892033-94d65ed6-4174-46f5-aff9-5c6eaf7accca.png)

那我重装一下SD看看是否可以解决，麻烦你！

**Comment by ntf-Cinema4D-sd** [comment]
我彻底重装了SD，仍然遇到这个问题，像我一样的还有3、4个人，但是其他人也有表示没有问题的，我们用的几乎是一模一样的SD，这可真把我整不明白了

**Comment by chioulin** [comment]
压缩包解压到指定文件夹运行终端出现Installing requirements for Web UI，我的是macos M1。请问如何解决呢

**Comment by Physton** [comment]
参考：https://github.com/Physton/sd-webui-prompt-all-in-one @chioulin

**Comment by Physton** [comment]
@ntf-Cinema4D-sd 
翻译测试成功后，还会失败的问题修复了，不是浏览器的问题。
至于reload ui后，这个我没测试出来，我猜测是后台服务还没完全加载成功，网页就被刷新展示了，所以出错。需要再刷新一遍网页，就好了。

**Comment by ykh2022** [comment]
<img width="244" alt="1abcc27e74552f65c10317c0e20e8ec2" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/107169448/a7c270da-245a-41fd-b5e2-6f1fedee81b0">
我使用的秋叶的整合包在加入了几个lora模型后也出现了这样的问题，其它功能没有影响，但是无法正常的读取存放于models\lora中的lora模型
