### ISSUE TITLE
"一键翻译所有关键词 "按钮不能正常工作

### ISSUE THREAD

**Issue by portg80** [Physton/sd-webui-prompt-all-in-one#110]
我在俄语的标准字段中输入 "Солнце"，按下翻译所有，然后底部的文字有些变成了中文，有些变成了英文，只有部分文字被翻译成我的母语俄语。
还有，原始输入字段中的单词并不总是从第1次按下按钮开始翻译的，如果成功了，也需要30秒左右，尽管使用字符串输入每个令牌通过你的插件的字段几乎瞬间就能成功。
1
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/42353304/79cce436-766a-450a-8d85-f11fb36b83bb)
2
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/42353304/33920320-f462-4851-9ff3-bd2d062b67df)

**Comment by Physton** [comment]
1. 请问你选择的本地语言是否是`Русский (Россия)`
2. 俄语确实不能适用于一键智能翻译。稍后我做会修改，在俄语环境中，会出现两个按钮：翻译到英语、翻译到本地语言。
3. WebUI输入框中的修改，需要先点下插件的面板， WebUI输入框的内容才会被加载进插件面板。所以你点击两次翻译按钮，第一次代表加载进插件面板。第二次才代表翻译。
4. 不要API KEY的接口，无法支持高并发，所以其中部分接口翻译会比较慢。

**Comment by portg80** [comment]
> 1. 请问你选择的本地语言是否是`Русский (Россия)`。或者你是否启用了TagComplete增强翻译，但CSV文件是中文翻译的文件。
> 2. WebUI输入框中的修改，需要先点下插件的面板， WebUI输入框的内容才会被加载进插件面板。所以你点击两次翻译按钮，第一次代表加载进插件面板。第二次才代表翻译。
> 3. 不要API KEY的接口，无法支持高并发，所以其中部分接口翻译会比较慢。

是的，我确实插入了标签系统，但我没有注意到它是中文的。我可以找一个俄语的替代品吗？

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/42353304/0063caa3-d9c1-4404-873a-899c40755194)

**Comment by Physton** [comment]
> > 1. 请问你选择的本地语言是否是`Русский (Россия)`。或者你是否启用了TagComplete增强翻译，但CSV文件是中文翻译的文件。
> > 2. WebUI输入框中的修改，需要先点下插件的面板， WebUI输入框的内容才会被加载进插件面板。所以你点击两次翻译按钮，第一次代表加载进插件面板。第二次才代表翻译。
> > 3. 不要API KEY的接口，无法支持高并发，所以其中部分接口翻译会比较慢。
> 
> 是的，我确实插入了标签系统，但我没有注意到它是中文的。我可以找一个俄语的替代品吗？
> 
> ![image](https://user-images.githubusercontent.com/42353304/243107643-0063caa3-d9c1-4404-873a-899c40755194.png)

是的，你可以使用俄语翻译的CSV文件。

**Comment by portg80** [comment]
我在一些没有API的翻译中也遇到了这个问题
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/42353304/0305b9e8-6327-4034-aef1-49cd769903ea)

**Comment by Physton** [comment]
> 我在一些没有API的翻译中也遇到了这个问题 ![image](https://user-images.githubusercontent.com/42353304/243107788-0305b9e8-6327-4034-aef1-49cd769903ea.png)

你需要测试每个不需要API KEY接口是否在能够你的计算机中稳定运行，选择一个你认为比较好用的。
或者使用需要API KEY的接口。比如Google、Microsoft等等，他们不需要付费，有提供免费额度。并且他们的速度非常快，非常稳定。

**Comment by Physton** [comment]
<img width="520" alt="Snipaste_2023-06-03_23-32-56" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/fc359c7d-86c1-4120-82d5-bc15c6bbe553">
<img width="562" alt="Snipaste_2023-06-03_23-33-16" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/2849bbd9-00c2-4452-9c5d-fe0e159e8531">

**Comment by portg80** [comment]
> > > 1. Могу я спросить, является ли выбранный вами местный язык`Русский (Россия)`.Или вы включили расширенный перевод TagComplete, но CSV-файл является файлом перевода на китайский.
> > > 2. Для внесения изменений в поле ввода WebUI вам необходимо нажать на панель подключаемого модуля, прежде чем содержимое поля ввода WebUI будет загружено на панель подключаемого модуля.Итак, вы дважды нажимаете кнопку перевести, в первый раз это означает загрузку на панель подключаемых модулей.Второй раз представляет собой перевод.
> > > 3. Интерфейсы, которые НЕ используют API KEY, не могут поддерживать высокий уровень параллелизма, поэтому перевод некоторых интерфейсов будет медленнее.
> > 
> > 
> > Да, я действительно вставил систему маркировки, но я не заметил, что она на китайском языке.Могу ли я найти замену русскому языку?
> > ![изображение](https://user-images.githubusercontent.com/42353304/243107643-0063caa3-d9c1-4404-873a-899c40755194.png)
> 
> 是的，你可以使用翻译成俄语的CSV文件。

我在哪里可以下载它？

**Comment by Physton** [comment]
> > > > 1. Могу я спросить, является ли выбранный вами местный язык`Русский (Россия)`.Или вы включили расширенный перевод TagComplete, но CSV-файл является файлом перевода на китайский.
> > > > 2. Для внесения изменений в поле ввода WebUI вам необходимо нажать на панель подключаемого модуля, прежде чем содержимое поля ввода WebUI будет загружено на панель подключаемого модуля.Итак, вы дважды нажимаете кнопку перевести, в первый раз это означает загрузку на панель подключаемых модулей.Второй раз представляет собой перевод.
> > > > 3. Интерфейсы, которые НЕ используют API KEY, не могут поддерживать высокий уровень параллелизма, поэтому перевод некоторых интерфейсов будет медленнее.
> > > 
> > > 
> > > Да, я действительно вставил систему маркировки, но я не заметил, что она на китайском языке.Могу ли я найти замену русскому языку?
> > > ![изображение](https://user-images.githubusercontent.com/42353304/243107643-0063caa3-d9c1-4404-873a-899c40755194.png)
> > 
> > 
> > 是的，你可以使用翻译成俄语的CSV文件。
> 
> 我在哪里可以下载它？

我也不知道，你需要去网上寻找有没有人分享出TagComplete插件的俄语的CSV文件。
或者你不要启用这个功能。

**Comment by portg80** [comment]
> > > > > 1. Могу я спросить, является ли выбранный вами местный язык`Русский (Россия)`.Или вы включили расширенный перевод TagComplete, но CSV-файл является файлом перевода на китайский.
> > > > > 2. Для внесения изменений в поле ввода WebUI вам необходимо нажать на панель подключаемого модуля, прежде чем содержимое поля ввода WebUI будет загружено на панель подключаемого модуля.Итак, вы дважды нажимаете кнопку перевести, в первый раз это означает загрузку на панель подключаемых модулей.Второй раз представляет собой перевод.
> > > > > 3. Интерфейсы, которые НЕ используют API KEY, не могут поддерживать высокий уровень параллелизма, поэтому перевод некоторых интерфейсов будет медленнее.
> > > > 
> > > > 
> > > > Да, я действительно вставил систему маркировки, но я не заметил, что она на китайском языке.Могу ли я найти замену русскому языку?
> > > > ![изображение](https://user-images.githubusercontent.com/42353304/243107643-0063caa3-d9c1-4404-873a-899c40755194.png)
> > > 
> > > 
> > > 是的，你可以使用翻译成俄语的CSV文件。
> > 
> > 
> > 我在哪里可以下载它？
> 
> 我也不知道，你需要去网上寻找有没有人分享出[TagComplete](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete)插件的俄语的CSV文件。 或者你不要启用这个功能。

啊，我明白了，非常感谢你，你有一个非常有用的插件。!
