### ISSUE TITLE
[Free] Microsoft Bing is not working. [JP]

### ISSUE THREAD

**Issue by Tktw** [Physton/sd-webui-prompt-all-in-one#112]
Extensions has been updated and currently cannot translate. [https://github.com/Physton/sd-webui-prompt-all-in-one/commit/5273c8872251050749d661894187d06071fda4cc](https://github.com/Physton/sd-webui-prompt-all-in-one/commit/5273c8872251050749d661894187d06071fda4cc)
from japan.
Is Region only CN?
Is it currently being updated?
![Animation](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/10087510/33a717f9-3a44-485b-9b93-2439a3b8f0e6)

**Comment by Physton** [comment]
I found that only CN is working properly during my testing, so I removed the others. Now, I have restored the other region codes.

**Comment by Tktw** [comment]
Wow! Thanks for the quick response! ❤️
