### ISSUE TITLE
What is the reason that wedui with this plugin does not have this plugin?

### ISSUE THREAD

**Issue by Op7788** [Physton/sd-webui-prompt-all-in-one#113]

**Comment by Physton** [comment]
https://github.com/Physton/sd-webui-prompt-all-in-one#faq--%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8
<img width="857" alt="Snipaste_2023-06-04_16-57-14" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/fb13b3fa-f4ff-464d-94e7-bf3473e880cb">

**Comment by Op7788** [comment]
I'm all version 1.3.1

**Comment by Physton** [comment]
Under version 1.3.1, everything is working fine on my end. You need to provide a screenshot of the console log or any error messages on the webpage.

**Comment by andyvha** [comment]
I have same issue. Working on A1111 1.3.2 and the log shows like following:

Model loaded in 21.4s (load weights from disk: 0.4s, create model: 0.4s, apply weights to model: 16.7s, apply half(): 0.8s, move model to device: 1.0s, load textual inversion embeddings: 2.2s).
sd-webui-prompt-all-in-one background API service started successfully.
Applying optimization: xformers... done.

This extension is under panel list but there no show up at anywhere. !!!

**Comment by Physton** [comment]
> I have same issue. Working on A1111 1.3.2 and the log shows like following:
> 
> Model loaded in 21.4s (load weights from disk: 0.4s, create model: 0.4s, apply weights to model: 16.7s, apply half(): 0.8s, move model to device: 1.0s, load textual inversion embeddings: 2.2s). sd-webui-prompt-all-in-one background API service started successfully. Applying optimization: xformers... done.
> 
> This extension is under panel list but there no show up at anywhere. !!!

I have tested it and it works fine on version [baf6946](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/baf6946e06249c5af9851c60171692c44ef633e0).

**Comment by andyvha** [comment]
I figure out why this does not show up. I am not sure which Gradio version will block path that not come from their inside folder. I tried 3.33 to 3.28. Add folder of extension blocked by Gradio to allowed_paths

Solution:
Go to this folder **venv\Lib\site-packages\gradio** inside sd folder. Pick up **blocks.py** file and edit:

- Find this line: **self.allowed_paths = allowed_paths or []** and add folder list between [] like following:
self.allowed_paths = allowed_paths or ["C:/Users/Kem/Documents/ext_iso/extensions/sd_feed", "C:/Users/xxx/Documents/ext_iso/extensions/canvas-zoom","C:/Users/xxx/Documents/ext_iso/extensions/sd-webui-depth-lib"]

It will show up, I did it for other extensions blocked by Gradio successfully. Cheers

**Comment by Physton** [comment]
> I figure out why this does not show up. I am not sure which Gradio version will block path that not come from their inside folder. I tried 3.33 to 3.28. Add folder of extension blocked by Gradio to allowed_paths
> 
> Solution: Go to this folder **venv\Lib\site-packages\gradio** inside sd folder. Pick up **blocks.py** file and edit:
> 
> * Find this line: **self.allowed_paths = allowed_paths or []** and add folder list between [] like following:
>   self.allowed_paths = allowed_paths or ["C:/Users/xxx/Documents/ext_iso/extensions/sd_feed", "C:/Users/xxx/Documents/ext_iso/extensions/canvas-zoom","C:/Users/xxx/Documents/ext_iso/extensions/sd-webui-depth-lib"]
> 
> It will show up, I did it for other extensions blocked by Gradio successfully. Cheers
> 
> ![image](https://user-images.githubusercontent.com/40895228/243983308-ca07fdc4-2900-4c2d-8ed9-8da26d8df459.png) ![image](https://user-images.githubusercontent.com/40895228/243984565-4dbc5b4f-5254-4e91-97a6-8fbfca55683b.png)

The solution you provided is very helpful.
After research, I found that there is a startup parameter for WebUI:
`--gradio-allowed-path  # add path to gradio's allowed_paths, make it possible to serve files from it`
By adding this parameter, it may not be necessary to modify the code.
Currently, I have not been able to reproduce this issue. If I can reproduce this problem, I think there should be a better solution.

**Comment by Op7788** [comment]
解决办法是什么？

**Comment by Physton** [comment]
@Op7788 @andyvha 
你们是否启用了了 --data-dir 参数，指定了自定义了数据目录？
Have you enabled the --data-dir parameter to specify a custom data directory?

**Comment by Op7788** [comment]
我不知道我的data路径

**Comment by Op7788** [comment]
我不知道我的data路径，如何找到data 路徑

**Comment by Physton** [comment]
> 我不知道我的data路径，如何找到data 路徑

更新插件，重启，控制台里面插件会告诉你目录。
![ZGEEQ7CO4BB52SZI7C)RQOY](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/f4109021-a3c5-4fb1-b277-446205ae4ff9)
