### ISSUE TITLE
yandex translator

### ISSUE THREAD

**Issue by SXxXS9** [Physton/sd-webui-prompt-all-in-one#114]
hi, can u add yandex translator for russian translate please

**Comment by Physton** [comment]
see: #72

**Comment by SXxXS9** [comment]
hi, now i've got an api key, how should i pass it to u?

**Comment by Physton** [comment]
You can send it to my email at physton@163.com. I will notify you after I finish the development. Thank you for your help!

**Comment by SXxXS9** [comment]
Thanks for your job!

**Comment by Physton** [comment]
Thank you for providing the API KEY. Yandex Translator is now supported.

**Comment by SXxXS9** [comment]
Thank you!!
