### ISSUE TITLE
使用阿里云的机器学习平台DSW打开的webui，载入插件有问题

### ISSUE THREAD

**Issue by dawancha** [Physton/sd-webui-prompt-all-in-one#115]
在阿里云的dsw打开webui的时候，点击本地地址
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/348031/d23189df-c9f4-497c-bc33-40178ea99951)
Url是
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/348031/340c33f8-364d-4ab5-8baa-d3718d04509c)
即会出现插件无法连接接口服务的错误。
如果用gradio的地址打开就没问题。在使用本地地址打开时，我发现插件访问的接口是
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/348031/09cea9d4-a59d-4e35-aea9-b3a24fc9a50e)
把阿里云提供的地址的后半部分都剪掉了所以出现了403

**Comment by Physton** [comment]
打开浏览器开发工具，输入`gradio_config`，截个图给我。
![Snipaste_2023-06-06_18-15-49](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/6cd9bb71-c28b-40ea-9a74-ac85cae5bb06)

**Comment by dawancha** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/348031/f766703b-8985-4318-8cff-d01244951621)
你好，这是gradio_config的截图，在访问local url 打开webui的时候，url里还是有其他参数的
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/348031/78a42d9d-ae37-4ed6-850a-6c9d1884ca2c)

**Comment by Physton** [comment]
你浏览器访问：https://dsw-xxxxxxxxx.com/dsw-21753/proxy/7860/physton_prompt/get_config
截个图给我

**Comment by Physton** [comment]
已修改，看是否可以了。

**Comment by dawancha** [comment]
OK了，谢谢
