### ISSUE TITLE
关键词能否插入到prompt框游标位置?

### ISSUE THREAD

**Issue by kiosty** [Physton/sd-webui-prompt-all-in-one#117]
关键词默认插入到尾部有些不方便，经常需要重新剪切调整新插入关键词的位置

**Comment by Physton** [comment]
如果插入到游标位置，会出现一些问题。
例如提示词：`abc, def`，如果游标放到bc中间 `ab|c, def`。就会导致插入出现问题。
你完全可以添加关键词后拖动关键词到指定的位置，还可以批量拖动关键词。
不知道你为什么要用剪切的方式调整，剪切调整还会导致本地对照语言消失。
所以，目前不会考虑这个功能。
