### ISSUE TITLE
希望开发单独的mac或window应用，或小程序！

### ISSUE THREAD

**Issue by bikingfree1989** [Physton/sd-webui-prompt-all-in-one#119]
这块插件非常好，已经是我的终极提示词解决方案。

但是，我主要用mac电脑，不用webui，用drawthings，这就导致我没法用这个插件。

希望独立出插件，以macOS小软件的形式存在，这样可以脱离webui的束缚，让应用更广泛。

不知作者是否有空，或者哪位大神可以开发一下。

**Comment by Physton** [comment]
macos也能用webui

**Comment by bikingfree1989** [comment]
> 
是可以用没问题，但是性能差。主要还是用第三方客户端Draw things以及diffusion bee等。
不希望每次用客户端的时候，还把webui也打开，多一个终端窗口，太麻烦。
