### ISSUE TITLE
BUG: 和tag autocomplete一起时存在问题

### ISSUE THREAD

**Issue by CrazyChildren** [Physton/sd-webui-prompt-all-in-one#121]
- 问题描述&复现：
使用tag autocomplete自动补全时，样式是“1girl, ”在逗号后会有一个空格，如果直接回车，会生成两个block，一个是1girl，一个是无内容block。
- 版本等信息：
win11，最新版webui及插件

**Comment by Physton** [comment]
更新再试试

**Comment by CrazyChildren** [comment]
看起来还是有问题的，看起来应该先trim再去除逗号，而不是先去逗号再去除空格。
`tags = tags.trim().replace(/\s*,\s*$/, '')`

**Comment by CrazyChildren** [comment]
auto complete自动补全后输入是 '1girl, '，直接回车后结果是'1girl, , '

**Comment by Physton** [comment]
你录个gif或者视频

**Comment by CrazyChildren** [comment]
https://github.com/Physton/sd-webui-prompt-all-in-one/assets/39021671/ea5ef957-6ab6-48e5-a769-ef6da03b8e14

**Comment by Physton** [comment]
更新了再试试
