### ISSUE TITLE
[Bug] Style change, text is unreadable

### ISSUE THREAD

**Issue by ghostsquad** [Physton/sd-webui-prompt-all-in-one#127]
**Issue Feedback**

Note: Any posts that do not follow this template will be closed immediately. I won't be able to address your issue if the information below is not provided.

Please mark "x" inside the square brackets to indicate that you have read the following information.
- [x] I confirm that I have searched for a solution to this issue in the [FAQ](https://physton.github.io/sd-webui-prompt-all-in-one-assets/#/FAQ) and couldn't find a solution.
- [x] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [x] I confirm that I have read the [Wiki](https://physton.github.io/sd-webui-prompt-all-in-one-assets/#/Installation) and couldn't find a solution.

**Describe the Issue**
A recent update of this extension seems to have drastically changed the styling and text contrast is very low.

**Steps to Reproduce**
N/a

**Screenshots**
The all styles turned off:

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/903488/8b941199-633a-4e22-9193-d013aced8ed7)

enabling `hellostyle` at least turns the text blue.

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/903488/838fa5b9-7d93-4c87-a904-8b62ef89e563)

These used to look like buttons though. The `X` is also nearly invisible.

**Some necessary information**
 - Stable Diffusion WebUI version: b76cc78ad9
 - Extension version: 510fa649
 - OS: windows
 - Browser: firefox
 - Python version: 3.10.9
 - Gradio version: 3.23.0

**Additional Logs**
Add any relevant logs regarding the issue here.

**Comment by Physton** [comment]
Do not check multiple themes.

**Comment by Physton** [comment]
No issues were found in Firefox browser. Please check if it is caused by a browser extension or the WebUI extension.

**Comment by ghostsquad** [comment]
Nothing has changed in my browser. I haven't updated automatic1111, nor installed any other extensions. As you can see in the first screenshot, I unchecked everything. I did try individual options in isolation. None of them seemed to do anything to affect colors other than `hellostyle`. I did a hard at restart of the webui.bat as well as reloading the browser. I will keep trying new things though. So far, all I changed was updating this extension.

**Comment by Physton** [comment]
Try adding `?__theme=dark` after the URL:
`http://localhost:7860/?__theme=dark`

**Comment by Physton** [comment]
The addition of the light/dark theme toggle button in the settings has been implemented. Please give it a try and see if it resolves your issue.
