### ISSUE TITLE
[Bug] 勾选“我的风格”后，提词标签无法完整收回隐藏

### ISSUE THREAD

**Issue by gustavmilo** [Physton/sd-webui-prompt-all-in-one#128]
**反馈须知**

注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://physton.github.io/sd-webui-prompt-all-in-one-assets/#/zh-cn/FAQ) 中搜索了此次反馈的问题，没有找到解决方法。
- [x] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [x] 我确认阅读了 [文档](https://physton.github.io/sd-webui-prompt-all-in-one-assets/#/zh-cn/Installation)，没有找到解决方法。

**描述问题**
勾选“我的风格”后，提词标签无法完整收回隐藏，比如正向提示词未完全隐藏，会被下边的反向提示词遮盖部分，如截图所示

**如何复现**
插件设置选项如截图所示

**截图**
![2023-06-16_103541](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/129682674/92b862c9-41a1-47a6-9ebb-331b1bb9f8e8)

**一些必要的信息**
 - Stable Diffusion WebUI 版本: [b6af0a3, 1.3.1]
 - 扩展版本: [dc491f4]
 - 系统: [win11]
 - 浏览器: [chrome]
 - Python 版本: [3.10.11]
 - Gradio 版本: [3.31.0]

**额外的日志**
无

**Comment by Physton** [comment]
不要同时勾选多个主题。

**Comment by gustavmilo** [comment]
谢谢回复，毕竟这样子的样式是目前最喜欢的样式
PS：如果不能同时多选融合的话，那是否能将样式风格设计成单选模式而不是复选模式呢

**Comment by gustavmilo** [comment]
还有 当我只勾选我的风格，其他的勾全去掉的时候，问题还是一样哦
![2023-06-16_182342](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/129682674/92f32697-499d-4f01-8ee6-e1dc24bdf613)

**Comment by Physton** [comment]
这个可能需要 @strongshuai 主题开发者解决。

**Comment by Physton** [comment]
已修复。
