### ISSUE TITLE
[Feature]提供与选择模型相关的提示词

### ISSUE THREAD

**Issue by vngano** [Physton/sd-webui-prompt-all-in-one#129]
提示词多了不方便查找, 可以提供 将提示词归类到指定模型的方式, 在选择了某个模型后会提供与模型绑定的提示词

**Comment by bluelovers** [comment]
在有了 關鍵詞組 這個功能之後 而且支援了 顯示收藏夾

在這種狀況下 可以考慮 如果有安裝 model-keyword 則讀取他的 提示詞表
然後 偵測在提示詞內使用的 lora 清單之後 將 模組相關提示詞都列出來
