### ISSUE TITLE
正面提示词和反面提示词的prompt框连锁显示/隐藏，无法单独隐藏一个

### ISSUE THREAD

**Issue by luanshang** [Physton/sd-webui-prompt-all-in-one#13]

**Comment by Physton** [comment]
目前是显示隐藏是针对全部的框，我会考虑把他们拆分开

**Comment by Physton** [comment]
已经支持！

**Comment by luanshang** [comment]
太好了！多谢啦~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Physton/sd-webui-prompt-all-in-one"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月12日(星期五) 晚上11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Physton/sd-webui-prompt-all-in-one] 正面提示词和反面提示词的prompt框连锁显示/隐藏，无法单独隐藏一个 (Issue #13)





 
已经支持！
