### ISSUE TITLE
[Bug] 提示词无法拖动

### ISSUE THREAD

**Issue by eric23** [Physton/sd-webui-prompt-all-in-one#131]
**反馈须知**

注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ x] 我确认已经在 [常见问题](https://physton.github.io/sd-webui-prompt-all-in-one-assets/#/zh-cn/FAQ) 中搜索了此次反馈的问题，没有找到解决方法。
- [x ] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [ x] 我确认阅读了 [文档](https://physton.github.io/sd-webui-prompt-all-in-one-assets/#/zh-cn/Installation)，没有找到解决方法。

**描述问题**
提示词无法拖拽，鼠标为输入状态不是拖拽状态。

**如何复现**
无额外操作。

**截图**
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/1481250/ce35245a-7ea2-4235-84c7-68ca1b4263f8)

**一些必要的信息**
 - Stable Diffusion WebUI 版本: [1.3.2]
 - 扩展版本: []
 - 系统: [macos]
 - 浏览器: [safari]
 - Python 版本: [3.10.10]
 - Gradio 版本: [3.32.0]

**额外的日志**
在此处添加有关问题的任何日志。

**Comment by eric23** [comment]
In the previous version, it works. I can't remember since when it became unavailable.

**Comment by Physton** [comment]
暂时只在safari浏览器下发现此问题，还未知道解决方案。建议先用其它浏览器。

**Comment by Physton** [comment]
已修复。
