### ISSUE TITLE
[Bug] Unable to click on the keyword expansion button (关键词扩展按钮无法点击)

### ISSUE THREAD

**Issue by mmhan2008** [Physton/sd-webui-prompt-all-in-one#132]
权重没办法加减了

**Comment by Physton** [comment]
刚发现这个问题了，刚好修复了。

**Comment by mmhan2008** [comment]
如此速度👍

**Comment by sos440** [comment]
It seems that deleting keywords in the keyword list by clicking on the x button seems not working anymore.

It has been working perfectly until I reflected today's update. Just for reference, I tested this issue with both Google Chrome and Microsoft Edge browsers.

**Comment by Physton** [comment]
遗漏了一个地方的修改，再更新一下。

**Comment by sos440** [comment]
Thank you so much for a quick update! Now it works :)
