### ISSUE TITLE
[Feature] 是否可以考虑增加一个选项，利用纯本地的翻译模型来翻译。

### ISSUE THREAD

**Issue by youyegit** [Physton/sd-webui-prompt-all-in-one#133]
**这个功能与现有的问题有关吗？**
增加这个选项，主要是考虑在不联网的情况下翻译。

**你想要什么功能或者有什么建议？**
有个类似的插件，利用了 https://huggingface.co/facebook/mbart-large-50-many-to-one-mmt/tree/main  这个模型，实现本地化翻译。如果能融合到本插件中，那真的是 all in one 了！

**有没有可以参考的同类竞品？**
类似的插件 github 地址：
https://github.com/ParisNeo/prompt_translator.git

**其他信息**
不知道有没有其他更好的本地翻译模型，目前我发现的只是 prompt_translator 中提供的。
最后，感谢大大的软件，体验很好！

**Comment by Physton** [comment]
已添加此功能 [bbf408a](https://github.com/Physton/sd-webui-prompt-all-in-one/commit/bbf408ae1907aea95bb8b4c89c6aafe4a615a08f)
