### ISSUE TITLE
[Feature] 建议增加一个是否自动修改关键词的可选按键

### ISSUE THREAD

**Issue by mayjack0312** [Physton/sd-webui-prompt-all-in-one#134]
**Is this feature related to existing issues?**
一些写好的提示词粘贴进去会默认自动修改，同样的提示词再次生成出来之后完全不是一个效果

**What feature do you want or what suggestions do you have?**
增加一个可以手动取消掉自动修改提示词的按键

**Comment by mayjack0312** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> In some cases, if you don't want the plugin to load and change the prompt word of the input box. Just don't click anywhere in the plugins panel.

Okay, I'll give it a try, but isn't the AI inscription in the bottom right corner also useless?

**Comment by Physton** [comment]
AI inscription ? 
I didn't understand what you meant.

**Comment by mayjack0312** [comment]
> AI inscription ? I didn't understand what you meant.

That AI prompt

**Comment by Physton** [comment]
> Okay, I'll give it a try, but isn't the AI inscription in the bottom right corner also useless?

https://physton.github.io/sd-webui-prompt-all-in-one-assets/UsingChatgptToGeneratePrompts.html

**Comment by mayjack0312** [comment]
> > Okay, I'll give it a try, but isn't the AI inscription in the bottom right corner also useless?
> 
> https://physton.github.io/sd-webui-prompt-all-in-one-assets/UsingChatgptToGeneratePrompts.html


ok, i'll try again, thanks
