### ISSUE TITLE
[Feature] 希望能出一个可以配置主题的功能

### ISSUE THREAD

**Issue by liudhzhyym2** [Physton/sd-webui-prompt-all-in-one#135]
希望能出一个可以配置主题的功能，现在只能是黑色主题，看着不太舒服，希望能自己设置，改回原来的白色主题

**Comment by Physton** [comment]
在url后面添加参数试试 `?__theme=light` ：
`http://localhost:7860/?__theme= light`

**Comment by Physton** [comment]
已在设置中增加浅色/深色切换按钮。

**Comment by liudhzhyym2** [comment]
这效率杠杆的
