### ISSUE TITLE
[Feature] Remove the red update circle once the info button is pressed

### ISSUE THREAD

**Issue by Terroosh** [Physton/sd-webui-prompt-all-in-one#138]
**Is this feature related to existing issues?**
No

**What feature do you want or what suggestions do you have?**
Remove the red update circle once the info button is pressed.

![4](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/55752005/73408d87-e1c9-4a1f-bbd1-2e022c8ef3a7)

**Are there any similar competitors that can be referenced?**
No

**Additional information**
Regarding the FAQ entry for an offline environment, if you manually download the extension and then remove the translation packages the version that is shown when the info button is pressed is "Unknown Version" which means the red update circle will always be there.

**Comment by weiluaa** [comment]
同问

**Comment by Physton** [comment]
Modified as:
If you don't open the About page, it won't connect to the internet to check for new versions. The red dot has been removed.
