### ISSUE TITLE
[Bug] Expecting value:line 4 column1 (char 6)

### ISSUE THREAD

**Issue by forhappiness** [Physton/sd-webui-prompt-all-in-one#139]
![1](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/26702481/8157ffb2-9b6d-4e9b-80e0-bb70fa278dfb)

**Comment by forhappiness** [comment]
并不是每次翻译关键词都会出现这个报错，但它现在很不稳定。这是我的问题还是本身就有bug，请告知我如何修复它

**Comment by Physton** [comment]
https://physton.gitee.io/sd-webui-prompt-all-in-one-assets/zh-CN/TranslationApiConfiguration.html#%E7%BF%BB%E8%AF%91%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E
![Snipaste_2023-06-21_13-45-01](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/3af6ab28-6092-46f1-862b-77684befd578)
