### ISSUE TITLE
在输入框输入中文总是报错

### ISSUE THREAD

**Issue by xiaodingdang111232** [Physton/sd-webui-prompt-all-in-one#141]
**反馈须知**

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://physton.github.io/sd-webui-prompt-all-in-one-assets/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [x] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [x] 我确认阅读了 [文档](https://physton.github.io/sd-webui-prompt-all-in-one-assets/zh-CN/)，没有找到解决方法。

**描述问题**
请在此描述你遇到了什么问题。
在输入框中输入文字报错，无法自动翻译成英文
**如何复现**
请告诉我你是通过什么操作触发的该问题。
正常输入自然语言报错，无法自动翻译成英文
**截图**
请在此提供控制台截图、屏幕截图。
![微信截图_20230622022336](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/137329453/4fbd233a-3b43-4132-933e-4aa03b80506b)

**一些必要的信息**
 - Stable Diffusion WebUI 版本: [e.g. b6af0a3, 1.3.1]
 - 扩展版本: [e.g. e0498a1]
 - 系统: [e.g. windows, macos, linux]
 - 浏览器: [e.g. chrome, edge, safari]
 - Python 版本: [e.g. 3.10.11]
 - Gradio 版本: [e.g. 3.31.0]

**额外的日志**
在此处添加有关问题的任何日志。

**Comment by weiluaa** [comment]
同问，已经困扰一天了

**Comment by xiaodingdang111232** [comment]
> 

我也是

**Comment by youdangdedaoyu** [comment]
是不是阿里翻译有问题，换吧

**Comment by Physton** [comment]
![Snipaste_2023-06-22_10-25-05](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/064f9f3a-89f6-4579-b717-098e45fff2a7)
![Snipaste_2023-06-22_10-23-39](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/dd996502-ea51-4487-94cf-93991011bc84)
![Snipaste_2023-06-22_10-23-50](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/5d328075-5310-4dc0-a51d-e35d67d44c95)
![247444420-3af6ab28-6092-46f1-862b-77684befd578](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/5e48dfb9-2758-42a5-af2a-22687d3df61b)

#139
#140
https://github.com/Physton/sd-webui-prompt-all-in-one/issues/137#issuecomment-1601148112
https://github.com/Physton/sd-webui-prompt-all-in-one/issues/137#issuecomment-1601897823

**Comment by weiluaa** [comment]
楼上的兄弟，还是接口问题，阅读文档去注册一个申请后免费使用的ID吧，我已解决问题，好使！
