### ISSUE TITLE
[Feature] 开启了插件，SD-WebUI的主题色变成了黑色

### ISSUE THREAD

**Issue by JoeAu** [Physton/sd-webui-prompt-all-in-one#142]
**这个功能与现有的问题有关吗？**
开启了插件，SD-WebUI的主题色变成了黑色

**你想要什么功能或者有什么建议？**
开启了插件，请不要改变SD-WebUI的主题色

**有没有可以参考的同类竞品？**
无

**其他信息**
插件不要改变主题风格，除非插件本身就是换主题的

**Comment by Physton** [comment]
https://physton.gitee.io/sd-webui-prompt-all-in-one-assets/zh-CN/Theme.html

**Comment by Physton** [comment]
如果不这么做，在有些人的电脑上，会出现显示错乱的问题。
