### ISSUE TITLE
[Feature] Make 

### ISSUE THREAD

**Issue by bubumua** [Physton/sd-webui-prompt-all-in-one#146]
This extension will hightlight embedding prompts those i have, that is great! However when I adjust the embedding prompt's weight to something other than 1, the highlighting doesn't exist.

I hope embedding prompts can be still highlighted if the weight != 1. 

Thank you, i like this extension really, because it shows me what i write Intuitively.

**Comment by Physton** [comment]
Thank you for your suggestion for the extension! This feature is now supported.
