### ISSUE TITLE
[Bug] 部分提示詞彙造成分析錯誤

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#147]
**反馈须知**

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://physton.github.io/sd-webui-prompt-all-in-one-assets/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [x] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [x] 我确认阅读了 [文档](https://physton.github.io/sd-webui-prompt-all-in-one-assets/zh-CN/)，没有找到解决方法。

**描述问题**

部分提示詞彙造成分析錯誤

**如何复现**

```
masterpiece, best quality, , (extremely detailed CG unity 8k wallpaper, masterpiece, best quality, ultra-detailed, best shadow), (chromatic aberration), (beautiful girl:1.5), (beautiful detailed girl:1.1), (ultra-detailed), ((cute face)), ((full body)), (( young girl, depicted in the style of Vincent van Gogh, is holding a fluffy orange and white cat in her arms. The background features swirling brushstrokes in shades of blue and yellow, reminiscent of a starry night sky. The girl has curly brown hair and is wearing a simple dress with bold colors and patterns, reflecting Van Gogh's use of vibrant hues. The cat has big green eyes and a content expression, as if enjoying the girl's affectionate embrace. The overall effect is a charming and whimsical scene that captures the essence of Van Gogh's artistic style )), ((caustic)), dynamic angle, beautiful detailed glow, <lora:add_detail:0.5>, <lora:LowRA:0.5>
```

**截图**
请在此提供控制台截图、屏幕截图。

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/5f86dc5b-c2e4-4dc7-ba12-9e4bfff9ce31)

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/1c0ab162-5eb4-4c19-bc28-dddd4d1fa6bf)

**一些必要的信息**

version:
[v1.3.2-241-g59419bd6](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/59419bd64a1581caccaac04dceb66c1c069a2db1)
 •  python:
3.10.10
 •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint:
[0f5ef4c164](https://google.com/search?q=0f5ef4c1649edde8c11f5b72a460ee6e7582e060aaaaec49efa4948cc1d3d3c1)

網址 | Branch | Commit | Date
-- | -- | -- | --
https://github.com/AUTOMATIC1111/stable-diffusion-webui.git | dev | 59419bd6 | Fri Jun 9 19:47:58 2023

Extension State
擴充功能	網址	Branch	Commit	Date
Cozy-Nest	https://github.com/Nevysha/Cozy-Nest.git	main	[04c834e2](https://github.com/Nevysha/Cozy-Nest/commit/04c834e202b5c891f35f0c1d4b6363ef7220de10)	[Sat Jun 17 07:30:38 2023](https://github.com/Nevysha/Cozy-Nest/commit/04c834e202b5c891f35f0c1d4b6363ef7220de10)
SD-CN-Animation	https://github.com/volotat/SD-CN-Animation.git	main	[2e257bbf](https://github.com/volotat/SD-CN-Animation/commit/2e257bbfc3b76fb1323f7b22f820981c1b9f56b2)	[Tue May 30 16:49:03 2023](https://github.com/volotat/SD-CN-Animation/commit/2e257bbfc3b76fb1323f7b22f820981c1b9f56b2)
Stable-Diffusion-Webui-Civitai-Helper	https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper.git	main	[920ca326](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/commit/920ca3267f789a72e3225c99f069bf0be0db795d)	[Tue May 23 11:53:22 2023](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/commit/920ca3267f789a72e3225c99f069bf0be0db795d)
a1111-sd-webui-locon	https://github.com/KohakuBlueleaf/a1111-sd-webui-locon.git	main	[b6911354](https://github.com/KohakuBlueleaf/a1111-sd-webui-locon/commit/b6911354f7641c49296b37a2b939c3c472624abc)	[Wed Jun 14 13:56:44 2023](https://github.com/KohakuBlueleaf/a1111-sd-webui-locon/commit/b6911354f7641c49296b37a2b939c3c472624abc)
a1111-sd-webui-lycoris	https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git	main	[025dea96](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/025dea96720197dd4486a5bb8e2f4d72a95a3088)	[Wed Jun 14 13:56:41 2023](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/commit/025dea96720197dd4486a5bb8e2f4d72a95a3088)
a1111-sd-webui-tagcomplete	https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git	main	[d7075c54](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/commit/d7075c5468c9483c89253510d2f080c6071bd513)	[Tue Jun 20 16:50:39 2023](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/commit/d7075c5468c9483c89253510d2f080c6071bd513)
adetailer	https://github.com/Bing-su/adetailer.git	main	[a1032d89](https://github.com/Bing-su/adetailer/commit/a1032d898018bd37816f26e2ac1a70c618c1b3e8)	[Tue Jun 20 14:38:19 2023](https://github.com/Bing-su/adetailer/commit/a1032d898018bd37816f26e2ac1a70c618c1b3e8)
multidiffusion-upscaler-for-automatic1111	https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git	main	[de488810](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/commit/de4888103c03d88c0d32af6d453373b47291687a)	[Sun Jun 18 21:39:44 2023](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/commit/de4888103c03d88c0d32af6d453373b47291687a)
prompt-fusion-extension	https://github.com/ljleb/prompt-fusion-extension.git	main	[c8748ddc](https://github.com/ljleb/prompt-fusion-extension/commit/c8748ddc2d3c05b745a5ecfa03b1e2d4b3129a0c)	[Sun Jun 11 01:24:15 2023](https://github.com/ljleb/prompt-fusion-extension/commit/c8748ddc2d3c05b745a5ecfa03b1e2d4b3129a0c)
sd-canvas-editor	https://github.com/jtydhr88/sd-canvas-editor.git	master	[1c0bb3ba](https://github.com/jtydhr88/sd-canvas-editor/commit/1c0bb3bace5fbf3297a05c7b0560b5dcab879fe1)	[Sun Jun 11 02:04:06 2023](https://github.com/jtydhr88/sd-canvas-editor/commit/1c0bb3bace5fbf3297a05c7b0560b5dcab879fe1)
sd-dynamic-prompts	https://github.com/adieyal/sd-dynamic-prompts.git	main	[525ee62a](https://github.com/adieyal/sd-dynamic-prompts/commit/525ee62a9a1ce308a8ae932883be0f4f264282c4)	[Mon Jun 19 09:23:10 2023](https://github.com/adieyal/sd-dynamic-prompts/commit/525ee62a9a1ce308a8ae932883be0f4f264282c4)
sd-webui-bilingual-localization	https://github.com/journey-ad/sd-webui-bilingual-localization.git	main	[89a02280](https://github.com/journey-ad/sd-webui-bilingual-localization/commit/89a02280507627dc40b5d7562691d1f03208f152)	[Thu Apr 27 03:54:25 2023](https://github.com/journey-ad/sd-webui-bilingual-localization/commit/89a02280507627dc40b5d7562691d1f03208f152)
sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	main	[6dc9f34b](https://github.com/Mikubill/sd-webui-controlnet/commit/6dc9f34b98033764bc2fe6a87aaa26d98e9e37b5)	[Fri Jun 23 15:35:23 2023](https://github.com/Mikubill/sd-webui-controlnet/commit/6dc9f34b98033764bc2fe6a87aaa26d98e9e37b5)
sd-webui-cutoff	https://github.com/hnmr293/sd-webui-cutoff.git	main	[3a073e9c](https://github.com/hnmr293/sd-webui-cutoff/commit/3a073e9c4525c21b72ae4645125768457c9c98e1)	[Wed May 3 07:14:40 2023](https://github.com/hnmr293/sd-webui-cutoff/commit/3a073e9c4525c21b72ae4645125768457c9c98e1)
sd-webui-faceswap	https://github.com/Ynn/sd-webui-faceswap	main	[09867dac](https://github.com/Ynn/sd-webui-faceswap/commit/09867dac5731a2daa1629f5a4c36e90c4a6f43dc)	[Sun Jun 18 17:05:41 2023](https://github.com/Ynn/sd-webui-faceswap/commit/09867dac5731a2daa1629f5a4c36e90c4a6f43dc)
sd-webui-lora-block-weight	https://github.com/hako-mikan/sd-webui-lora-block-weight.git	main	[a68ca91f](https://github.com/hako-mikan/sd-webui-lora-block-weight/commit/a68ca91fb39dec18ee248a83ea1017dd7dc696c1)	[Mon Jun 19 14:17:48 2023](https://github.com/hako-mikan/sd-webui-lora-block-weight/commit/a68ca91fb39dec18ee248a83ea1017dd7dc696c1)
sd-webui-photopea-embed	https://github.com/yankooliveira/sd-webui-photopea-embed	main	[f3874a0c](https://github.com/yankooliveira/sd-webui-photopea-embed/commit/f3874a0c7b416553aa042e607511ffedf075e5b4)	[Sat Jun 17 09:46:50 2023](https://github.com/yankooliveira/sd-webui-photopea-embed/commit/f3874a0c7b416553aa042e607511ffedf075e5b4)
sd-webui-prompt-all-in-one	https://github.com/Physton/sd-webui-prompt-all-in-one	main	[bbf408ae](https://github.com/Physton/sd-webui-prompt-all-in-one/commit/bbf408ae1907aea95bb8b4c89c6aafe4a615a08f)	[Fri Jun 23 01:52:50 2023](https://github.com/Physton/sd-webui-prompt-all-in-one/commit/bbf408ae1907aea95bb8b4c89c6aafe4a615a08f)
sd-webui-stablesr	https://github.com/pkuliyi2015/sd-webui-stablesr.git	master	[17b75e98](https://github.com/pkuliyi2015/sd-webui-stablesr/commit/17b75e98360c75b70cb7c9c6be02b886fbd73162)	[Tue May 23 10:12:17 2023](https://github.com/pkuliyi2015/sd-webui-stablesr/commit/17b75e98360c75b70cb7c9c6be02b886fbd73162)
sd_web_ui_preset_utils	https://github.com/Gerschel/sd_web_ui_preset_utils	master	[6e5648df](https://github.com/Gerschel/sd_web_ui_preset_utils/commit/6e5648df1a0944d9e255f6e893ec44d71baefb7c)	[Sun May 28 20:37:30 2023](https://github.com/Gerschel/sd_web_ui_preset_utils/commit/6e5648df1a0944d9e255f6e893ec44d71baefb7c)
stable-diffusion-webui-auto-translate-language	https://github.com/hyd998877/stable-diffusion-webui-auto-translate-language.git	main	[84a0e759](https://github.com/hyd998877/stable-diffusion-webui-auto-translate-language/commit/84a0e759f81f7c973a45be8a5911b92cdd043ff4)	[Tue May 30 07:04:06 2023](https://github.com/hyd998877/stable-diffusion-webui-auto-translate-language/commit/84a0e759f81f7c973a45be8a5911b92cdd043ff4)
stable-diffusion-webui-images-browser	https://github.com/AlUlkesh/stable-diffusion-webui-images-browser.git	main	[b2f6e4cb](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/b2f6e4cbe507078e3bf2b9d5fce6f83e2e233aa8)	[Thu Jun 8 08:11:43 2023](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/b2f6e4cbe507078e3bf2b9d5fce6f83e2e233aa8)
stable-diffusion-webui-localization-zh_TW	https://github.com/benlisquare/stable-diffusion-webui-localization-zh_TW.git	main	[b47c85e0](https://github.com/benlisquare/stable-diffusion-webui-localization-zh_TW/commit/b47c85e0716283cb9463fa54cba90a3dab3eedae)	[Fri Jun 23 16:08:54 2023](https://github.com/benlisquare/stable-diffusion-webui-localization-zh_TW/commit/b47c85e0716283cb9463fa54cba90a3dab3eedae)
stable-diffusion-webui-state	https://github.com/ilian6806/stable-diffusion-webui-state	main	[85d8ef19](https://github.com/ilian6806/stable-diffusion-webui-state/commit/85d8ef191d28a918036881ab47523e0c02467ccc)	[Sat Jun 10 12:39:50 2023](https://github.com/ilian6806/stable-diffusion-webui-state/commit/85d8ef191d28a918036881ab47523e0c02467ccc)
LDSR				
LoRA				
ScuNET				
SwinIR				
canvas-zoom-and-pan				
extra-options-section				
提示括號檢查器

**Comment by Physton** [comment]
![Snipaste_2023-06-26_10-09-40](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/1bd2e81b-e44c-4824-b0a8-a890e6c7290b)
没有复现出错误。
