### ISSUE TITLE
Pasting Has Issues

### ISSUE THREAD

**Issue by ArtaFakhari** [Physton/sd-webui-prompt-all-in-one#15]
Would you please make it able paste like classic webui, in both txt2image and image2image interfaces?

**Comment by Physton** [comment]
sorry, I didn't quite understand specifically what you meant

**Comment by bluelovers** [comment]
我想他的意思是 貼上之後 沒有更新區塊內的標籤

**Comment by Physton** [comment]
@ArtaFakhari After pasting in the default input box of WebUI, you need to manually click on the expansion panel, and then the expansion will read and parse the content inside

@bluelovers Thanks!

**Comment by ArtaFakhari** [comment]
> @ArtaFakhari After pasting in the default input box of WebUI, you need to manually click on the prompt-all-in-one panel, and then the prompt-all-in-one will read and parse the content inside
> 
> @bluelovers Thanks!

@bluelovers is right.
The idea of your extension nice but it makes it a little bit complicated.

**Comment by Physton** [comment]
@ArtaFakhari So, do you have any other suggestions?

**Comment by ArtaFakhari** [comment]
Sure!
Bring back the native functionality of this button ↙️ to read the pasted generation parameters.
Also Infinite Image Browsing extension has simple method to restore the saved prompts. I suggest to merge it with yours.

**Comment by Physton** [comment]
@ArtaFakhari 

The button ↙️ is not malfunctioning. You need to click on it and then enter the content in the pop-up box. If you enter the content directly in the original input box and then click this button, there will be a conflict with this plugin. Therefore, this plugin has modified the paste step accordingly. #4 #21

**Comment by ArtaFakhari** [comment]
Have you tested it on img2img tab too?

**Comment by Physton** [comment]
They have the same ID in the code, so I thought it was the same button. I didn't expect that they are two different buttons.
