### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by cgyy666** [Physton/sd-webui-prompt-all-in-one#150]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

py310\python.exe -m pip install PyExecJS 
 
why？

### OS

Windows

### Browser

Chrome

**Comment by Physton** [comment]
![Snipaste_2023-07-01_19-46-06](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/c9a07d6a-6582-4c69-9ae8-9973bf479475)
