### ISSUE TITLE
[Bug] 无法连接到API并导致插件失效

### ISSUE THREAD

**Issue by anne43983959** [Physton/sd-webui-prompt-all-in-one#152]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

当前启动后无法连接到API，导致插件失效，并且a46e7f2版本会与comfyUI插件冲突导致comfyUI的监听地址被占用
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/115604775/987f661e-a127-49b9-ace8-6c84224ff7cc)

### 操作系统

Windows

### 浏览器

Chrome

### Stable Diffusion WebUI 版本

1.4.1

### 扩展版本

a46e7f2、381b192

### Python 版本

3.10.10

### Gradio 版本

3.32.0

**Comment by Physton** [comment]
这边无法测试到你的问题。并且本插件不会主动监听其它端口，只是继承扩展WebUI监听的接口地址。

**Comment by xuzhhua** [comment]
> 这边无法测试到你的问题。并且本插件不会主动监听其它端口，只是继承扩展WebUI监听的接口地址。

我也遇到了类似的问题。并且在彻底重启SD以后又发生了界面无响应的现象，经多次尝试后无法解决，移除该插件之后问题消失。

**Comment by xuzhhua** [comment]
> > > 这边无法测试到你的问题。并且本插件不会主动监听其它端口，只是继承扩展WebUI监听的接口地址。
> > 
> > 
> > 我也遇到了类似的问题。并且在彻底重启SD以后又发生了界面无响应的现象，经多次尝试后无法解决，移除该插件之后问题消失。
> 
> 建议卸载插件，删除插件目录，重装试试。

感谢回复。完全卸载并删除插件目录后再重装，奇怪的现象消失了，可以正常使用。
我会继续观察，后续如有情况再联络，谢谢
