### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by shiyk92** [Physton/sd-webui-prompt-all-in-one#157]
### 这个功能与现有的问题有关吗？

希望能再comfyui中用到这个插件

### 你想要什么功能或者有什么建议？

希望能再comfyui中用到这个插件

### 其他信息

希望能再comfyui中用到这个插件

**Comment by Physton** [comment]
![3896862B](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/cf66d848-9cf0-4939-bdd2-79e2473c23d5)未来都没有做comfyui插件的想法。
