### ISSUE TITLE
[Feature] 支援在 `BREAK` 關鍵字後方拆分 與 斷行

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#158]
### 你想要什么功能或者有什么建议？

1. `1girl, BREAK bohemian style`
2. `1girl, BREAK, bohemian style`

=>

```
1girl,
BREAK, 
bohemian style
```

當 `BREAK` 在標籤區段的開頭的時候 才拆分

**Comment by Physton** [comment]
我没明白你具体指的什么意思。

**Comment by bluelovers** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/e02ec892-7d71-41af-958d-85270a4bef76)

=>

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/008122cf-17ff-49d2-8260-07ef507047a4)

-------------

另外希望能將 break 顯示為分隔線的風格

例如 `--------------------- BREAK -----------------` 這種感覺

**Comment by Physton** [comment]
![CleanShot 2023-08-04 at 14 38 17@2x](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/5a21311f-123a-4707-9930-bc39b651f544)
已支持。
