### ISSUE TITLE
[Feature] 支援從 歷史與收藏內 插入提示詞

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#159]
### 这个功能与现有的问题有关吗？

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/ba4538d3-1da9-4704-91b8-1bbe54cbf0b6)

### 你想要什么功能或者有什么建议？

現有的功能只能選擇取代全部
但希望能夠支援插入而不是取代

**Comment by Physton** [comment]
https://aiodoc.physton.com/zh-TW/KeywordInputBox.html
![Snipaste_2023-08-03_10-57-33](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/f6865bb5-411b-48fe-8381-786cfd64d146)

**Comment by Physton** [comment]
> 那在請問一下能夠編輯已經存進去的收藏嗎?

无法直接编辑，因为要重做一套交互界面功能。
目前如果需要编辑，只能使用收藏，然后修改，然后重新收藏。
或者到插件目录下直接修改favorites.json文件。
