### ISSUE TITLE
openAI/chatgpt是否可以正常使用呢？

### ISSUE THREAD

**Issue by Maiyomi** [Physton/sd-webui-prompt-all-in-one#16]
API kay正确，但无法正常使用，翻译测试却超时
![QQ截图20230513005936](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/76479801/433f62cf-d439-4766-85a4-1d09eecc2edf)

**Comment by Physton** [comment]
一般的梯子软件，未经过设置，在系统命令行中是无效的。而python就运行在命令行终端中。

**Comment by Maiyomi** [comment]
目前使用clash

**Comment by Physton** [comment]
你可以跟换无需梯子就能访问到的api地址，图中的API Base，这个你自己去网站寻找吧

**Comment by Maiyomi** [comment]
非常感谢
