### ISSUE TITLE
[Bug] 收藏或歷史內提示詞的翻譯邏輯似乎不同

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#160]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

歷史

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/7b32e8ff-cc39-4ce8-b992-5035d4377bb1)

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/8f0587be-ec0c-4b34-a4f7-db9a0055f3a2)

收藏

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/2de7a6b0-2eb3-4aac-b6ed-0d0ef8f9338c)

### 操作系统

Windows

### 浏览器

Chrome

**Comment by bluelovers** [comment]
那也許可以考慮 將 收藏與歷史內的已翻譯內容 額外紀錄 作為 類似 csv 離線翻譯一樣
然後當瀏覽時 就統一使用最後的已翻譯內容

---

並且可以拿來當 csv 翻譯的輔助

一般提示時輸入時 的 自動翻譯 以 `csv 翻譯 > 網路翻譯 > 收藏與歷史內的緩存翻譯` 做為顯示
在手動網路翻譯時 則忽略 `收藏與歷史內的緩存翻譯` 但如果翻譯失敗 則繼續使用 `收藏與歷史內的緩存翻譯`

**Comment by bluelovers** [comment]
清除歷史的時候 一併清除 緩存翻譯

**Comment by Physton** [comment]
https://github.com/Physton/sd-webui-prompt-all-in-one/commit/fbfd2a50757246b64621b68bf6daadc54f5f0c1f
这个版本已支持使用关键词组的内容用于翻译。

收藏和历史记录用于翻译，我觉得没有必须，现在翻译的功能已经太复杂了。
不如说每次的翻译记录都单独永久存储，手动清除（目前是每次启动了WEBUI就一直缓存，直到重新启动自动清除）。
