### ISSUE TITLE
[Feature] 是否可以在java中集成

### ISSUE THREAD

**Issue by Galaxy-Lqy** [Physton/sd-webui-prompt-all-in-one#164]
### 这个功能与现有的问题有关吗？

无关

### 你想要什么功能或者有什么建议？

我想问一下这个插件功能是否可以集成到java程序中，或者提供一些在java中可以调用的API？

**Comment by Physton** [comment]
没明白你要做什么，sd插件都是python后端加js前端。
如果要调用python实现的api，可以看插件源码或者抓包。
