### ISSUE TITLE
[Bug] The prompt input box and the translate generate prompt option are out of sync

### ISSUE THREAD

**Issue by tim9292654** [Physton/sd-webui-prompt-all-in-one#165]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

有人知道这是怎么回事吗,我在上面提示词输入了1,下面提示词翻译不生成对应的1 tag选项,昨天晚上还好好的,我今天早上更新了几个插件就这样了,
按了回车,点击旁边空白都不行了,就只能在提示词翻译输入框哪里输入才生成,
我只有点历史和收藏的标签才显示,不和输入框同步

### 如何复现

我昨天晚上用的好好的,就今天早上更新了几个插件,就变成这样了,更新了这个a1111-sd-webui-tagcomplete

### 截图或日志

![WHA4R7_6UH%~DC4NB~JQLXW](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/29449662/b4320f9f-ed7b-4830-b62c-893fca62af6c)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/29449662/1156db04-c749-47bb-be32-05992477bfe2)

### 操作系统

Windows

### 浏览器

Edge

### Stable Diffusion WebUI 版本

1.5.1

### 扩展版本

700306c

### Python 版本

3.10.11

### Gradio 版本

3.32.0

**Comment by Physton** [comment]
确实是更新了 tagcomplete 引起的。我在想办法修复。

**Comment by Physton** [comment]
修复了，再试试。
