### ISSUE TITLE
[Feature] 建议持久化存储外观样式

### ISSUE THREAD

**Issue by wzddl** [Physton/sd-webui-prompt-all-in-one#166]
### 这个功能与现有的问题有关吗？

1. 浅色模式与Stable Diffusion的UI更协调，因此我经常使用浅色模式
2. 现在通过 "?__theme=light" 的query参数方式临时更变外观一旦页面关闭后则丢失更改，每次需要重新选择比较不便，并且即使页面载入完成后也会存在FOUC闪烁问题

### 你想要什么功能或者有什么建议？

1. 我是一名web前端开发者，我没有开发过Stable Diffusion的扩展，我对相关API不太清楚
2. 实在不行可以考虑将数据封装写入localstorage，通过storage相关API读写配置，以减少FOUC问题 & 改善样式丢失问题

### 其他信息

感谢你的付出，如果有需要，我也可以提供一定的帮助~

**Comment by Physton** [comment]
几点解决办法：

1. 收藏带有浅色query的网址。
2. WEBUI中配置主题浅色 or 深色。
3. 配置WEBUI启动参数。
4. 某些启动器选择默认打开浅色深色的功能。

由于不同用户的WEBUI环境复杂，如果使用插件默认存储主题颜色，可能会造成很多问题。

**Comment by wzddl** [comment]
> 几点解决办法：
> 
> 1. 收藏带有浅色query的网址。
> 2. WEBUI中配置主题浅色 or 深色。
> 3. 配置WEBUI启动参数。
> 4. 某些启动器选择默认打开浅色深色的功能。
> 
> 由于不同用户的WEBUI环境复杂，如果使用插件默认存储主题颜色，可能会造成很多问题。
> 

谢谢，这些方法我都知晓
我自行修改代码解决吧
