### ISSUE TITLE
[Feature] integration with the permanently free API DeepL

### ISSUE THREAD

**Issue by mikheys** [Physton/sd-webui-prompt-all-in-one#167]
### What feature do you want or what suggestions do you have?

Good afternoon. There is an implementation of a persistent-free API DeepL using DeepL X and PyDeepLX. Maybe you could friend your extension and these libraries? DeepL is very shorish to translate!

https://github.com/OwO-Network/DeepLX
https://github.com/ptrstn/deepl-translate
https://github.com/OwO-Network/PyDeepLX

**Comment by Physton** [comment]
These methods involve using a web crawler to access the DeepL website for translation, but the stability is very poor.
I initially considered this approach, but after testing, I found that it often fails to work properly, and the situation worsens when performing batch translations.
Obtaining an official API key from DeepL is also very simple, and the free quota provided after application is generally sufficient for translation.
