### ISSUE TITLE
[Feature] 提示詞黑名單功能

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#168]
### 你想要什么功能或者有什么建议？

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/bfaca5b8-1091-47d3-b697-424502efaf8e)

假設將 `masterpiece, best quality` 設為黑名單

則日後在輸入

```
masterpiece, best quality, sfJuli, blue eyes, brown hair, hat, necktie, red gloves, ribbed bodysuit, large breasts, upper body, emotionless, looking at viewer, indoors, futuristic building <lora:junijuli-nvwls-v1-000009:0.9>
```

時會自動變成

```
sfJuli, blue eyes, brown hair, hat, necktie, red gloves, ribbed bodysuit, large breasts, upper body, emotionless, looking at viewer, indoors, futuristic building <lora:junijuli-nvwls-v1-000009:0.9>
```

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/dc484e13-3fe8-41d5-acc3-7645e9d4e241)

### 有没有可以参考的同类竞品？

https://github.com/viyiviyi/prompts-filter

**Comment by bluelovers** [comment]
另外可以的話 也希望支援 lora 黑名單

例如 `add_detail`

則不管是 `<lora:add_detail:0.4>` or `<lora:add_detail:1>` 都會被自動清除

**Comment by Physton** [comment]
最近在忙另一个大功能，这个往后延期一些时日。

**Comment by Physton** [comment]
![2f4997802d80d9ef6513df30396cd9b7](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/c14709ba-186d-4b0a-8dd4-363c5b7b4d24)
已开发完成。

**Comment by bluelovers** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/97715a1e-9385-4bc5-a13d-d5b3a50efa2b)

似乎沒有過濾掉

**Comment by Physton** [comment]
> ![image](https://user-images.githubusercontent.com/167966/261449643-97715a1e-9385-4bc5-a13d-d5b3a50efa2b.png)
> 
> 似乎沒有過濾掉

已修复

**Comment by bluelovers** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/ced30d38-2cfb-49cd-b935-40efbb44d501)

似乎沒有忽略大小寫
