### ISSUE TITLE
[Feature] 请求在收藏列表旁加一个预设搜索栏

### ISSUE THREAD

**Issue by ligerye** [Physton/sd-webui-prompt-all-in-one#169]
### 你想要什么功能或者有什么建议？

很喜欢可以一键把提示词打包收藏的功能，还可以将禁用掉的词汇作为可选项和启用词一起存储，有很多可玩性和便捷性，基本已经替代了原生的csv文件的作用，但是当收藏的词组过多时，单靠着滚动会不方便查找想要的预设。
大大能不能在收藏列表栏边上追加一个搜索框，通过预设名称来快速搜索想要的，就不需要靠拖滚动条来慢慢找了。

**Comment by Physton** [comment]
关键词较多的话，刚刚上线的新功能可能更适合你的需求，也可以自定义。

[文档](https://aiodoc.physton.com/zh-CN/GroupTags.html)
![](https://s1.imagehub.cc/images/2023/08/15/demo.group_tags.gif)

**Comment by chen135347542093** [comment]
> 关键词较多的话，刚刚上线的新功能可能更适合你的需求，也可以自定义。
> 
> [文档](https://aiodoc.physton.com/zh-CN/GroupTags.html) ![](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966) [ ![68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966) ](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966) [ ](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966)

如何自定义添加自己的提示词

**Comment by Physton** [comment]
https://aiodoc.physton.com/zh-CN/GroupTags.html

**Comment by ligerye** [comment]
> 关键词较多的话，刚刚上线的新功能可能更适合你的需求，也可以自定义。
> 
> [文档](https://aiodoc.physton.com/zh-CN/GroupTags.html) ![](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966) [ ![68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966) ](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966) [ ](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966)

感谢大大了，词汇分组也是个很方便功能，能自定义很棒；
另外其实这个提议的想法其实是如下图所示，请问是收藏架构不方便支持按名搜索吗？
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/d8ddf8a4-7904-4739-bdf1-dae023b4a8e1)

**Comment by Physton** [comment]
> > 关键词较多的话，刚刚上线的新功能可能更适合你的需求，也可以自定义。
> > [文档](https://aiodoc.physton.com/zh-CN/GroupTags.html) ![](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966) [ ![68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966) ](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966) [ ](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966)
> 
> 感谢大大了，词汇分组也是个很方便功能，能自定义很棒； 另外其实这个提议的想法其实是如下图所示，请问是收藏架构不方便支持按名搜索吗？ ![image](https://user-images.githubusercontent.com/60023469/260909887-d8ddf8a4-7904-4739-bdf1-dae023b4a8e1.png)

目前的结构确实不好做这个功能，而且输入框为了tagcomplete做了兼容，更不好处理了。
要么说把收藏页放到下方的关键词组最前面一列。这样展示的就更清晰一些。

**Comment by ligerye** [comment]
> 

感谢回答，如果不好做可以理解，就目前而言其实诸多功能也很好用了xD

**Comment by ligerye** [comment]
> > > 关键词较多的话，刚刚上线的新功能可能更适合你的需求，也可以自定义。
> > > [文档](https://aiodoc.physton.com/zh-CN/GroupTags.html) ![](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966) [ ![68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966) ](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966) [ ](https://camo.githubusercontent.com/500d1f1edab0ebfcc444cd6b5d03251f0d39068f36828130e14c6098ab475c0f/68747470733a2f2f73312e696d6167656875622e63632f696d616765732f323032332f30382f31352f64656d6f2e67726f75705f746167732e676966)
> > 
> > 
> > 感谢大大了，词汇分组也是个很方便功能，能自定义很棒； 另外其实这个提议的想法其实是如下图所示，请问是收藏架构不方便支持按名搜索吗？ ![image](https://user-images.githubusercontent.com/60023469/260909887-d8ddf8a4-7904-4739-bdf1-dae023b4a8e1.png)
> 
> 目前的结构确实不好做这个功能，而且输入框为了tagcomplete做了兼容，更不好处理了。 要么说把收藏页放到下方的关键词组最前面一列。这样展示的就更清晰一些。

感谢回答，如果不好做可以理解，就目前而言其实诸多功能也很好用了xD

**Comment by Physton** [comment]
已将收藏列表默认加到了关键词组的第一页。
