### ISSUE TITLE
支援翻譯檔加速並且減少網路查詢翻譯的請求

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#17]
[danbooru-0-zh.csv](https://github.com/Physton/sd-webui-prompt-all-in-one/files/11468563/danbooru-0-zh.csv)

https://github.com/DominikDoom/a1111-sd-webui-tagcomplete#translations

**Comment by bluelovers** [comment]
https://magic-tag.netlify.app/#webview

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/8589f7d0-0635-4f38-b760-99f2c0de07ae)

**Comment by Physton** [comment]
凌晨3点多的更新已经支持过a1111-sd-webui-tagcomplete。自述文件里有demo图。你需要更新到最新版本并且保证a1111-sd-webui-tagcomplete已安装到最新版本。

**Comment by bluelovers** [comment]
不是 tagcomplete 的部分 而是指 

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/068ea290-d64d-4104-952d-24dca92059b2)

**Comment by Physton** [comment]
明白了，未来可以考虑。

**Comment by Physton** [comment]
我考虑有两种方式做这个功能。

1. 只要安装了tagcomplete，调用他的csv数据。
2. 把csv数据拷贝到我的项目中，使用 danbooru.语言代码.csv 文件名格式。调用自己的csv文件。

你推荐哪种？

**Comment by bluelovers** [comment]
3. 設定翻譯檔路徑

**Comment by Physton** [comment]
@bluelovers 已开发完成
