### ISSUE TITLE
[Feature] 能否将汉服归类在一起？谢谢！

### ISSUE THREAD

**Issue by bj803** [Physton/sd-webui-prompt-all-in-one#171]
### What feature do you want or what suggestions do you have?

1,能否将唐风、宋风、明风归类在汉服下面，也就是说一、二级是分类名，三级才是分类列表。
2,能否单独设个一级分类名为：反推。用来放反推用词。
3,能否增添个独立的一级按钮指向custom.yaml文件。

谢谢！加油哦！

**Comment by Physton** [comment]
1,能否将唐风、宋风、明风归类在汉服下面，也就是说一、二级是分类名，三级才是分类列表。
> 已放到一个分类。
> ![Snipaste_2023-08-16_10-30-00](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/3143501b-98a0-41b1-aeec-ec710266dc51)

2,能否单独设个一级分类名为：反推。用来放反推用词。
> 需要有人整理优化反推提示词。

3,能否增添个独立的一级按钮指向custom.yaml文件。
> custom.yaml 目前的作用是覆盖。
> 之后会做一个 append.yaml 专门用于在当前关键词组后面追加。

**Comment by Physton** [comment]
已添加 prepend.yaml 和 append.yaml 功能。
具体参考文档：https://aiodoc.physton.com/zh-CN/GroupTags.html

**Comment by bj803** [comment]
谢谢！谢谢！用上了！太好了！
附上反推提示词:
反向提示:
  NSFW: nsfw,logo,text
  Embeddings: AS-YoungV2-neg,BadDream,badhandv4,BadNegAnatomyV1-neg,EasyNegative,FastNegativeV2
  常用反向: blurry,low quality,bad anatomy
  移除成年人: (AS-YoungV2-Neg:1.3)
  移除年轻人: (AS-Adult-Neg:1.3)
  变异手指: mutated hands and fingers
  畸形的: deformed
  解剖不良: bad anatomy
  毁容: disfigured
  脸不好: poorly drawn face
  变异的: mutated
  多余肢体: extra limb
  丑陋: ugly
  手画得差: poorly drawn hands
  缺少的肢体: missing limb
  漂浮的四肢: floating limbs
  肢体不连贯: disconnected limbs
  畸形的手: malformed hands
  脱离焦点: out of focus
  长颈: long neck
  身体长: long body
  头发正常下垂: windy
  全选: nsfw,logo,text,badhandv4,EasyNegative,ng_deepnegative_v1_75t,rev2-badprompt,verybadimagenegative_v1.3,negative_hand-neg,mutated hands and fingers,poorly drawn face,extra limb,missing limb,disconnected limbs,malformed hands,ugly,blur,windy
  反向提示1: easynegative, paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), extra fingers, fewer fingers, strange fingers, bad hand, bad anatomy, fused fingers, missing leg, mutated hand, malformed limbs, missing feet,(Fake eyelashes:1.5),(masculine:1.5), strange lips,strange eyes,(wide mouth:1.5),
  反向提示2: (worst quality:2), (low quality:2), (normal quality:2), ((monochrome)), ((grayscale)),paintings, sketches, skin spots, acnes, skin blemishes, bad anatomy, facing away, looking away, tilted head, multiple girls, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, blurry, bad feet, cropped, poorly drawn hands, poorly drawn face, mutation, deformed, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, extra fingers, fewer digits, extra limbs, extra arms, extra legs, malformed limbs, fused fingers, too many fingers, long neck, cross-eyed, mutated hands, polar lowres, bad body, bad proportions, gross, extra breasts, ng_deepnegative_v1_75t, bad-hands-5

**Comment by Physton** [comment]
> 谢谢！谢谢！用上了！太好了！ 附上反推提示词: 反向提示: NSFW: nsfw,logo,text Embeddings: AS-YoungV2-neg,BadDream,badhandv4,BadNegAnatomyV1-neg,EasyNegative,FastNegativeV2 常用反向: blurry,low quality,bad anatomy 移除成年人: (AS-YoungV2-Neg:1.3) 移除年轻人: (AS-Adult-Neg:1.3) 变异手指: mutated hands and fingers 畸形的: deformed 解剖不良: bad anatomy 毁容: disfigured 脸不好: poorly drawn face 变异的: mutated 多余肢体: extra limb 丑陋: ugly 手画得差: poorly drawn hands 缺少的肢体: missing limb 漂浮的四肢: floating limbs 肢体不连贯: disconnected limbs 畸形的手: malformed hands 脱离焦点: out of focus 长颈: long neck 身体长: long body 头发正常下垂: windy 全选: nsfw,logo,text,badhandv4,EasyNegative,ng_deepnegative_v1_75t,rev2-badprompt,verybadimagenegative_v1.3,negative_hand-neg,mutated hands and fingers,poorly drawn face,extra limb,missing limb,disconnected limbs,malformed hands,ugly,blur,windy 反向提示1: easynegative, paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), extra fingers, fewer fingers, strange fingers, bad hand, bad anatomy, fused fingers, missing leg, mutated hand, malformed limbs, missing feet,(Fake eyelashes:1.5),(masculine:1.5), strange lips,strange eyes,(wide mouth:1.5), 反向提示2: (worst quality:2), (low quality:2), (normal quality:2), ((monochrome)), ((grayscale)),paintings, sketches, skin spots, acnes, skin blemishes, bad anatomy, facing away, looking away, tilted head, multiple girls, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, blurry, bad feet, cropped, poorly drawn hands, poorly drawn face, mutation, deformed, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, extra fingers, fewer digits, extra limbs, extra arms, extra legs, malformed limbs, fused fingers, too many fingers, long neck, cross-eyed, mutated hands, polar lowres, bad body, bad proportions, gross, extra breasts, ng_deepnegative_v1_75t, bad-hands-5

感谢，已添加
