### ISSUE TITLE
after update it breaks the arrangement of ui [Bug] 

### ISSUE THREAD

**Issue by esirt** [Physton/sd-webui-prompt-all-in-one#172]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

after update specially when the new clickable options become available it breaks the ui arrangement and place the generated image at the bottom 

### Steps to Reproduce

install extention
activate extention
restart ui
....

### Screenshot or log

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/45271026/02d3d223-80bf-4702-ac6a-320191c51a6e)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/45271026/ee49361b-43cd-4743-8b34-9cc5024488a8)

### OS

Windows

### Browser

Chrome

### Stable Diffusion WebUI version

 v1.5.1-479-g7327be97

### Python version

3.10.11

### Gradio version

 3.39.0

**Comment by Physton** [comment]
![Snipaste_2023-08-18_00-49-17](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/1512c09a-daf1-4525-b5fe-78373b88d800)
Testing revealed that it was caused by this theme.

**Comment by Physton** [comment]
The developer of the hellostyle theme developed it under the webui kitchen(lobe) theme and did not adapt it to the default theme. It is possible to consider not using the hellostyle theme.

**Comment by esirt** [comment]
i disable the theme. thank you <3 
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/45271026/73948364-6326-4106-8317-4ad72fa6ba49)

**Comment by Physton** [comment]
The compatibility issues with the HelloStyle theme have been fixed. You can now enable the HelloStyle theme.
