### ISSUE TITLE
能否将设置栏放置在工具栏的末尾位置

### ISSUE THREAD

**Issue by dale003** [Physton/sd-webui-prompt-all-in-one#173]
### 这个功能与现有的问题有关吗？

在常规的使用习惯中，绝大多数鼠标的移动和文字的阅读总是保持在从左到右的顺序，在使用该插件时，每次移动鼠标使用功能时，总是会唤醒设置菜单，而设置菜单内的功能又和后面的功能在选择位置上保持在同一高度，所以经常要多次调整鼠标的位置，才能成功选择自己需要的功能，同时设置菜单内的选项基本很少需要改动，所以建议放置在工具栏从左到右的末尾位置。
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/37768614/bae5f9ae-4d25-4564-86c9-214a8d71e373)

### 你想要什么功能或者有什么建议？

功能栏中的设置选项放置在从左到右排列方向的末尾位置。
或者在弹出设置窗口时，功能的UI位置不要和后面的功能重叠，可以弹出在下面/上面。
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/37768614/18651dc1-c015-48b1-8e95-21249be81d82)

**Comment by Physton** [comment]
已在扩展主题中增加。
