### ISSUE TITLE
[Feature] Prevent prompt token tooltips from showing up on hover

### ISSUE THREAD

**Issue by SirMoogle** [Physton/sd-webui-prompt-all-in-one#175]
### What feature do you want or what suggestions do you have?

Currently when you hover a prompt token with this extension the toolbar to adjust weight or add it to favourites immediately shows up and blocks any tokens that are underneath it. Can this be changed to only show up if I click and select that token?

**Comment by Physton** [comment]
The current functionality is to edit keywords with a single mouse click, and double-clicking disables/enables the keywords.

I am considering using the right mouse button click to expand the keyword operation panel, so the mouse hover to expand feature needs to be removed. This change may affect the current user habits.

Therefore, it is necessary to develop a feature that allows setting mouse button behavior.

It may take some time to support this feature.

**Comment by Physton** [comment]
![Snipaste_2023-08-22_14-49-35](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/064f3416-45b6-46f1-889b-5d1eaace6b35)
![Snipaste_2023-08-22_14-49-56](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/21e4c717-515f-4793-836d-1f5fb9931fbd)
The feature has been developed and completed. Set it up like this.

**Comment by Physton** [comment]
> Thank you! This was what I was looking for. :)
> 
> One thing: is it possible to keep the extend panel active when clicking to adjust weight? I click on it once and it disappears.

Fixed.

**Comment by SirMoogle** [comment]
Much appreciated!
