### ISSUE TITLE
[Bug] Generated Picture not under Generate button anymore

### ISSUE THREAD

**Issue by defender107** [Physton/sd-webui-prompt-all-in-one#178]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

At first, thanks a lot for creating this excellent extension. It is extremely useful and powerful :)
I did an update of the extension and since then, the generated picture viewer is not under the generate button anymore, but at the button of the page. There it is hardly usable.
I tried Chrome, Firefox, Edge and it is always the same. I have no idea how to adjust the layout in a way that the picture view is below the Generate button again, I hope you can help me. 

### Steps to Reproduce

Start automatic1111
- Picture viewer is under the generate button
- extension loads and the picture viewer moves to buttom of page
- does not happen with extension disabled.

### Screenshot or log

When automatic 1111 is initializing, all good
![grafik](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/142727617/ee6b5b05-8071-436e-a72f-156d15125bd5)

After extension is loaded, note the picture viewer is not under the generate button anymore
![grafik](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/142727617/447bf476-ec00-45ba-b123-6b04cfd98ec6)

### OS

Windows

### Browser

Firefox

### Stable Diffusion WebUI version

v1.5.1 

### Extension version

0e3fd2d7

### Python version

 python: 3.10.11  

### Gradio version

 gradio: 3.32.0

**Comment by Physton** [comment]
#172 Please refer to this issue.

https://aiodoc.physton.com/ThemeStyle.html

**Comment by defender107** [comment]
Thanks a lot that solved it! It was the hellostyle.

**Comment by Physton** [comment]
The compatibility issues with the HelloStyle theme have been fixed. You can now enable the HelloStyle theme.
