### ISSUE TITLE
[Bug] 加载最新版本后重启ui主页不显示插件相关组件且拓展页面中已安装页面无法加载出来

### ISSUE THREAD

**Issue by RealSlakey** [Physton/sd-webui-prompt-all-in-one#179]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

加载最新版本后重启ui主页不显示插件相关组件且拓展页面中已安装页面无法加载出来，本地插件文件夹删除后，拓展页面恢复正常

### 操作系统

macOS

### 浏览器

Edge

### Stable Diffusion WebUI 版本

1.5.1

**Comment by Physton** [comment]
macos测试无法复现你的问题。请提供更多的版本信息、控制台日志截图等。

**Comment by RealSlakey** [comment]
2023-08-20 23:18:51,305 - ControlNet - INFO - ControlNet v1.1.238
sd-webui-prompt-all-in-one background API service started successfully.
./webui.sh: line 254:  8150 Segmentation fault: 11  "${python_cmd}" "${LAUNCH_SCRIPT}" "$@"
/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by RealSlakey** [comment]
<img width="1440" alt="image" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/13360040/b25112b3-8913-4179-8e14-d48006390777">

**Comment by RealSlakey** [comment]
重新安装几次后，突然正常了
