### ISSUE TITLE
希望添加对换行、分隔符、分类的支持

### ISSUE THREAD

**Issue by anne43983959** [Physton/sd-webui-prompt-all-in-one#18]
当前版本打开提示词编辑后，会自动格式化提示词，所有换行都会被取消，但换行是唯一一种不影响token识别的分类、分段方式，希望后续版本中能加入提示词分段、自动识别换行、添加权重为0的分隔符的功能

尤其对于使用了latent couple的超长提示词，换行是必须的，甚至需要将AND单独作为一行分隔上下两段子提示词，不过对于现版本来说，使用从其他地方发送到页面的提示词时自动关闭插件功能确实非常实用，在分段功能实装之前请保留这个特性

**Comment by Physton** [comment]
#10 对于逗号后面多个空格都很介意

**Comment by Elysiel** [comment]
我更希望每个逗号后都有一个空格而不是把它们全部trim掉

**Comment by Physton** [comment]
所以这我不知道该听谁的意见了

**Comment by Elysiel** [comment]
建议连续的空格和换行符只保留一个，其他分隔符除非提前设置一律trim

**Comment by anne43983959** [comment]
> 所以这我不知道该听谁的意见了

这个好办，加个复选框或者在设置中添加一个独立的默认选项设置页就好了，需求有冲突的时候最好还是提供给用户选择，虽然会增大工作量，但是毕竟只是个特性请求，慢慢做就是了

**Comment by seamyctl** [comment]
换行自动消掉 会对一些分区绘画的插件产生影响。比如rogional prompter分区绘画插件的格式就是是
tag1,tag2,tag3 ADDCOL
tag4,tag5,tag6 ADDROW
tag7,
这样的

**Comment by Physton** [comment]
@seamyctl `ADDCOL`是针对`tag1,tag2,tag3`都有效，还是只针对`tag3`

**Comment by seamyctl** [comment]
针对tag1,tag2,tag3都有效，  也就是一个区域 填一批tag 结尾用 空格 + ADDCOL/ADDROW标识词 + 换行

**Comment by Physton** [comment]
@seamyctl 明白了，我尽快修改。

**Comment by Physton** [comment]
已经加了对换行的支持， @seamyctl 分区绘图我这测试过了已经没问题。

**Comment by seamyctl** [comment]
这边也测了下，确实没有问题，太感谢大佬了

**Comment by Physton** [comment]
@Elysiel @seamyctl @anne43983959 @StimeKe 
这个issues我关闭了，如有解析问题移步到 #20
