### ISSUE TITLE
[Feature] 增加 新增至黑名單 按鈕

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#180]
### 你想要什么功能或者有什么建议？

這樣對於在新增黑名單時 比較便利

**Comment by Physton** [comment]
![Snipaste_2023-08-22_15-18-13](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/bd64d8dd-05f5-46c8-a294-ee16e65e3e7c)
已开发完成。
