### ISSUE TITLE
[Bug] Enter key does not get selection with the tagcomplete extension

### ISSUE THREAD

**Issue by Terroosh** [Physton/sd-webui-prompt-all-in-one#182]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

When you select a tag in tagcomplete with the keyboard keys and then press enter, you will only get the text you typed and not the correct tag. Clicking on the tag does work though.

The GIF below shows me showing the correct behavior in the default text box, then I show how it doesn't work in sd-webui-prompt.

### Steps to Reproduce

1. Type girl
2. Press Down on your keyboard and then press Enter
3. The expected result is to have the "1girl" tag be added to the prompt, instead "girl" is added.

### Screenshot or log

![grab](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/55752005/6cfdfc21-6e4a-4d5e-98db-cede02983016)

### OS

Windows

### Browser

Firefox

### Stable Diffusion WebUI version

1.5.2

### Extension version

8625402

### Python version

3.10.6

### Gradio version

3.32.0

**Comment by Physton** [comment]
Fixed.
