### ISSUE TITLE
表情描述符号>_<，导致后面的关键词标记为一个词组了

### ISSUE THREAD

**Issue by dale003** [Physton/sd-webui-prompt-all-in-one#183]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

如果表情符号>_<放置在关键词列表中时，在表情符后面的词组会被识别成一个词组。
![Snipaste_2023-08-24_18-29-53](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/37768614/19c915c9-be93-4d0d-a01d-5739422e2076)
![Snipaste_2023-08-24_18-30-43](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/37768614/ff92c031-dc65-4bca-91db-2a38aedbc6c5)

### 操作系统

Windows

### 浏览器

Chrome

### 扩展版本

15821560

**Comment by Physton** [comment]
已修复。
