### ISSUE TITLE
[Feature] Allow lora weight to go negative

### ISSUE THREAD

**Issue by Terroosh** [Physton/sd-webui-prompt-all-in-one#186]
### What feature do you want or what suggestions do you have?

Slider loras and transformation loras often have negative weights for a certain outcome. For example the eye slider lora goes from -8.0 to 8.0. Negative for smaller eyes, positive for bigger eyes. Currently you can't go below 0.1, please allow for the minus button to go below 0.

![1](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/55752005/0eb67020-e1af-4517-a2ce-84c6fa9a958a)

**Comment by Physton** [comment]
Completed.
