### ISSUE TITLE
[Feature] How to delete  favorite tag in a group

### ISSUE THREAD

**Issue by dongshaojia** [Physton/sd-webui-prompt-all-in-one#187]
### Is this feature related to existing issues?

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/63761073/cc86288c-531f-4aca-89e3-8cf6a0c7a5a9)

### What feature do you want or what suggestions do you have?

delete  favorite tag

**Comment by a857313401** [comment]
看这里![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/129591199/447e44b1-3656-44d5-b2e0-cbccab8b84d0)
