### ISSUE TITLE
[Bug] After updating to the latest version on 8/26, the separator will automatically disappear.

### ISSUE THREAD

**Issue by a857313401** [Physton/sd-webui-prompt-all-in-one#190]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

更新8.26最新版本后分隔符会自动消失

### 如何复现

输入整理好的提示词
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/129591199/02968d32-c990-487c-bb28-3b776f182193)

插件读取到提示词后
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/129591199/8a73f798-f1ba-4ea0-889c-1ee0cd2677cb)

### 操作系统

Windows

### 浏览器

Edge

**Comment by Physton** [comment]
已修复。
