### ISSUE TITLE
[Bug] Syntax conflict with the stable-diffusion-webui-composable-lora

### ISSUE THREAD

**Issue by obs945** [Physton/sd-webui-prompt-all-in-one#193]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

與 Composable LoRA/LyCORIS with steps (https://github.com/a2569875/stable-diffusion-webui-composable-lora) 語法衝突

### 如何复现

Composable LoRA/LyCORIS with step 的其中一種 step 控制語法 [<lora:A:1>::10]
sd-webui-prompt-all-in-one 處理過後會自動解譯成 [,<lora:A:1>,::10]
每次更改 Prompt 就會自動再多加一次逗點 [,,<lora:A:1>,,::10] --> [,,,<lora:A:1>,,,::10] --> [,,,,<lora:A:1>,,,,::10] --> 

### 操作系统

macOS

### 浏览器

Edge

### Python 版本

3.10.12

### Gradio 版本

3.39.0

**Comment by Physton** [comment]
已修复。
![Snipaste_2023-08-27_01-10-26](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/79aa5eff-598a-4bde-bf42-a12272a874e5)

**Comment by obs945** [comment]
目前觀察除了先前的 Composable LoRA/LyCORIS with steps 衝突之外也跟 sd-prompt-comment-out 有衝突
sd-prompt-comment-out ( https://github.com/misimoai/sd-prompt-comment-out )
sd-prompt-comment-out 的語法 /= 註解的內容 =/
希望也有辦法處理這個問題, 謝謝

**Comment by Physton** [comment]
> 目前觀察除了先前的 Composable LoRA/LyCORIS with steps 衝突之外也跟 sd-prompt-comment-out 有衝突 sd-prompt-comment-out ( https://github.com/misimoai/sd-prompt-comment-out ) sd-prompt-comment-out 的語法 /= 註解的內容 =/ 希望也有辦法處理這個問題, 謝謝

这个没有办法。
