### ISSUE TITLE
[Feature] 允許取消 加入至黑名單時的確認提示

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#195]
### 你想要什么功能或者有什么建议？

允許取消 加入至黑名單時的確認提示

**Comment by Physton** [comment]
很多人都不知道这个功能，也不用，如果突然误点了，提示词消失不见了，并且无法再添加，会造成困扰。

**Comment by bluelovers** [comment]
所以是 `允許取消` 而不是 `取消` 

也就是額外做一個設定開關

**Comment by Physton** [comment]
![Snipaste_2023-08-29_15-26-58](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/c039baba-40f4-43f5-8236-ce6c5a45bd41)
已完成
