### ISSUE TITLE
[Bug] 收藏夹使用中文命名时，会自动取消，无法使用

### ISSUE THREAD

**Issue by wibur0620** [Physton/sd-webui-prompt-all-in-one#197]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

将我已经收藏的提示词进行命名的时候，发现使用中文命名。无法使用。会自动弹出命名窗口

### Screenshot or log

https://github.com/Physton/sd-webui-prompt-all-in-one/assets/131615326/e82e25ca-57d8-4a7c-b454-5a7b36fb1ea7

### OS

Windows

### Browser

Edge

### Stable Diffusion WebUI version

version: v1.5.2

### Extension version

9a42de63

### Python version

 python: 3.10.6  

### Gradio version

 gradio: 3.32.0

**Comment by wibur0620** [comment]
输入法使用的是win11自带的输入法

**Comment by Physton** [comment]
微软输入法的BUG，已修复。

**Comment by bluelovers** [comment]
> 微软输入法的BUG，已修复。

這種bug也找得出來真是神奇
