### ISSUE TITLE
[Feature] 顯示 extra networks 資訊

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#199]
### 你想要什么功能或者有什么建议？

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/a959148c-8333-4278-974e-b68a229f01d5)

顯示 extra networks 的小型資訊框
例如

- 名字 ( name, output name, filename 如果相同就不顯示 )
- 版本 
- 相對路徑 (參考 https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/12838/files)
- 觸發詞 (可以被點選插入提示詞)
- 說明(超過寬度就截斷)
- 點擊後可以跳到 civitai
- 預覽圖 (本地 + civitai info 內)

### 有没有可以参考的同类竞品？

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/a68c2e02-0cae-4569-9768-6cd23cd53107)

**Comment by Physton** [comment]
已开发完成。
