### ISSUE TITLE
请问收藏的内容，保存在本地的那个文件呀

### ISSUE THREAD

**Issue by ifimcyx** [Physton/sd-webui-prompt-all-in-one#2]
请问收藏的内容，保存在本地的那个文件呀，我想做定期的备份，担心更换平台后会丢失

**Comment by Physton** [comment]
保存在sd-webui目录下的physton-prompt文件夹中

**Comment by Physton** [comment]
最新版本存储路径已经改为扩展目录下的storage文件夹，以后不会变动了 @ifimcyx
