### ISSUE TITLE
解析錯誤

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#20]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/7cd42805-f68a-403d-896d-5f8e9f23783a)

**Comment by Physton** [comment]
已修复

**Comment by lokpro** [comment]
解析還是有問題，而且會 freeze 很久才回應。

謝謝!


(deformed iris, deformed pupils, semi-realistic), aaa
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/2010297/0a3426e0-52f1-47fe-b409-91abe3610f9a)

**Comment by bluelovers** [comment]
https://github.com/KonghaYao/promptor

**Comment by Physton** [comment]
谢谢，我测试了，https://github.com/KonghaYao/promptor 这个库也有问题，所以暂时不会采用这个库。我会继续优化tags分词问题.
<img width="535" alt="Snipaste_2023-05-14_11-15-23" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/660a4f2c-d6a2-491b-be98-aec45fdf5e70">

**Comment by Physton** [comment]
测试发现，是因为碰到有“-”的时候会freeze

**Comment by Physton** [comment]
已提交新版本，以下词测试通过：
`[night light:magical forest:5, 15],[night light:magical forest:norvegian territory:5, 15, 25:catmull],(fire extinguisher:1, 2.0),[(fire extinguisher: 1.0, 2.0)::5],[lion:bird:girl: , 7, 10],EasyNegative (normal quality,Low quality,worst quality:1.4),EasyNegative [normal quality,Low quality,worst quality:1.4],<lora:clothesTransparent_v20:1:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0>,(aaa,bbb,ccc),(deformed iris, deformed pupils, semi-realistic),aaa,`
<img width="1091" alt="Snipaste_2023-05-14_11-29-34" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/488bf97d-5c3f-47c1-82fa-8a4ff0c06cda">

**Comment by lokpro** [comment]
謝謝, 我這邊試OK了。

(deformed iris, deformed pupils, semi-realistic)++
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/2010297/390b760f-b710-416b-8f6d-5f1c7e203027)

另外, 這個++ 我也不知道是甚麼語法, 按"調高"化成這樣, 我也不清楚對不對。 不過應該很少用到, 先這樣吧。
((deformed iris, deformed pupils, semi-realistic)++:1.4)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/2010297/0ac2f28d-2805-4f32-86b9-f9de9b250a39)

**Comment by yuno779** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/131428984/5686cb0a-d8fb-48bb-a78a-2e71b762c09a)
还是出现了错误，以及这个插件把原版自带的语法纠错功能给屏蔽了

**Comment by yuno779** [comment]
(((masterpiece))),(((crystals texture Hair))),(((((extremely detailed CG))))),((8k_wallpaper)), (1 girls:1.5),big top sleeves, floating,beautiful detailed eyes, overexposure, side blunt bangs, buttons, bare shoulders,light shafts, soft focus, character focus,wings,(((Transparent wings))),
[((Wings made of golden lines,angel wing,gold halo around girl,many golden ribbon,Aureate headgear,gold magic circle in sky,ight, black sky):1.3):((galaxy background, snowflakes, night sky, black pupils, starts sky background, stars behind girl, view on sky,standing):0.8)],[(Elegant hair,Long hair,The flying golden lines,Messy golden lines,halo,hairs between eyes,Small breasts,ribbons, bowties,red eyes, golden pupil, white hair,flowing hair,disheveled hair,lowing long hair):(Delicate arms and hands):0.8]
Negative prompt: Blond hair,(mutated hands and fingers:1.5 ),(mutation, poorly drawn :1.2), (long body :1.3), (mutation, poorly drawn :1.2) , liquid body, text font ui, long neck, uncoordinated body,fused ears,huge breasts,((((ugly)))),one hand with more than 5 fingers, one hand with less than 5 fingers
ENSD: 31337, Size: 1216x576, Seed: 435199350, Model: [M]LoliV1_Fix_FP16, Steps: 50, Sampler: Euler a, CFG scale: 7, Clip skip: 2, Model hash: 5801911d1a

**Comment by Physton** [comment]
完全重写了解析算法。以往老的没解析成功的我这测试已全部通过。
@yuno779 你提供的第二个会卡死的那个，也可以解析正常了。

**Comment by yuno779** [comment]
谢谢，我已经在使用了
