### ISSUE TITLE
[Feature] csv 翻譯支援 簡單包覆型的提示詞

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#200]
### 你想要什么功能或者有什么建议？

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/c072f497-ebfe-4625-ab2e-ffd869a11726)

如果只是單純被包起來 並且 `,` 分離時 則支援翻譯 與 黑名單
其他比較複雜的語法結構就不理他

**Comment by Physton** [comment]
4d4ae994c5914911fcf4e1ec5e151344e823baa3 已完成
