### ISSUE TITLE
无法成功预览历史记录[Bug] 

### ISSUE THREAD

**Issue by dale003** [Physton/sd-webui-prompt-all-in-one#201]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

历史记录有遮挡
![Snipaste_2023-08-30_11-33-26](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/37768614/cfacd33f-4395-4f0c-b173-097db9f180eb)

### 操作系统

Windows

### 浏览器

Chrome

### 扩展版本

36cbd935

**Comment by Physton** [comment]
已修复。
