### ISSUE TITLE
[Bug] 在最新webui1.6.0中all in one失效，请求适配

### ISSUE THREAD

**Issue by ligerye** [Physton/sd-webui-prompt-all-in-one#202]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

在新版webui1.6.0下，虽然扩展列表仍能找到all in one插件，但是无法正常显示在原生的正负输入框下，附带的一系列功能也无法使用了。
希望作者大大尽快适配一下，感谢感谢。

### 截图或日志

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/abcd8d0b-7580-49c7-b7b7-dbce7d9f18fc)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/304a6b6d-68de-474b-8cfc-6c9ebc742862)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/329d517c-c986-4eb6-afa9-839ca175fd5d)

### 操作系统

Windows

### 浏览器

Edge

**Comment by Physton** [comment]
![网页捕获_31-8-2023_205439_localhost](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/ed87be5e-6e2f-4aa4-8b55-9e00a02e7f26)
1.6.0版本测试可以正常使用。

**Comment by ligerye** [comment]
> ![网页捕获_31-8-2023_205439_localhost](https://user-images.githubusercontent.com/12066768/264650541-ed87be5e-6e2f-4aa4-8b55-9e00a02e7f26.jpeg) 1.6.0版本测试可以正常使用。

那看来可能是其他问题？在我个人这里的话是无法正常工作显示的。。
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/f90a67cd-b5a2-44d6-87f4-5398a6119815)

**Comment by Physton** [comment]
回退老版本正常吗？
控制台日志发来看看。

**Comment by ligerye** [comment]
> 回退老版本正常吗？ 控制台日志发来看看。

谢谢大大，我发现切换至8.27的旧版本后可以正常使用，且惊喜的是再次切换回最新版后也能够正常加载出来了；之前的情况是控制台中会显示加载，但实际并不会工作
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/ee288972-f2ce-44a9-b4ca-6a4aeaa77a85)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/8b744c21-26c9-4063-bc56-c591857e03f0)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/7e870418-624c-47cf-b653-da6031619fc8)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/56c986fe-d4d2-44ad-b16b-3eeba7bb91c5)
