### ISSUE TITLE
Dynamic LoRa incompatibility[Bug] 

### ISSUE THREAD

**Issue by kyle215ps3** [Physton/sd-webui-prompt-all-in-one#206]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

Conflict with Dynamic LoRa suddenly, I had the previous version as well and had no issue but now both are automatically changing the weight.
When setting to lora:0@0,1@0.25
The first 0 on the left gets automatically changed back to 1.

### Steps to Reproduce

change lora:1 to lora:0@0,1@0.25 it will atumatically change to 1 but doesnt do it if i do 0.1 or 0.01,
Any way to have a setting to turn off automatic weight changing?
this is the extension i use https://github.com/cheald/sd-webui-loractl

### OS

Windows

### Browser

Chrome

### Stable Diffusion WebUI version

1.6

### Extension version

6cace8cf

### Python version

3.10.6

### Gradio version

3.41.0

**Comment by Physton** [comment]
Fixed.

**Comment by kyle215ps3** [comment]
> Fixed.

Thank you!! :D

**Comment by Physton** [comment]
> > Fixed.
> 
> Same problem on the latest version of webui and latest version of prompt-AiO.
> 
> Removed config.json, ui-config.json and enabled only loractl + prompt-AiO. The problem remains

I haven't tested this issue. Please provide a detailed reproduction process.

**Comment by bananasss00** [comment]
> > > Fixed.
> > 
> > 
> > Same problem on the latest version of webui and latest version of prompt-AiO.
> > Removed config.json, ui-config.json and enabled only loractl + prompt-AiO. The problem remains
> 
> I haven't tested this issue. Please provide a detailed reproduction process.

The whole process is described in the first post. After this fix https://github.com/Physton/sd-webui-prompt-all-in-one/commit/88345b644cf2bd3a6a688793f69544db90be5c89 the problem did not disappear

**Comment by Physton** [comment]
> > > > Fixed.
> > > 
> > > 
> > > Same problem on the latest version of webui and latest version of prompt-AiO.
> > > Removed config.json, ui-config.json and enabled only loractl + prompt-AiO. The problem remains
> > 
> > 
> > I haven't tested this issue. Please provide a detailed reproduction process.
> 
> The whole process is described in the first post. After this fix [88345b6](https://github.com/Physton/sd-webui-prompt-all-in-one/commit/88345b644cf2bd3a6a688793f69544db90be5c89) the problem did not disappear
> 
> when I set the weight <lora:name:0@0, 0.5@0.25> and click somewhere outside the prompt field, the first 0 changes to 1 => <lora:name:1@0, 0.5@0.25>
> 
> but if you specify a non integer <lora:name:0.0001@0, 0.5@0.25>, everything is fine.

Try updating to version 841045d82907cfab389b3cb96bd6ecb84e6a2680 and see how it goes.

**Comment by bananasss00** [comment]
> Try updating to version https://github.com/Physton/sd-webui-prompt-all-in-one/commit/841045d82907cfab389b3cb96bd6ecb84e6a2680 and see how it goes.

Works great now, thank you very much
