### ISSUE TITLE
⭐️Bug反馈须知 / Bug Reporting Guidelines

### ISSUE THREAD

**Issue by Physton** [Physton/sd-webui-prompt-all-in-one#209]
1. 反馈问题前，请先在以下地方查阅是否有解决方式：
- [文档](https://aiodoc.physton.com/zh-CN/)
- [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html)
- [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues)

2. 请使用我提供的模板反馈问题，否则我可能不会去处理你的问题。
![1](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/e1cb2c3c-1286-4a38-940b-5e511f23c094)
![2](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/d1273645-7e98-43e0-b645-bd862fa3b69e)

3. 涉及到插件不能启动等相关问题，尽量提供控制台的截图或日志。

----

1. Before providing feedback, please check the following sources to see if there is a solution available:
- [Documentation](https://aiodoc.physton.com/)
- [FAQ](https://aiodoc.physton.com/FAQ.html)
- [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues)

2. Please use the provided template to provide feedback, otherwise I may not be able to address your issue.
![1](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/e1cb2c3c-1286-4a38-940b-5e511f23c094)
![2](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/d1273645-7e98-43e0-b645-bd862fa3b69e)

3. For issues related to plugin startup or other related problems, please provide screenshots or logs from the console if possible.

**Comment by hotmangaga** [comment]
大神 我这个不知道为什么启动这个插件就会提示木马,关闭这个prompt-all-in-one扩展就不会提示 不知道别人是否和我一样，我删掉了extensions里面的从新下也是一样

**Comment by hotmangaga** [comment]
非常感谢大神,我向可能是百度指向暂时性有问题，我把地址换到有道翻译启动就不会提示了。
