### ISSUE TITLE
从C站复制关键词进行解算，点击插件submit后无法正常解算正向词的TAG，反向关键词正常解析。

### ISSUE THREAD

**Issue by hzjdzzh955** [Physton/sd-webui-prompt-all-in-one#21]
从C站复制关键词进行解算，点击插件submit后无法正常解算正向词的TAG，反向关键词正常解析。另外是否可以增加直接从系统剪切板解析关键词的按钮。 黏贴到插件的submit界面再进行解析的操作有点多余。

**Comment by Physton** [comment]
如果不这么做，会导致原本的输入框无法解析C站复制的 #4

**Comment by Physton** [comment]
是有些小问题，在修复了

**Comment by hzjdzzh955** [comment]
> 如果不这么做，会导致原本的输入框无法解析C站复制的 #4

明白了 谢谢

**Comment by Physton** [comment]
已修复
