### ISSUE TITLE
正向提示词文本框不可见[Bug] 

### ISSUE THREAD

**Issue by dhs964057117** [Physton/sd-webui-prompt-all-in-one#210]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

更新到webui1.6。插件更新到最新。无法正常显示正向提示词文本框。禁用插件后，可以正常显示。

启用前
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/34617909/78706d9d-2d0f-438c-b366-d262209e19c8)
启用后
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/34617909/8378f329-8688-4640-b770-a0b4d3738d09)

### 截图或日志

启用前
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/34617909/5733e52e-63e7-4556-a2f8-49a00010acba)
启用后
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/34617909/a0a8c60c-f0e3-4d95-8cbe-a5d6fc6997bf)

### 操作系统

Windows

### 浏览器

Chrome

### Stable Diffusion WebUI 版本

1.6

### 扩展版本

88345b64

### Python 版本

3.10.6

### Gradio 版本

3.41.2

**Comment by Physton** [comment]
1.6默认主题下应该没问题，我这边使用lobe主题，界面完全就没法办正常显示。

**Comment by dhs964057117** [comment]
> 1.6默认主题下应该没问题，我这边使用lobe主题，界面完全就没法办正常显示。

默认主题也不行。禁用掉本插件之后。默认主题。lobe主题都可正常显示。一旦开启。默认和lobe都无法显示。之前的版本貌似是正常的。当我更新到插件新版本后出现的。

**Comment by Physton** [comment]
回退插件版本试下，看哪个版本正常。

**Comment by bluelovers** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/7430f693-df25-4276-882a-a8811a5651aa)

**Comment by dzzhuipang** [comment]
我遇到了同样的问题，这个插件貌似无法下载之版本，卸载后一切正常
