### ISSUE TITLE
我觉得大概率是我自己的问题，但是我确实好像不太能解决

### ISSUE THREAD

**Issue by MysteryManTK** [Physton/sd-webui-prompt-all-in-one#22]
![uTools_1683998152580](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/132129804/854f563e-4cc1-4f93-bb41-a3be6c67c683)
![uTools_1683998184484](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/132129804/04330669-b01e-48f0-9792-7db6e2fd0d74)

我在计算机这方面比较外行，麻烦作者看到了，帮我支支招，谢谢，

**Comment by Physton** [comment]
你这是升级还是安装？

**Comment by Physton** [comment]
你应该是软件下载的压缩包有问题，参考 https://github.com/Physton/sd-webui-prompt-all-in-one#installation-and-usage--%E5%AE%89%E8%A3%85%E4%BD%BF%E7%94%A8

**Comment by MysteryManTK** [comment]
我通过更换下载器解决了压缩包的问题，通过本地安装了插件，不过其实我更希望是能通过扩展从网址安装，因为这样后续我就可以直接在启动器里更新了，不过我不清楚为什么它失败了就想图2显示的那样，然后你推荐的安装方式，其实主要是因为我看不太懂，虽然举例了，但是“使用 git 克隆 sd-webui-prompt-all-in-one 到 stable-diffusion-webui 的 extensions 目录下”，这个《克隆》的具体操作应该是什么样的，不太明白，可能需要那种类似一步一步跟着操作的视频会比较让我这个外行好理解一些，

**Comment by Physton** [comment]
只要webui能够检测到插件的版本，那就能一键更新

**Comment by Physton** [comment]
你可以去插件列表里看看有没有检测到。

在插件列表里也可以通过官方库安装本扩展

**Comment by MysteryManTK** [comment]
官方列表里确实有，不过很奇怪的是它也下不下来，我以为是网络或者其他原因，然后我试着随便装了几个其他插件是可以的，就很奇怪，不知道问题再哪里

**Comment by MysteryManTK** [comment]
我过几天再试试吧，反正插件的安装的问题我几乎经常碰到，虽然最后好像都能安装，不过过程比较曲折，可能是什么偶然性的问题，感谢作者的回答，问一下作者是否真的要放弃b站，看了一下置顶大致了解了一些原因，但就我个人而言，b站整体会比较本土化一些，相对的github这个还是有点过于专业化，对于我槛比较高，我更喜欢视频的方式，我认为会比图文更加的直观明了，对于我的理解有非常大的帮助，作为心存感激的那些人来说，可能都希望作者还是能够留下包括我在内，人与人之间的差异确实很难想象，互联网环境也亦是如此，除了恶意的一些人，同样也有支持的一批人，不过最后还是尊重作者你本人的意愿

**Comment by Physton** [comment]
我已经将这些gif图片移到别的仓库去了，它们只是一些演示图片。不需要被用户下载到本地。你可以再试一下。
