### ISSUE TITLE
请增加免翻译tag功能

### ISSUE THREAD

**Issue by DELSAO6** [Physton/sd-webui-prompt-all-in-one#220]
### 这个功能与现有的问题有关吗？

我使用用于抽卡的通配符是中文,导致被翻译成英语从而通配符失效

### 你想要什么功能或者有什么建议？

请增加免翻译tag功能,

**Comment by Physton** [comment]
你可以关闭自动翻译，需要的时候手动翻译。

**Comment by Physton** [comment]
![Snipaste_2023-09-08_10-17-53](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/bccdabdc-7e20-4153-9259-b3674f1b0094)
已加到关键词黑名单设置界面中。
