### ISSUE TITLE
[Feature] Option for enabling the negative value for weight

### ISSUE THREAD

**Issue by hako-mikan** [Physton/sd-webui-prompt-all-in-one#221]
### Is this feature related to existing issues?

Hello. Thank you for the wonderful extension.
I have a request regarding the recent updates.
Recently, I encountered an issue where entering a negative value for weight was automatically corrected.
Generally, negative values don't make sense, but in the extension I've created, negative values work effectively.

### What feature do you want or what suggestions do you have?

I would like you to provide an option to disable the correction when a negative value is entered for Weight.

### Are there any similar competitors that can be referenced?

https://github.com/hako-mikan/sd-webui-negpip

**Comment by Physton** [comment]
Negative weight numbers are supported by default.

**Comment by hako-mikan** [comment]
Appreciate it!
