### ISSUE TITLE
[Bug] 不應該將 slugify 的內容當作翻譯內容

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#226]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/3d36bd93-2fb1-4cce-ac23-9a7581a24118)

此處應顯示為 `星系` 而不是 `星係`

### 操作系统

Windows

### 浏览器

Chrome

**Comment by Physton** [comment]
这不是跟你你写的代码来的吗。这个具体有什么用我都不清楚。

**Comment by bluelovers** [comment]
> 这不是根据你写的代码来的吗。这个具体有什么用我都不清楚。

哈哈 簡單來說就是 就是不論輸入的漢字是什麼語系或異體字的漢字 都將它轉換為一個只能用來識別用的漢字

例如 假設有一個字 是有很多異體字(包含 中文 或 日文漢字) 那麼他們都會被轉換為同一個字來識別
只是這轉換後的字 並不是用來閱讀用的 只是單純給程式用來識別的

**Comment by Physton** [comment]
> > 这不是根据你写的代码来的吗。这个具体有什么用我都不清楚。
> 
> 
> 
> 哈哈 簡單來說就是 就是不論輸入的漢字是什麼語系或異體字的漢字 都將它轉換為一個只能用來識別用的漢字
> 
> 
> 
> 例如 假設有一個字 是有很多異體字(包含 中文 或 日文漢字) 那麼他們都會被轉換為同一個字來識別
> 
> 只是這轉換後的字 並不是用來閱讀用的 只是單純給程式用來識別的
> 
> 

明白了

**Comment by bluelovers** [comment]
就像 `噁恶悪惡` 這些全都會在轉換後變成同一個字
