### ISSUE TITLE
[Bug] When installed with Supermerger, it doesn't respond to input unless I refresh the webui.

### ISSUE THREAD

**Issue by toyxyz** [Physton/sd-webui-prompt-all-in-one#229]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

When installed with Supermerger, it doesn't respond to input unless I refresh the webui. https://github.com/hako-mikan/sd-webui-supermerger
The UI looks fine, but it doesn't respond to input and the extension list is stuck with the Loading message as shown below. My guess is that there is a conflict with sd-webui-prompt-all-in-one. Disabling either of them should fix the problem. There are no error messages.

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/8006000/c1d18ea4-aafa-49e6-8943-df87343a13e1)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/8006000/59aa19b1-b9f2-4b37-b076-0d988ca66c1d)

### Steps to Reproduce

Install sd-webui-prompt-all-in-one like supermerger and run webui.

### Screenshot or log

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/8006000/bc555a3d-74f0-41c5-a054-b558912cdc6f)

### OS

Windows

### Browser

Chrome

### Stable Diffusion WebUI version

v1.6.0

### Extension version

07f9f8f9

### Python version

 3.10.6

### Gradio version

3.41.2

**Comment by Physton** [comment]
I have installed Supermerger and haven't encountered any issues. Could it be that my testing process is incorrect? Or perhaps I didn't understand the specific error you were referring to?
