### ISSUE TITLE
[Bug] 启动webui，在后端显示语法错误

### ISSUE THREAD

**Issue by wibur0620** [Physton/sd-webui-prompt-all-in-one#230]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

Running on local URL:  http://127.0.0.1:7860
Creating model from config: D:\AI\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml

To create a public link, set `share=True` in `launch()`.
Startup time: 28.5s (prepare environment: 12.1s, import torch: 3.8s, import gradio: 1.1s, setup paths: 0.7s, initialize shared: 0.2s, other imports: 0.7s, setup codeformer: 0.1s, load scripts: 6.5s, create ui: 1.2s, gradio launch: 0.6s, app_started_callback: 1.3s).
Applying attention optimization: xformers... done.
Model loaded in 14.1s (load weights from disk: 1.6s, create model: 1.6s, apply weights to model: 6.4s, apply half(): 0.2s, calculate empty prompt: 4.0s).
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误

### 操作系统

Windows

### 浏览器

Edge

### Stable Diffusion WebUI 版本

1.6.1

### 扩展版本

07f9f8f9

### Python 版本

3.10.6

### Gradio 版本

3.41.2

**Comment by wibur0620** [comment]
就是启动后就出现错误信息了，没有任何操作。当我打开ui后，插件能正常使用。

**Comment by wibur0620** [comment]
刚更新就出现这个问题，

**Comment by Physton** [comment]
不影响使用，等待后续修复。

**Comment by wibur0620** [comment]
好的，我以为是我的环境出现问题了

**Comment by wibur0620** [comment]
venv "D:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.014926500000001397
Launching Web UI with arguments: --xformers --no-half-vae --medvram-sdxl
[-] ADetailer initialized. version: 23.9.1, num models: 14
2023-09-09 18:45:09,915 - ControlNet - INFO - ControlNet v1.1.408
ControlNet preprocessor location: D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-09 18:45:10,035 - ControlNet - INFO - ControlNet v1.1.408
sd-webui-prompt-all-in-one background API service started successfully.
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
dirname:  D:\AI\stable-diffusion-webui\localizations
localizations:  {'zh-Hans (Stable) [vladmandic]': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable) [vladmandic].json', 'zh-Hans (Stable)': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable).json', 'zh-Hans (Testing) [vladmandic]': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing) [vladmandic].json', 'zh-Hans (Testing)': 'D:\\AI\\stable-diffusion-webui\\extensions\\界面汉化stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing).json'}
Loading weights [31e35c80fc] from D:\AI\stable-diffusion-webui\models\Stable-diffusion\sd_xl_base_1.0.safetensors
D:\AI\stable-diffusion-webui\modules\gradio_extensons.py:25: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  res = original_IOComponent_init(self, *args, **kwargs)
Running on local URL:  http://127.0.0.1:7860
Creating model from config: D:\AI\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml

To create a public link, set `share=True` in `launch()`.
Startup time: 25.3s (prepare environment: 5.6s, import torch: 5.9s, import gradio: 1.1s, setup paths: 1.1s, initialize shared: 0.2s, other imports: 0.9s, setup codeformer: 0.1s, load scripts: 7.2s, create ui: 1.2s, gradio launch: 0.8s, app_started_callback: 1.2s).
Applying attention optimization: xformers... done.
Model loaded in 14.9s (load weights from disk: 1.7s, create model: 1.5s, apply weights to model: 6.7s, apply half(): 0.2s, calculate empty prompt: 4.4s).
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误

**Comment by EfeelinG110** [comment]
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
Using customized region CN server backend.

自动中文翻译英文失效

**Comment by qinggeouye** [comment]
输入后自动翻译时页面报错提示：Cannot read properties of undefined (reading '')

**Comment by 5fVU25Jf** [comment]
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 語法錯誤
多次重新安裝 WEBUI 1.5 WEBUI 1.6都有此問題

**Comment by Physton** [comment]
@EfeelinG110 @qinggeouye 谁方便加下我QQ 94126162，我远程看下。

**Comment by NirvaanaaLiushuo** [comment]
控制台：[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
WebUI：Cannot read properties of undefined (reading '')

**Comment by qinggeouye** [comment]
这个插件切换回退到 09月01日 最后一个版本正常翻译了

**Comment by Alishan3230** [comment]
没有安装360 也是出现了同样的问题
sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
Cannot read properties of undefined (reading '')
的提示 ，另外您提供的QQ禁止加好友。o(╯□╰)o

**Comment by Physton** [comment]
> 没有安装360 也是出现了同样的问题
> 
> sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
> 
> Cannot read properties of undefined (reading '')
> 
> 的提示 ，另外您提供的QQ禁止加好友。o(╯□╰)o  

已解除限制。

**Comment by Physton** [comment]
@wibur0620 @EfeelinG110 @qinggeouye @5fVU25Jf @NirvaanaaLiushuo @Alishan3230 
更新到目前最新版本再看看。
