### ISSUE TITLE
[Feature] extra networks 資訊 觸發詞分組

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#231]
### 你想要什么功能或者有什么建议？

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/fc705429-e1c2-46a5-a5c3-089a3765527d)

應該要跟資訊頁面上一樣分成好幾個來選擇 => 

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/ea6de096-dd57-4f77-849e-ee3271f9cef9)

**Comment by bluelovers** [comment]
然後允許點擊之後 就直接加入 而不是只有複製到剪貼簿 或者 只能按最底下的按鈕

**Comment by Physton** [comment]
已修改完成。
