### ISSUE TITLE
Cannot read properties of undefined (reading "[Bug] 

### ISSUE THREAD

**Issue by lost9999** [Physton/sd-webui-prompt-all-in-one#233]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

更新之后插件用不了了，输入关键词回车提示：Cannot read properties of
undefined (reading "。启动时后台显示：[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误

### OS

Windows

### Browser

Edge

**Comment by Physton** [comment]
#225 
#230

https://github.com/Physton/sd-webui-prompt-all-in-one/issues/230#issuecomment-1712674043

**Comment by Physton** [comment]
更新到目前最新版本再看看。

**Comment by lost9999** [comment]
> 更新到目前最新版本再看看。

辛苦了！更新之后问题解决了
