### ISSUE TITLE
[Bug] incorrect translation in the opposite direction

### ISSUE THREAD

**Issue by mooonwalker1983** [Physton/sd-webui-prompt-all-in-one#235]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

The translation into english has stopped working, now when I write promt in russian, I receive a translation into russian. If I write promt in English, I receive a translation into Russian. 
how to make russian words translated into english?

### Screenshot or log

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/140676641/bfcfd5af-b79f-42a7-b0a4-f05adbd6ff8d)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/140676641/424b5ff0-066b-4ac7-813f-d97171ad0d66)

### OS

Windows

### Browser

Chrome

### Stable Diffusion WebUI version

1.6.0

### Python version

3.10.6

### Gradio version

3.41.2

**Comment by mooonwalker1983** [comment]
Thank you very much, now it works correctly!

**Comment by Physton** [comment]
I'm not sure exactly where the error occurred. I removed the functionality proposed by developer @bluelovers based on slugify (#214 #226). Please update to the latest version and give it another try.

**Comment by bluelovers** [comment]
看起來還是弄一個開關比較穩xd

**Comment by mooonwalker1983** [comment]
problem fixed, translation works
