### ISSUE TITLE
当all in one插件与lobe theme插件一起使用时，生成图片的预览界面会被自行置放到页面最下方

### ISSUE THREAD

**Issue by ZL1417896412** [Physton/sd-webui-prompt-all-in-one#236]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

当all in one插件与lobe theme插件一起使用时，生成图片的预览界面会被自行置放到页面最下方
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/85060918/b70f4427-2c15-46ec-ba4a-6219e47660c6)

### OS

Windows

### Browser

Edge

### Stable Diffusion WebUI version

1.6

### Extension version

newest

**Comment by Physton** [comment]
all in one 和 lobe theme 是否都已更新了到了最新版本？

**Comment by ZL1417896412** [comment]
均已更新至最新版本，刚试过，仍会出现该bug
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/85060918/ceca97fc-ab90-4607-ad65-92ca4116890b)

**Comment by Physton** [comment]
![Snipaste_2023-09-11_11-14-27](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/ed69c552-dd34-4ad2-a73d-0d5273614d5c)
关闭主题

**Comment by ZL1417896412** [comment]
好的好的，成功解决问题，感谢大大的回复
