### ISSUE TITLE
启动后,运行360提示病毒

### ISSUE THREAD

**Issue by qq425729** [Physton/sd-webui-prompt-all-in-one#237]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/8380579/8a456ba3-905a-4a1a-bd93-23d4ec2ea447)

### 如何复现

最新版本插件启动sd后,360就提示

### 截图或日志

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/8380579/85d9feab-6167-46c9-a76c-0d3da2c303e2)

 拦截后提示

### 操作系统

Windows

### 浏览器

Edge

### Stable Diffusion WebUI 版本

1.6

### 扩展版本

f965fa8

### Python 版本

 3.10.11

### Gradio 版本

3.41.2

**Comment by Physton** [comment]
已删除其他开发者提出基于slugify做的功能，#214 #226。更新到最新版本再看看。
