### ISSUE TITLE
[Feature] 禁用/启用关键词功能，可以把被禁用关键词与启用关键词之间区分再明显一些就好了

### ISSUE THREAD

**Issue by twinoak1990** [Physton/sd-webui-prompt-all-in-one#239]
### 你想要什么功能或者有什么建议？

你好，禁用/启用关键词功能，现在被禁用的关键词是灰色，被启用关键词是白色，两者区别不明显；

如果考虑给禁用关键词加上删除线、或者叉，这样区分就明显了。致敬，祝好！

![未标题-1](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/138547894/1af16ea0-ebce-49e5-aba7-47e0448005a0)

**Comment by Physton** [comment]
已显示为中划线
