### ISSUE TITLE
百度API，TEST里翻译没问题，到主界面点翻译按钮会报 app_id is required，啥原因

### ISSUE THREAD

**Issue by seamyctl** [Physton/sd-webui-prompt-all-in-one#24]
2台电脑情况居然还不同，一台是报app_id is required，一台报请求过于频繁。 
ID和KEY一样

请求过于频繁这个在免费的阿里翻译则没这个现象

**Comment by Physton** [comment]
报app_id is required目前发现应该是浏览器/缓存问题？有人反应过，换一个浏览器就好了。请求过于频繁是因为百度并发最高只能1秒1个。阿里是1秒50

**Comment by seamyctl** [comment]
= = 那我还是用免费的好了…… 离谱百度

**Comment by Physton** [comment]
免费具体并发不知道，肯定也不会很高。

**Comment by Physton** [comment]
这个问题已经修复了，不是浏览器和缓存的问题。
