### ISSUE TITLE
[Bug] 配合sd-webui-lobe-theme使用加载不出模型

### ISSUE THREAD

**Issue by AiBanLanGen** [Physton/sd-webui-prompt-all-in-one#241]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

配合sd-webui-lobe-theme使用加载不出模型

### Steps to Reproduce

卸载插件后可以正常使用主题，重装后就出现加载模型失败一直在读取状态

### Screenshot or log

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/31445084/8a918314-8535-4cb3-87e6-dc724ac56c17)

### OS

Windows

### Browser

Chrome

### Stable Diffusion WebUI version

秋叶1.6

### Python version

3.10.11

**Comment by JaneYork** [comment]
为什么关闭了呢？支持lobe主题吗/?
