### ISSUE TITLE
[Bug] 启用扩散模型时会将分隔符全部清除，且分隔符存在时扩散模型卡片均为灰色

### ISSUE THREAD

**Issue by a857313401** [Physton/sd-webui-prompt-all-in-one#243]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

启用扩散模型时会将分隔符全部清除，且分隔符存在时扩散模型卡片均为灰色

### 如何复现

分隔符存在时扩散模型卡片为灰色但是可以启用
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/129591199/7d7d3287-f23e-414e-9807-5eebb37ad19b)
在我点击扩散模型时，分隔符全部消失，但是并未添加扩散模型，再次点击可正常启用
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/129591199/41c74534-8d2c-49ff-aaa6-6a353791858a)

### 操作系统

Windows

### 浏览器

Edge

**Comment by a857313401** [comment]
使用BREAK强行隔开时扩散模型不可用，全部处于灰色状态且无法添加，也不会清除任何tag

**Comment by Physton** [comment]
已修复
