### ISSUE TITLE
Disable automatic prompt formatting

### ISSUE THREAD

**Issue by mikheys** [Physton/sd-webui-prompt-all-in-one#244]
Good afternoon! Is there any way to disable the automatic formatting of the prompt? So that it doesn't delete spaces it thinks are unnecessary and doesn't put commas where I don't need them?

**Comment by Physton** [comment]
Currently, there is no way to disable it, but you can customize the prompt format:
https://aiodoc.physton.com/FormatOfPrompts.html

**Comment by thijsi123** [comment]
for anyone wondering, I disabled this by setting

$n=this.textarea.value.trim();if($n===this.prompt.trim())
to
$n=this.textarea.value();if($n===this.prompt())
