### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading '')

### ISSUE THREAD

**Issue by NewBieIsM** [Physton/sd-webui-prompt-all-in-one#245]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

我是用谷歌浏览器：当我输入关键词的时候，右上角会出现Cannot read properties of undefined (reading '')，并不能翻译成英文。

### Steps to Reproduce

[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
[sd-webui-prompt-all-in-one] slugify error: SyntaxError: 语法错误
Using customized region CN server backend.

### Screenshot or log

Cannot read properties of undefined (reading '')

### OS

Windows

### Browser

Chrome

### Stable Diffusion WebUI version

V1.6.0

### Python version

3.10.6

### Gradio version

3.41.2

**Comment by Physton** [comment]
更新。
