### ISSUE TITLE
[Feature] 加强“启用关键词”和“禁用关键词”两种状态的视觉反差

### ISSUE THREAD

**Issue by hben35096** [Physton/sd-webui-prompt-all-in-one#247]
### 你想要什么功能或者有什么建议？

加强“启用关键词”和“禁用关键词”两种状态的视觉反差
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/139383150/0d7e9240-f431-4885-8fd0-cc9849233deb)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/139383150/01b0de33-314e-4906-98a1-30845d25e21c)
这太难辨认了，很难分清“启用”和“禁用”状态。

**Comment by Physton** [comment]
最新的版本里，禁用的关键词是会显示删除线的。

**Comment by hben35096** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/139383150/e161ece8-af0f-426e-b691-ec44fd8b8413)
Okay, thanks, the effect is great now, thank you for your efforts
