### ISSUE TITLE
【功能请求】希望可以添加设置折叠内容 与 隐藏WebUI输入框的设置

### ISSUE THREAD

**Issue by HalfMAI** [Physton/sd-webui-prompt-all-in-one#25]
如果设置了ui-config.json 的一些默认设置时，打开页面时会有比较大的占比
如图所示：
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/5293796/697845c3-3e28-45cd-adba-7893df07040a)

希望可以添加设置某个输入框默认是打开还是关闭的设置。
1.显示/折叠内容【正向词与否定词分别设置】
2.开启WebUI输入框设置【同上】

希望的效果是打开页面后是这样子的效果：
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/5293796/1a6ae857-e592-4897-8363-8a1b1dbb2954)

**Comment by Physton** [comment]
webui输入框显示隐藏，在扩展输入框的前面的勾选框就是的，带记忆功能。
展开折叠扩展面板，最前面第一个小图标就是，只不过没有记忆功能。

**Comment by HalfMAI** [comment]
是的，主要是折叠的面板也希望记忆。因为设置了UI-config.json的话，反射提示词可能很多，更改的情况也比较少

**Comment by Physton** [comment]
已优化
