### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by gobshyte** [Physton/sd-webui-prompt-all-in-one#251]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

If I try to load the base 1.0 SDXL model with this extension enabled, I get the following error and the model fails to load :
 AttributeError: 'NoneType' object has no attribute 'is_sdxl'

### OS

Windows

### Browser

Firefox

**Comment by Physton** [comment]
Unable to reproduce the error you described.
