### ISSUE TITLE
[Bug] Keywords reset if the field touches the mouse cursor

### ISSUE THREAD

**Issue by Terroosh** [Physton/sd-webui-prompt-all-in-one#255]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

When editing a keyword, if the mouse interacts with the field, anything in the field is reset to what it was before you started editing.

### Steps to Reproduce

Click on a keyword to edit, place your mouse cursor in the field and keep typing.
The field will reset.

### Screenshot or log

![bug](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/55752005/7afcf70e-362c-436d-a18f-70a7fae136de)

### OS

Windows

### Browser

Firefox

### Stable Diffusion WebUI version

1.5.2

### Extension version

c07aab2

### Python version

3.10.6

### Gradio version

3.32.0

**Comment by Physton** [comment]
fixed.
