### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by vvip2u** [Physton/sd-webui-prompt-all-in-one#257]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/20998070/a7880ce7-33e3-49af-b621-8dc0e5f42dea)
看红框里面出现了error，加载不到ckpt文件，包括lora那个标签页也是一样

### 如何复现

> 我的./webui.sh启动时会加参数，设定sd外部的文件夹作为ckpt/lora文件夹等。这时就出现该问题。因为同时会用多个Stable diffusion且用ComfyUI，不想把不同的ckpt和lora文件拷来拷去，所以会放在一个公共目录下。麻烦支持该场景

我的环境是
MacOS M1 Max
version: [v1.6.0]
python: 3.10.10
torch: 2.0.1
xformers: N/A
gradio: 3.41.2
checkpoint: [038ba203d8]

### 操作系统

macOS

### 浏览器

Chrome

### Stable Diffusion WebUI 版本

v1.6.0

### 扩展版本

5ef669d

### Python 版本

3.10.10

### Gradio 版本

3.41.2

**Comment by Physton** [comment]
通过什么样的参数设置的？这个BUG应该跟本插件没有关系。
