### ISSUE TITLE
[Feature] 可自定义多个收藏列表

### ISSUE THREAD

**Issue by DELSAO6** [Physton/sd-webui-prompt-all-in-one#261]
### 这个功能与现有的问题有关吗？

我使用公开的tag时会收藏有用的tag，久而久之唯一的收藏列表里tag越来越繁多，用起来也不方便

### 你想要什么功能或者有什么建议？

能自由增加和删除收藏列表，改善tag使用方便性，（如果不方便，可以加多个固定名字并不会创建或删除的收藏列表）

**Comment by Physton** [comment]
可以使用自定义关键词组功能：https://aiodoc.physton.com/zh-CN/GroupTags.html
新建一个 prepend.yaml 用于维护自己喜爱的关键词，可以分组。
唯一不方便的是，无法通过网页增加删除，只能编译文件。

收藏夹分组过于复杂，目前不会考虑。
