### ISSUE TITLE
[Feature] 能否增加独立运行文件？

### ISSUE THREAD

**Issue by hben35096** [Physton/sd-webui-prompt-all-in-one#262]
### 你想要什么功能或者有什么建议？

这个插件十分好用，在国内基本上已经是AUTOMATIC1111必装插件，但ComfyUI中没有这样的插件，我想如果要开发成ComfyUI插件工作量应该非常大。
由于实在找不到更好的应用程序，我每次都只能启动sd webui来编辑他提示词。
假如能够像infinite-image-browsing那样，既可以是sd webui插件，也可以独立运行，就太好了。

**Comment by Physton** [comment]
已开发独立运行版本，仓库地址：https://github.com/Physton/sd-webui-prompt-all-in-one-app

**Comment by hben35096** [comment]
> 已开发独立运行版本，仓库地址：https://github.com/Physton/sd-webui-prompt-all-in-one-app

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/139383150/3f581074-11a5-4c6d-8661-b655aaf161a9)
非常感谢，它在云端服务器的linux系统中，使用cloudflared网址可以完美运行，假如直接使用：python app.py
会有显示不全的情况，不过这应该是阿里云实例的问题。

**Comment by hben35096** [comment]
https://drive.google.com/file/d/1itgxELmFYd5bcoQIR5n3s9gLXZHVCp-5/view?usp=sharing
我把prompt-all-in-one-app做成了独立便携版，内置独立python环境，解压即可使用。再次感谢你做了这么好用的插件~

**Comment by Physton** [comment]
已制作 Windows 一键启动包。

https://github.com/Physton/sd-webui-prompt-all-in-one-app/blob/main/README_CN.MD#windows-%E4%B8%80%E9%94%AE%E5%90%AF%E5%8A%A8

**Comment by hben35096** [comment]
太棒了，感谢~
