### ISSUE TITLE
[Feature] Stop adding Commas after Loras

### ISSUE THREAD

**Issue by kashyyyk1** [Physton/sd-webui-prompt-all-in-one#263]
### What feature do you want or what suggestions do you have?

When I add a lora with it's trigger word or words it adds a comma after the last ">"  Which wouldn't be a big deal except it causes issues with  X/Y/Z plot's Prompt S/R.  I want to test different loras with the same prompt and I can't, Manually I can, but I want to set and run it and let it go through the loras I want to test

**Comment by Physton** [comment]
You can set the format of prompts by following this link: https://aiodoc.physton.com/FormatOfPrompts.html
Please check the option 'Automatically remove the last comma in the prompt.'

In addition, two new options have been developed:

1. Whether to remove the comma in front of Lora.
2. Whether to remove the comma after Lora.

![CleanShot 2023-11-09 at 20 21 08@2x](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/c23d0595-4d9b-4173-ae64-24ec74a5110c)
