### ISSUE TITLE
[Bug] 在WebUI的输入框中编写，点击任意位置后不会被解析到扩展面板里

### ISSUE THREAD

**Issue by pimin12** [Physton/sd-webui-prompt-all-in-one#265]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

在WebUI的输入框中编写，点击任意位置后不会被解析到扩展面板里，以前是可以的
这样用导入关键词类的功能会很不方便

### 操作系统

Windows

### 浏览器

Edge

**Comment by Physton** [comment]
现在是在WebUI输入框中编写后，鼠标焦点离开输入框，会自动加载到扩展面板中，不需要再手动点击面板。
