### ISSUE TITLE
[疑问]是否支持lobe theme或者其他主题？ 

### ISSUE THREAD

**Issue by JaneYork** [Physton/sd-webui-prompt-all-in-one#266]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

[疑问]是否支持lobe theme或者其他主题？ 

### 操作系统

Windows

### 浏览器

Chrome

**Comment by Physton** [comment]
支持。
