### ISSUE TITLE
[Bug] 和civitai-shortcut插件冲突了,在最后一次期的更新后出现的问题.

### ISSUE THREAD

**Issue by tim9292654** [Physton/sd-webui-prompt-all-in-one#267]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

我在之前使用sd-webui-prompt-all-in-one和civitai-shortcut,兼容性都没问题,但更新了最新版的sd-webui-prompt-all-in-one,就出现不可以使用civitai-shortcut,用civitai-shortcut不能扫描模型和网址下载模型功能都失效了,只要禁用sd-webui-prompt-all-in-one就可以了,不清楚什么原因,没有报错选项,但是是更新到最新版sd-webui-prompt-all-in-one的时候出现的.
该项目地址:https://github.com/sunnyark/civitai-shortcut

### 如何复现

但更新了最新版的sd-webui-prompt-all-in-one,就出现不可以使用civitai-shortcut,用civitai-shortcut不能扫描模型和网址下载模型功能都失效了,

### 操作系统

Windows

### 浏览器

Edge

### Stable Diffusion WebUI 版本

1.6.1

### 扩展版本

627a741

### Python 版本

3.10.11

**Comment by Physton** [comment]
请给出具体的动图、视频、图片等演示和控制台日志。

**Comment by tim9292654** [comment]
就是没有报错,但点击Scan Models没反应,一般都会扫描出来本地有那些没信息的模型,然后下载信息,加载sd-webui-prompt-all-in-one插件后,就会这样,之前没有这样,是更新了最新的sd-webui-prompt-all-in-one,才这样加载不出来.
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/29449662/26a08d6e-f13a-477d-9926-389118ffc0d6)

**Comment by Physton** [comment]
![Snipaste_2023-11-11_13-39-53](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/b05c75a2-a261-45e4-83cf-25cd1cef0906)

**Comment by tim9292654** [comment]
好吧,可能是我电脑性能慢了,同时使用这两个插件,他加载太慢了,5分钟都没出来,我以为有冲突,关掉sd-webui-prompt-all-in-one,就能很快识别出来,我的问题,没有做太严谨的实验,麻烦作者了
