### ISSUE TITLE
[Bug] 加载不出来，偶尔重新刷新UI可以出来

### ISSUE THREAD

**Issue by jasoncow007** [Physton/sd-webui-prompt-all-in-one#268]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

webui加载完成，all in one加载不出来，
还会出现 data failed load to server字样

### 如何复现

秋叶启动器，最近更新后每次启动都无法正常加载，

### 操作系统

Windows

### 浏览器

Edge

### Stable Diffusion WebUI 版本

1.6.1

### 扩展版本

627a41

### Python 版本

3.10.11

### Gradio 版本

3.41.2

**Comment by Physton** [comment]
发下截图和控制台日志。

**Comment by jasoncow007** [comment]
![微信截图_20231112164918](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/125945058/6d48a483-7293-4ad0-91ae-4eabf7f2f502)
![微信截图_20231112164941](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/125945058/f7aca6eb-5a0a-4b7f-b012-2798e54bed43)
控制台看不出来什么异常，只是ui不显示

**Comment by Physton** [comment]
你插件装了很多，检查下是否跟哪个插件冲突了。

**Comment by jasoncow007** [comment]
不知道跟哪个冲突，关键最后会提示“连接错误”，是不是跟api有关？还会导致模型/lora显示那边加载不出来，通常要刷新多次都不一定行

**Comment by Physton** [comment]
把其它插件都禁用，逐个排查。
