### ISSUE TITLE
tag信息无法传送

### ISSUE THREAD

**Issue by Stanley-baby** [Physton/sd-webui-prompt-all-in-one#27]
在图片信息中，识别图片信息后，无法把图片信息传送到文生图、图生图等

**Comment by Physton** [comment]
我这一直是正常的，你具体描述下发什么了情况。

**Comment by Stanley-baby** [comment]
我使用的是mac哦！
就是图片信息（识别图片tag）—发送至文生图—文生图正负tag框显示报错
图生图也一样
然后我后来更新了最新版本的webui，正负tag框不报错了，但是依然不显示图片信息传送过来的正负tag（意思是没有报错，文生图正负tag框为空）

Physton ***@***.***> 于2023年5月16日周二 01:31写道：

**Comment by Physton** [comment]
我又重试了下发送到文生图、发送到图生图，提示词都能正常传递到系统的输入框中。
你需要提成更详细的截图。

**Comment by Stanley-baby** [comment]
### 为了更直观，我录了一个gif
![测试](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/58399659/f6f6d986-fe6d-49bb-9036-dac10caf2e71)

**Comment by Stanley-baby** [comment]
扩展版本很老？不太明白，是指让我更新一下您开发的这个翻译插件吗？

Physton ***@***.***> 于2023年5月16日周二 15:42写道：

**Comment by Physton** [comment]
是的，更新这个扩展到最新的版本
