### ISSUE TITLE
[Bug] 这个界面是怎么设置的

### ISSUE THREAD

**Issue by snoopytl** [Physton/sd-webui-prompt-all-in-one#271]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

在看插件介绍的过程中，发现了这个样式，我很喜欢，也想把自己的设置成这样，就是图中标红的区域，我找不到其他沟通的渠道，只能在这试试留言了

### 截图或日志

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/29892766/cc0b4c73-bfed-4af2-8bb3-2f6385601daa)

### 操作系统

Windows

### 浏览器

Chrome

**Comment by Physton** [comment]
https://github.com/lobehub/sd-webui-lobe-theme

**Comment by snoopytl** [comment]
感谢大佬
