### ISSUE TITLE
[Feature] 能否增加关键词扩展面板增减()切换成{}的主题功能

### ISSUE THREAD

**Issue by 780ilk8ui9otk** [Physton/sd-webui-prompt-all-in-one#272]
### 你想要什么功能或者有什么建议？

novelai还在用极老的语法希望能增加此功能方便webui作为novelai前台时的prompt整理

**Comment by Physton** [comment]
![CleanShot 2023-11-26 at 20 15 22@2x](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/d144db09-c146-482b-8261-566cb105345e)

已开发完成，在关键词格式配置窗口中开启。
