### ISSUE TITLE
[Bug]调用openai的api时报错

### ISSUE THREAD

**Issue by hutao01-miku** [Physton/sd-webui-prompt-all-in-one#276]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API. You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28` A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
我不是很懂代码，gpt翻译后貌似是openai官方对接口进行了更新，而项目中还未更新？我已经更新了本项目的最新版本但仍然报错

### 如何复现

使用的是秋叶最新包，插件也是最新，不管是官方的key还是国内中转的都只会报这个错误

### 截图或日志

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/118782661/54607011-f389-426c-91e2-b016cac54b77)

### 操作系统

Windows

### 浏览器

Chrome

**Comment by Physton** [comment]
已修复，更新后重试。
