### ISSUE TITLE
[Feature] 我想有一个功能,类似配置文件一键导入的效果

### ISSUE THREAD

**Issue by tim9292654** [Physton/sd-webui-prompt-all-in-one#279]
### 这个功能与现有的问题有关吗？

类似sd载入config.json和ui-config.json的效果

### 你想要什么功能或者有什么建议？

就是我想云服务器上跑,发现每次配置都要重新修改,
有没有办法把配置导入进去,或者告诉我把什么文件夹下的文件,对应的是什么..
我想把我收藏栏的标签导入到云端的程序中..发现不知道收藏栏收藏的标签对应的文件是那个,麻烦告诉我..我看说明文档和网站没看到指向..
我知道有group_tags/prepend.yaml功能可以导入你需要的标签,但收藏栏里面的标签可以有回车,group_tags/prepend.yaml这个里面不好加回车的标签组

**Comment by Physton** [comment]
所有的数据都存储在storage目录中，备份还原该目录即可。
