### ISSUE TITLE
[Feature] Disable/hide the Negative Prompt box

### ISSUE THREAD

**Issue by NeonXi** [Physton/sd-webui-prompt-all-in-one#280]
### 你想要什么功能或者有什么建议？

First of all, thank you for developing this plugin，it's very good.
I want to Disable/hide the Negative Prompt box. Although it can be folded. Because I rarely use this, But it takes up another large piece of space，So I had this idea. Thank you very much!!!

I don't know what your mother tongue is, let me describe it again in Chinese
首先非常感谢您开发了这个插件，很好用
我希望可以禁用或者说是完全隐藏反向提示词这一块，虽然他可以折叠，但是还是占据一部分空间，当我需要输入反向提示词时，我也几乎不用这里，所以我有了这个想法。非常感谢！！！

**Comment by Physton** [comment]
See: https://aiodoc.physton.com/OtherFeatures.html

**Comment by NeonXi** [comment]
Okay, I'll go take a look

**Comment by NeonXi** [comment]
What I want is to completely disable it，But now I feel that my request is not very necessary.
I give up on this idea.
Thank you very very much
