### ISSUE TITLE
[Bug] 安装插件和扩展依赖后，并启动后报错：连接到后台服务接口失败，并且webui 上无插件的标签。

### ISSUE THREAD

**Issue by slayeryahu** [Physton/sd-webui-prompt-all-in-one#281]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

安装插件和扩展依赖后，并启动后报错：连接到后台服务接口失败，
并且webui 上无插件的标签。

根据FAQ中的步骤建议重启无效，Storage目录为空，没有东西可删除。依赖的python包均已安装成功。

### Steps to Reproduce

1.更新sd web ui到最新的master版本
2.git clone 插件到 extensions目录
3.安装依赖
4.启动，报错。

### Screenshot or log

![webui](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/7860485/905c4aa2-beda-4858-91d8-039e484e9b4b)
![BUG1](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/7860485/4172f44c-a3b7-4958-b74b-ac7ad4e0d65d)

### OS

Windows

### Browser

Chrome

### Stable Diffusion WebUI version

git pull最新版本

### Extension version

git clone最新版本

### Python version

3.10

### Gradio version

3.31.0

**Comment by Physton** [comment]
你这边使用的是云服务器，我没用过，具体什么环境怎么部署的我都不清楚。没法回答你的问题。
可能需要做url反向代理之类的？

**Comment by slayeryahu** [comment]
> 你这边使用的是云服务器，我没用过，具体什么环境怎么部署的我都不清楚。没法回答你的问题。 可能需要做url反向代理之类的？

和本地设备没什么区别，可以正常联网，也可以翻墙挂梯子访问外网，插件都是正常安装的，只是安装后控制台提示很多404错误。

**Comment by 1537348750** [comment]
您好，请问您解决该问题了吗？
