### ISSUE TITLE
[Bug] 正向提示词显示问题

### ISSUE THREAD

**Issue by snoopytl** [Physton/sd-webui-prompt-all-in-one#282]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

同样的提示词，正向输入框和反向输入框显示的内容不一致，正向会自动添加中文，看着很别扭，如何让它不显示
正向和反向中的设置一致

### Screenshot or log

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/29892766/cd4d946a-37e9-412b-937c-b321ba546645)

### OS

Windows

### Browser

Chrome

**Comment by Physton** [comment]
请检查是否其他插件造成的此问题。
