### ISSUE TITLE
[Feature] Disable the automatic comma before line breaks

### ISSUE THREAD

**Issue by dexyel** [Physton/sd-webui-prompt-all-in-one#283]
### What feature do you want or what suggestions do you have?

I'd love to see an option in the format menu to disable the automatic comma before line breaks. I often prompt with Dynamic Prompts' variable system and with the comma being added automatically, the generation add the commas to the prompt.

**Comment by Physton** [comment]
Developed.
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/ae01f20c-708d-44b2-9b2e-ff2853c2422d)

**Comment by xiahongyu939** [comment]
能添加不要禁用换行符的自动逗号的代码吗
