### ISSUE TITLE
[Bug] 禁用换行符前的自动逗号

### ISSUE THREAD

**Issue by xiahongyu939** [Physton/sd-webui-prompt-all-in-one#284]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

在禁用换行符自动逗号后，在自己生成的图片没有达到我的预想效果，我希望提示词不要在禁用（或去除）换行符自动符号。

### 操作系统

Windows

### 浏览器

Chrome

### Stable Diffusion WebUI 版本

8b0beeb

**Comment by Physton** [comment]
???????

**Comment by xiahongyu939** [comment]
不要禁用自动符号了
