### ISSUE TITLE
[Bug] Doesn't display subfolders in Extra Network tab (Lora)

### ISSUE THREAD

**Issue by Subvel** [Physton/sd-webui-prompt-all-in-one#285]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

I'll describe the bug for "Lora", but most likely it is present for "Textual Inversion", "Hypernetworks" and "Checkpoints" too.

It usually should show subfolders (in the "/models/Lora/" folder) to the right of the button "Lora". But it stops showing all the subfolders ("Lora" button still exists and works correctly) if:
1) There are only subfolders with models (in /models/Lora) without any model files in the root. (main problem)
2) Even if a model in the root folder is present, but it is a duplicate of a model in one of the subfolder, it is not counted. (just noticed, it's a minor problem)
3) Even if a model in the root folder is present, but checkpoint has a different base model, it is not counted. Because it is just filtered. For example: lora model is SD1.5, but checkpoint is SDXL. (is likely to be solved along with the main problem)

### Steps to Reproduce

Create a similar file structure:

- /models/Lora/
    - a/
        - (some lora models)
    - b/
        - (some lora models)

Make sure there are no files in the root folder ("/models/Lora/").

### Screenshot or log

![Screenshot](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/131311006/7b0ee777-f4b7-4fc6-b976-c32143c17431)

### OS

Windows

### Browser

Chrome

### Stable Diffusion WebUI version

v1.6.0-2-g4afaaf8a

### Extension version

9465ea43

### Python version

3.10.6

### Gradio version

3.41.2

**Comment by Physton** [comment]
The issue has been fixed. However, indeed, the problem that incompatible models cannot be displayed when the checkpoint is SDXL is unsolvable.
