### ISSUE TITLE
[Bug] sd-webui-v1.7.0 插件位置显示问题

### ISSUE THREAD

**Issue by hben35096** [Physton/sd-webui-prompt-all-in-one#286]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

stable-diffusion-webui升级到v_1.7.0，all-in-one工具条变成了并排显示，不止我一台机子遇到这个问题。
已尝试过删除stable-diffusion-webui文件夹下的config.json文件来恢复初始设置，没有效果。

### 截图或日志

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/139383150/47c7ff7d-3ca7-47ce-8228-db2cf46529d3)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/139383150/998ed071-2256-4c07-981d-27275b5dcfd4)
一个是在linux系统下，一个是在Windows系统下的。

### 操作系统

Ubuntu

### 浏览器

Edge

**Comment by Physton** [comment]
已修复，再试试。

**Comment by hben35096** [comment]
> 已修复，再试试。

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/139383150/98cc6564-574f-4ece-b30a-64b012ca8f00)
完美解决了，谢谢~
