### ISSUE TITLE
和背景色融为一体了，请问怎么改

### ISSUE THREAD

**Issue by RebortQu** [Physton/sd-webui-prompt-all-in-one#288]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

和背景色融为一体了，请问怎么改![捕获](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/20516084/d6ea5ad6-7250-4da5-aa1a-d96f9a27bd75)

### 操作系统

Windows

### 浏览器

Chrome

**Comment by Physton** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/e9471171-ea4e-48a6-974a-3fa6e398aa4d)
切换一下主题看看。

**Comment by RebortQu** [comment]
好的 我看看

**Comment by RebortQu** [comment]
好了一点还是不清楚，改的是整个ui界面吧。但并没改太多，可能是我ui的问题。这次下次启动把整个界面主题改了

**Comment by RebortQu** [comment]
讲解了谢谢，你是机器人回复吧
