### ISSUE TITLE
意见征询，输入框是放到左边还有右边

### ISSUE THREAD

**Issue by Physton** [Physton/sd-webui-prompt-all-in-one#29]
1. 右边
![Snipaste_2023-05-16_11-24-16](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/dbb32fcf-c6fa-4290-9ea0-1e5aedce8afd)
2. 左边
![Snipaste_2023-05-16_11-23-40](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/67f1133e-bf8c-4a5b-9dc1-18539ebe8349)
3. 其它？？？

**Comment by sdbds** [comment]
能不能像cozy-nest那样的设计，侧边栏加个按钮，点一下从侧栏滑出。
https://github.com/Nevysha/Cozy-Nest

**Comment by lokpro** [comment]
https://raw.githubusercontent.com/Physton/sd-webui-prompt-all-in-one-assets/main/images/elegant_input.gif

圖例不是能直接輸入在下面框裏嗎? 現在能用嗎?

**Comment by Physton** [comment]
> https://raw.githubusercontent.com/Physton/sd-webui-prompt-all-in-one-assets/main/images/elegant_input.gif
> 
> 圖例不是能直接輸入在下面框裏嗎? 現在能用嗎?

放到下面，在面板折叠起来的时候，就没法输入了
