### ISSUE TITLE
[Feature] Chinese Mainland region Can't use this extension , can there be a built-in proxy?

### ISSUE THREAD

**Issue by 2575044704** [Physton/sd-webui-prompt-all-in-one#291]
### 这个功能与现有的问题有关吗？

yes
![QQ截图20240108201021](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/19410065/b143591c-5d93-4c5d-b90a-35a8262e9c81)

### 你想要什么功能或者有什么建议？

Hello Author, The China Mainland can't use this extension due to THE GREAT FIREWALL, can you add an proxy inside?
I don't know if you know exactly about China's THE GREAT FIREWALL. Chinese government block people from contacting foreigner

**Comment by Physton** [comment]
这是你的运行环境的问题，非网络墙，估计你使用的是云服务提供的webui吧。打开服务后，等待1分钟，刷新再看看。
