### ISSUE TITLE
[Bug] 在提示词中输入“:<” （表情）导致提示词末尾不断增加多余的逗号

### ISSUE THREAD

**Issue by Kepler-16b** [Physton/sd-webui-prompt-all-in-one#293]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

在提示词中输入“:<” （表情提示词）导致末尾不断增加多余的逗号，似乎是被识别为lora引用。
例如，原始提示词：
1girl, solo, Siren-inspired off-shoulder dresses with flowing chiffon, <lora:hairdetailer:1>
在任意位置加入“:<” 提示词后：
1girl, solo,  :<, Siren-inspired off-shoulder dresses with flowing chiffon, ,  <lora:hairdetailer:1>
且随着提示词的增删，冗余逗号不断增多。

### Steps to Reproduce

在提示词的任意位置加入“ :<”

### OS

Windows

### Browser

Edge

### Stable Diffusion WebUI version

v1.6.0-2-g4afaaf8a

### Extension version

658ae822

### Python version

3.10.11

### Gradio version

3.41.2

**Comment by Physton** [comment]
已修复。
