### ISSUE TITLE
[Bug] 当Checkpoint存在子目录时加载异常

### ISSUE THREAD

**Issue by guclan** [Physton/sd-webui-prompt-all-in-one#295]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

当Checkpoint存在子目录时，点击图标，会加载异常找不到该模型，加载不会带有子目录文件夹前缀。

该问题可能存在于get_extra_networks方法

### 操作系统

Windows

### 浏览器

Chrome

### Stable Diffusion WebUI 版本

cf2772f

### 扩展版本

ac35a1e

### Python 版本

3.10.11

### Gradio 版本

3.44.4

**Comment by Physton** [comment]
没有复现出你所说的问题。
