### ISSUE TITLE
为什么会有违禁词？？害我的网站被封了，怎么删除违禁词啊

### ISSUE THREAD

**Issue by 2575044704** [Physton/sd-webui-prompt-all-in-one#297]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

# 请问作者能新开一个分支，开发个专门为中华人民共和国地区和谐的无害化处理过的标签选择框吗？
# 或者我自己删除，有没有什么办法可以选择性删掉？
![QQ图片20240130173106](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/19410065/d1a45438-fc97-43d3-9980-bb2bd6abcbd2)

### 操作系统

Windows

### 浏览器

Chrome

**Comment by Physton** [comment]
https://aiodoc.physton.com/zh-CN/GroupTags.html#%E6%96%87%E4%BB%B6%E5%8A%A0%E8%BD%BD%E9%A1%BA%E5%BA%8F
