### ISSUE TITLE
[Bug] group_tags translation problem

### ISSUE THREAD

**Issue by BlueberryCat123** [Physton/sd-webui-prompt-all-in-one#298]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

> zh_CN.yaml - 人物 -  二次元角色 - line 198: multiple girls: 魔幻少女

我不太清楚这条翻译是否正确。我觉得他和下面的这条提示词没有区别，感觉不应该在这。

> zh_CN.yaml - 人物 - 对象 - line 44: multiple_girls: 多个女孩

而且SD画出来的也不是什么“魔幻少女”。

### 操作系统

Windows

### 浏览器

Edge

**Comment by Physton** [comment]
感谢指正。已删除 198 行 multiple girls: 魔幻少女
