### ISSUE TITLE
deepl翻译老是报错

### ISSUE THREAD

**Issue by zietenL** [Physton/sd-webui-prompt-all-in-one#3]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/130427069/2db02a77-e7db-4156-9db6-0c345a747f44)
想问一下这个怎么解决，有梯子可以直接上deepl

**Comment by Physton** [comment]
你是用的免费的还是需要apikey的deepl

**Comment by zietenL** [comment]
我用的是免费的

**Comment by Physton** [comment]
免费的都不稳定，建议用免费的阿里云，或者用需要apikey的，注册apikey很简单。
