### ISSUE TITLE
解决：启动DecodeError 与 右上角code 404

### ISSUE THREAD

**Issue by eddiechina** [Physton/sd-webui-prompt-all-in-one#30]
1、控制台启动问题：
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 3779: illegal multibyte sequence
或
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 702: invalid start byte
2、右上角code 404
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/33860299/5577bce1-b8ee-4a85-ab18-ddfa302bd74f)

原因：当使用手动安装的SD时候，没有上述问题；当在同样环境中使用绘世启动时，会产生上述问题。可能是双语插件等冲突。
解决：修改history.txt2img.json，history.img2img.json，history.img2img_neg.json等，由格式ANSI另存为UTF-8。

**Comment by Physton** [comment]
感谢。今日更新的版本 [@e04feb9](https://github.com/Physton/sd-webui-prompt-all-in-one/commit/e04feb945cd1ad6cff06c6f981d8c2e8cf580c24) 加上了自动检测文件编码，可能应该没问题了？这问题我也没碰到，不知道为什么会产生文件编码错误的。
