### ISSUE TITLE
[Bug] 关于prompt格式中最后逗号的设置产生的一些问题，如无法方便复现原图

### ISSUE THREAD

**Issue by ligerye** [Physton/sd-webui-prompt-all-in-one#300]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

当在prompt格式中勾选上去除Prompt最后的一个逗号后，会始终自动删去最后一个tag的逗号，然而，如果将最后一个prompt双击注释掉后，其前一个单词后面的逗号并不会自动去掉，且会伴随生成的图一并存入到exif信息当中。（这种情况对于正负面输入框都是存在的，对于我发现的情况是正面多了一个末尾句号，主要一般负面不怎么动）
如果后面想要将生成的图片进行复现或对其进行hires.fix放大操作时，使用图片浏览器将其生成信息发送到t2i界面时，由于之前的操作“勾选上去除Prompt最后的一个逗号”，这会导致自动将原来被留下的末尾的逗号被抹掉，因此会导致生成的图片产生意料之外的变化（虽然有时这种变化是比较微妙的），不能复现原来的图。
另外，如果去掉勾选“去除Prompt最后的一个逗号”，也会导致相同的问题，因为虽然正面输入正确保留了最后的逗号，然而在负面输入框又会自动地加上一个末尾逗号，但对于之前发送的图是不存在这个末尾逗号的，故也会影响复现。

设想的解决办法：
A：在勾选了去除Prompt最后的一个逗号的情况下，当最后一个prompt被禁用后也会自动删除位于其前面的逗号，即始终去除掉最后末尾的逗号；这样就保证了生成的图片中不会发生意外存在末尾逗号的情况；
B：增加一个新的选项，不对末尾的逗号做任何额外处理，即既不删也不增，保留原始情况；这样对于原图存在末尾的逗号时，即使发送到t2i界面，也会保证这个逗号正确地保留下来，从而正确复现原图。
应该也有其他的具体解决方案，希望作者大大将这里的末尾逗号功能给改良一下，感谢！

### 如何复现

以下例子以正面输入的情况为例：
1.输入正面词
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/6b630cb2-beb3-4099-a6d3-6e1b05aa84a2)
2.禁用掉最后一个词，并进行生成（此时留存了本来应该删除的逗号，但此时是开启了去除Prompt最后的一个逗号的选项的）
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/37ae2b11-dd62-44f9-82be-ff6f4a06284a)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/3b190a03-a500-426c-a8b2-db10492b4995)
3.查看刚才生成的图的图片信息（可以看到逗号被意料之外的保留了下来）
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/500f6d0a-6176-4ef5-bcb4-5f0c7d437418)
4.将该图片的信息发送到t2i界面中（发送前已清空掉输入框）（可以看到原来末尾的逗号被自动删掉了，这正是因为开启了去除Prompt最后的一个逗号的选项导致的，也因此无法完美复现原图了）
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/5bfcc7b3-0a4e-4c0c-8124-4745424cf9b3)

### 操作系统

Windows

### 浏览器

Edge

### Stable Diffusion WebUI 版本

1.7.0

### 扩展版本

b35ee8e

### Python 版本

3.10.11

### Gradio 版本

3.41.2

**Comment by Physton** [comment]
感谢你的反馈！

A：在勾选了去除Prompt最后的一个逗号的情况下，当最后一个prompt被禁用后也会自动删除位于其前面的逗号，即始终去除掉最后末尾的逗号；这样就保证了生成的图片中不会发生意外存在末尾逗号的情况；
> 这个可以修复。

B：增加一个新的选项，不对末尾的逗号做任何额外处理，即既不删也不增，保留原始情况；这样对于原图存在末尾的逗号时，即使发送到t2i界面，也会保证这个逗号正确地保留下来，从而正确复现原图。
应该也有其他的具体解决方案，希望作者大大将这里的末尾逗号功能给改良一下，感谢！
> 这个思路无法实现。但是我会考虑使用 #290 的方案：增加一个选项框，如果勾选，就监听默认提示词框的变化，并使用本插件格式化提示词（这是目前插件默认启用的功能）。如果不勾选，插件将不自动读取默认提示词框的变化（这样就不会格式化提示词，导致提示词变动）。

**Comment by ligerye** [comment]
> 感谢你的反馈！
> 
> A：在勾选了去除Prompt最后的一个逗号的情况下，当最后一个prompt被禁用后也会自动删除位于其前面的逗号，即始终去除掉最后末尾的逗号；这样就保证了生成的图片中不会发生意外存在末尾逗号的情况；
> 
> > 这个可以修复。
> 
> B：增加一个新的选项，不对末尾的逗号做任何额外处理，即既不删也不增，保留原始情况；这样对于原图存在末尾的逗号时，即使发送到t2i界面，也会保证这个逗号正确地保留下来，从而正确复现原图。 应该也有其他的具体解决方案，希望作者大大将这里的末尾逗号功能给改良一下，感谢！
> 
> > 这个思路无法实现。但是我会考虑使用 #290 的方案：增加一个选项框，如果勾选，就监听默认提示词框的变化，并使用本插件格式化提示词（这是目前插件默认启用的功能）。如果不勾选，插件将不自动读取默认提示词框的变化（这样就不会格式化提示词，导致提示词变动）。

感谢大大看到这里，期待该问题早日修复。
另外，我对该问题的临时办法是，手动在最后一个tag的内部加上一个逗号，而不是在外面增加，这样就将tag和逗号变为一个整体，就可以保证不会被自动删去了。
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/60023469/10381899-c29e-40db-acfe-d15175434ddf)

我也认为A方案是比较容易且符合直觉一些的（印证“去除Prompt最后的一个逗号”的功能描述）；另外，看描述对于B的处理是增加监听提示词框的开关，是不是意味着关闭后会让tag后的空格也会一并不做处理呢？

最后祝大大龙年快乐！

**Comment by Physton** [comment]
A：这个已修复。
B：这个比较复杂一点，未来会开发。

**Comment by Physton** [comment]
B: 已增加功能选项：是否自动加载webui提示词

**Comment by ligerye** [comment]
> B: 已增加功能选项：是否自动加载webui提示词

经过实测问题已充分解决，A避免了尾缀逗号的产生，B可以便于读取和保留图中生成信息的原始格式。
最后再次感谢大大的辛苦付出！
