### ISSUE TITLE
[Feature] Refresh for Extra Networks

### ISSUE THREAD

**Issue by StylusEcho** [Physton/sd-webui-prompt-all-in-one#302]
### What feature do you want or what suggestions do you have?

Hi, sometimes I add Checkpoints or Loras while the Web UI is open, for them to show up I need to refresh the whole page, which takes a while.

But another issue as well is when changing between checkpoints of different SD versions (eg. 1.5 -> XL), the list of Loras and TIs doesn't change, which is problematic as they aren't compatible.

I think a simple way to solve this is to add a refresh button in the interface, but what would be nice too is auto-refresh when changing between SD versions.

**Comment by jayododds** [comment]
A refresh button would be a very welcome addition for sure.

**Comment by Physton** [comment]
Added refresh button and auto-refresh feature.
