### ISSUE TITLE
[Bug] Extra Networks not loading Checkpoints in subfolders

### ISSUE THREAD

**Issue by StylusEcho** [Physton/sd-webui-prompt-all-in-one#303]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

When a checkpoint is located in a subfolder of Stable-diffusion, clicking on it in Extra Networks results in a fallback checkpoint being loaded instead, that is located in the root folder.

### Steps to Reproduce

1. Place checkpoint in models/Stable-diffusion/
2. Place another checkpoint in models/Stable-diffusion/<insert folder here>
3. Load up webui or refresh page in current instance
4. Wait for extension to fully initialise and Extra Networks list to populate
5. Click on checkpoint that is located in subfolder

### Screenshot or log

Files:
- models/Stable-diffusion/anithing_v10.safetensors
- models/Stable-diffusion/2D/mistoonAnime_v20.safetensors

Console:
`Checkpoint mistoonAnime_v20.safetensors not found; loading fallback anithing_v10.safetensors [a6fad5698d]`

### OS

Windows

### Browser

Edge

### Stable Diffusion WebUI version

Forge f0.0.12-latest-155-gd81e353d

### Extension version

62e7040c

### Python version

3.10.6

### Gradio version

3.41.2

**Comment by Physton** [comment]
Fixed.
