### ISSUE TITLE
[Feature] 请问，有换行后自动添加空格的功能吗？

### ISSUE THREAD

**Issue by StrangeJoe2613** [Physton/sd-webui-prompt-all-in-one#307]
----------------------------------------------------------------------------------------
比如，我写了一段关键词，我喜欢把这些关键词分类，他们之间空一行，这样好让我整理思路。

```
#Lora#
<lora:asianGirlsFace_v1:0.8>, 

#画质#
((masterpiece, high quality, best quality, 8k, wallpaper, fine lineart, highly detailed, absurdres)), 
(extremely detailed, realistic, intricate details, highres), 
(cinematic lighting, sunlight, volumetric), 

#场景#
pink background, 

#构图#
(((full_shot, full_body))), from_above, 

#人物#
1girl, solo, shiny_skin, brown hair, straight_hair, brown eyes, pretty hands, 
```
----------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------
但我点了一下空白处，插件自动把我的空行去掉，就变成了下边这样。哪怕我手动在提示词里加入空行，只要添加新的关键词空行就又没了。而且会在#xxx#后面加一个,和空格。

```
#Lora#, 
<lora:asianGirlsFace_v1:0.8>, 
#画质#, 
((masterpiece, high quality, best quality, 8k, wallpaper, fine lineart, highly detailed, absurdres)), 
(extremely detailed, realistic, intricate details, highres), 
(cinematic lighting, sunlight, volumetric), 
#场景#, 
pink background, 
#构图#, 
(((full_shot, full_body))), from_above, 
#人物#, 
1girl, solo, shiny_skin, brown hair, straight_hair, brown eyes, pretty hands, 
```
----------------------------------------------------------------------------------------

**Comment by Physton** [comment]
1. 粘贴到webui输入框中时，插件会把多个换行符变成一个，如果在插件的输入框使用添加换行符功能，则会保留多个换行符。
你可以让插件不自动解析和格式化webui输入框的内容。
2. `#Lora#` 这种写法，是注释的意思吗，现在SD默认就支持这种格式吗，还是第三方插件实现的。

**Comment by StrangeJoe2613** [comment]
> 1. 粘贴到webui输入框中时，插件会把多个换行符变成一个，如果在插件的输入框使用添加换行符功能，则会保留多个换行符。
>    你可以让插件不自动解析和格式化webui输入框的内容。
> 2. `#Lora#` 这种写法，是注释的意思吗，现在SD默认就支持这种格式吗，还是第三方插件实现的。

您好，谢谢您的解答。
1、您说的`你可以让插件不自动解析和格式化webui输入框的内容`是怎么设置？
2、`#xxx#`这个是我自己弄的注释，因为我发现好像这样并不会对图片内容有影响，而且在读取图片tags信息时，#中的内容也自然消失了。

**Comment by Physton** [comment]
1、您说的`你可以让插件不自动解析和格式化webui输入框的内容`是怎么设置？
> ![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/42cd60d6-02ea-4ace-bdd7-a7f216e985e6)

 2、`#xxx#`这个是我自己弄的注释，因为我发现好像这样并不会对图片内容有影响，而且在读取图片tags信息时，#中的内容也自然消失了。
> 如果 # 是官方支持的格式，可以让插件在 #注释# 后面不自动加逗号。但目前不明确，不知是否有其它的用途，所以暂时不修改。

**Comment by StrangeJoe2613** [comment]
> 1、您说的`你可以让插件不自动解析和格式化webui输入框的内容`是怎么设置？
> 
> > ![image](https://private-user-images.githubusercontent.com/12066768/310502423-42cd60d6-02ea-4ace-bdd7-a7f216e985e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mjk0ODksIm5iZiI6MTcwOTcyOTE4OSwicGF0aCI6Ii8xMjA2Njc2OC8zMTA1MDI0MjMtNDJjZDYwZDYtMDJlYS00YWNlLWJkZDctYTdmMjE2ZTk4NWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEyNDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMGVkNDkyYzE3YmZiMWE2MDA0YzE1Njk4ZTQ5YzgzMzc2ZmEzZjZlYzIxZDAyM2I0NmNjYzdiODM2YzZkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2eTRw0lQucFvViUPaRWYZAdmlhzjuNneIN25lb9afxs)
> 
> 2、`#xxx#`这个是我自己弄的注释，因为我发现好像这样并不会对图片内容有影响，而且在读取图片tags信息时，#中的内容也自然消失了。
> 
> > 如果 # 是官方支持的格式，可以让插件在 #注释# 后面不自动加逗号。但目前不明确，不知是否有其它的用途，所以暂时不修改。

感谢！！！
