### ISSUE TITLE
[Feature] 如何通过API调用本项目将中文翻译成英文

### ISSUE THREAD

**Issue by XiangjiBU** [Physton/sd-webui-prompt-all-in-one#310]
### Is this feature related to existing issues?

你好,我想知道如何通过API调用本项目将中文翻译成英文?
我尝试通过下面的方式去调用,但是data的内容不知道是什么样的
```
url = 'http://127.0.0.1:7680/physton_prompt/translate'
resp = requests.post(url=url, json=data)
```
请问能提供一些指导吗?

### What feature do you want or what suggestions do you have?

None

**Comment by Physton** [comment]
1. 浏览器抓包看请求参数
2. 查阅源码：`scripts/on_app_started.py`
3. 查阅源码：`src/src/utils/gradioAPI.js`
