### ISSUE TITLE
[Bug] chatGPT dialog cannot be fully displayed

### ISSUE THREAD

**Issue by chace20** [Physton/sd-webui-prompt-all-in-one#312]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

When I click the chatGPT button, the pop-up dialog box cannot be fully displayed and cannot be scrolled, so I cannot enter the api base.

### 如何复现

On my macbook.

### 截图或日志

![report](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/7760149/00b2befe-ca8d-4c6a-88bf-8cdec2e7629a)

### 操作系统

macOS

### 浏览器

Chrome

### Stable Diffusion WebUI 版本

1.6.1

### 扩展版本

90bc20f3c3bb73b6140f96d2f4b466221f2f684d

### Python 版本

3.10.4

### Gradio 版本

3.41.2

**Comment by Physton** [comment]
Because your resolution is too low, you can click on the blue icon on the left to collapse the panel.

**Comment by chace20** [comment]
虽然是可以通过缩小浏览器大小来解决这个问题。但是体验还是不太好。

比如这里的黑名单对话框，点对话框外面不能隐藏对话框，下面的保存和关闭也显示不出来，只能刷新网页才能操作。

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/7760149/d83a4aa0-c873-4c10-9f09-3f7d0824ebd4)
