### ISSUE TITLE
[Bug] Only 1 entry of a subfolder/folder getting drawn

### ISSUE THREAD

**Issue by V0ID-Whisperer** [Physton/sd-webui-prompt-all-in-one#313]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [X] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

So I have a few sub folders in my lora folder. It worked fine before but suddenly it doesn't work anymore. It only shows 1 subfolder and only 1st file of those folders.
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/94946192/abf62ca5-38f0-449a-b393-8c5c1b9e1b36)
And there are other 4 loras in the same folder.

### OS

Ubuntu

### Browser

Chrome

### Stable Diffusion WebUI version

v1.8.0

### Extension version

90bc20f3

### Python version

3.10.0

### Gradio version

3.41.2

**Comment by V0ID-Whisperer** [comment]
Other extentions find those other subfolders and loras just fine

**Comment by Physton** [comment]
Have you switched to the SDXL model? The SDXL model is not compatible with some of the older Lora models.

**Comment by V0ID-Whisperer** [comment]
Oh ye.. Switched to an another model now they are back :)
