### ISSUE TITLE
Is there anyway that I can use this feature via API? 想问一下有办法通过api调取这个功能吗？

### ISSUE THREAD

**Issue by Pancat007** [Physton/sd-webui-prompt-all-in-one#314]
### 你想要什么功能或者有什么建议？

If I install this feature, I can easily use this feature via webui prompt input box, but what if I use API to use SD? e.g. the /txt2img api
如果直接用webui，可以直接弹出提示，或者操作，但是如果是通过api来call 请求的话，有办法能用上吗，或者怎么集成，比如/txt2img这个接口？

**Comment by Physton** [comment]
https://github.com/Physton/sd-webui-prompt-all-in-one/issues/310#issuecomment-1993356751
