### ISSUE TITLE
[Bug] 标签颜色选择器不生效

### ISSUE THREAD

**Issue by chace20** [Physton/sd-webui-prompt-all-in-one#315]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/7760149/9c3ee73b-efed-4192-a4b9-15b00dbc4196)

如题，点击这个按钮没有任何反应，预期应该会有一个color-picker弹出来。

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/7760149/7b9450ad-9580-4c1e-9d14-ba2ff75aaecd)

### 如何复现

直接点击

### 截图或日志

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/7760149/43f0cc7d-ebd0-4d83-bff1-e42f410c7b2b)

### 操作系统

macOS

### 浏览器

Chrome

### Stable Diffusion WebUI 版本

1.6.1

### 扩展版本

90bc20f3c3bb73b6140f96d2f4b466221f2f684d

### Python 版本

3.10.4

### Gradio 版本

3.41.2

**Comment by Physton** [comment]
更新到最新版本再试下。
