### ISSUE TITLE
[Feature] 适配本地llm比如ollama或者lmstudio

### ISSUE THREAD

**Issue by smartjx** [Physton/sd-webui-prompt-all-in-one#316]
### Is this feature related to existing issues?

在目前已有的Chatgpt功能上简单修改即可实现，ollama和lmstudio都支持chatgpt api协议的

### What feature do you want or what suggestions do you have?

![屏幕截图 2024-03-23 205838](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/1443333/a4c1d6ae-b4a0-4d61-b316-9a1fcaa95f5f)
参见图片描述，通过简单的修改支持本地大模型进行翻译

**Comment by haddadrm** [comment]
https://github.com/Physton/sd-webui-prompt-all-in-one/issues/306#issue-2154611032

**Comment by Physton** [comment]
只需要模型自定义就好了吗？

**Comment by haddadrm** [comment]
Yes, 

The feature will enable users to utilize alternative LLMs to ChatGPT API, such as Ollama and Lmstudio. Ollama and Lmstrudio  provide interfaces similar to ChatGPT’s API, but run locally, with free open-source LLMs.
