### ISSUE TITLE
[Bug] lost separators in prompt

### ISSUE THREAD

**Issue by siilky** [Physton/sd-webui-prompt-all-in-one#317]
### Issue Feedback

- [X] I confirm that I have searched for a solution to this issue in the [FAQ](https://aiodoc.physton.com/FAQ.html) and couldn't find a solution.
- [x] I confirm that I have searched for this issue in the [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) list (including closed ones) and couldn't find a solution.
- [X] I confirm that I have read the [Wiki](https://aiodoc.physton.com/) and couldn't find a solution.

### Describe the Issue

prompt commas/separators are lost randomly after switching certain keywords on/off
from the screenshot you may think it is related to comma after BREAK, but it isn't, on more complex prompts it may happen somewhere in the middle and affect multiple keywords at once

### Steps to Reproduce

happens (or not) quite for a random set of keywords,
- no format options are set
- just switch kw on/off 

### Screenshot or log

https://i.imgur.com/zvebG49.gif (this is an animated gif, click it to view)

### OS

Windows

### Browser

Edge

### Stable Diffusion WebUI version

forge  f0.0.17v1.8.0rc-latest-276-g29be1da7

### Extension version

2a328176

### Python version

3.10.6

### Gradio version

3.41.2

**Comment by Physton** [comment]
I can't see the screenshot you uploaded.

**Comment by siilky** [comment]
> I can't see the screenshot you uploaded.

what is the issue with the screenshot?

**Comment by Physton** [comment]
> > I can't see the screenshot you uploaded.
> 
> what is the issue with the screenshot?

Unable to open the link. HTTP ERROR 429

**Comment by siilky** [comment]
ok attached it here
https://github.com/Physton/sd-webui-prompt-all-in-one/assets/28986709/998711e1-9bd5-4504-b9db-668bc3e31cba

**Comment by Physton** [comment]
> ok attached it here https://github.com/Physton/sd-webui-prompt-all-in-one/assets/28986709/998711e1-9bd5-4504-b9db-668bc3e31cba

Received, I'll fix this bug.

**Comment by Physton** [comment]
I modified the code, please try again after updating.

**Comment by siilky** [comment]
seems working now, thank you
