### ISSUE TITLE
[Feature] custom model name

### ISSUE THREAD

**Issue by thejohnd0e** [Physton/sd-webui-prompt-all-in-one#318]
### What feature do you want or what suggestions do you have?

Please add the ability to specify a custom model name.

![Screenshot - 2024-03-25 09 22 18](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/115493464/e827dd60-2159-4a14-858d-6de636c9347d)

**Comment by Physton** [comment]
The latest version now supports custom model names.

**Comment by thejohnd0e** [comment]
> The latest version now supports custom model names.

Thank you!
