### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sk8boi** [Physton/sd-webui-prompt-all-in-one#319]
### 反馈须知

- [X] 我确认已经在 [常见问题](https://aiodoc.physton.com/zh-CN/FAQ.html) 中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认已经在 [Issues](https://github.com/Physton/sd-webui-prompt-all-in-one/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解决方法。
- [X] 我确认阅读了 [文档](https://aiodoc.physton.com/zh-CN/)，没有找到解决方法。

### 描述问题

作者您好，我有两个问题想请教您。
1、第一是看到您的webui界面的风格，类似这种颜色风格的Generate按钮
![企业微信截图_17114469748850](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/73382519/3be606d8-deaa-4941-b5dd-2a92e186ec16)
我曾尝试在stable-diffusion-webui目录下的style.css文件下添加指定风格
和在stable-diffusion-webui/modules目录下的ui_toprow.py指定对应的id
![q11](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/73382519/a4bf2a9f-6e89-426c-a3de-2fad7956f404)
但都失败，我想请教您是怎么样修改这个样式的
2、第二是您这个插件方面的问题，我按照您的指导编辑了一个/sd-webui-prompt-all-in-one/group_tags目录下的custom.yaml文件
用于编辑我的提示词格式。
![q21](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/73382519/73b0eab9-65b3-44d0-9f97-6baa6d6a6fdf)
检查编辑的提示词并无错误，但是颜色并没有发生改变
![q22](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/73382519/229b8489-568a-4fb2-ac72-56df397e5ece)
然后我直接修改zh_CN.yaml中的color参数，只有部分按钮颜色发生改变，我想问一下还有更好的办法能正确改变提示词背景颜色嘛。
谢谢大佬，给您点了杯咖啡

### 操作系统

Ubuntu

### 浏览器

Chrome

**Comment by Physton** [comment]
感谢咖啡，我晚点仔细看看。

**Comment by Physton** [comment]
1. 本插件没有修改webui的默认样式主题，这个我也没研究过，所以我无法帮助你。
  我使用的 webui 主题是 https://github.com/lobehub/sd-webui-lobe-theme
3. 如果自定义了颜色，可能需要再界面中点一下恢复默认颜色按钮：
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/4cac557a-579c-49ea-92d7-e7a8f4e27d44)

**Comment by sk8boi** [comment]
好的，谢谢作者
