### ISSUE TITLE
扩展安装后前端不显示，帮看看什么问题

### ISSUE THREAD

**Issue by ScorpioZeng** [Physton/sd-webui-prompt-all-in-one#32]
![360截图20230517100907490](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/65064633/53b1bfbb-d990-4009-8888-d570b9abcbcd)
![360截图20230517100845447](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/65064633/6c3ab7aa-d8a5-4951-a247-3285fbc309f4)

**Comment by Physton** [comment]
更新webui的环境到13周及以上
