### ISSUE TITLE
为什么安装本插件后在MAC系统下的stable diffusion不起作用，显示不了呢？谢谢Why does stable diffusion under MAC system not work after installing this plugin? thank you

### ISSUE THREAD

**Issue by lisongze8** [Physton/sd-webui-prompt-all-in-one#35]
为什么安装本插件后在MAC系统下的stable diffusion不起作用，显示不了呢？谢谢
Why does stable diffusion under MAC system not work after installing this plugin? thank you

**Comment by Physton** [comment]
Please see / *请参考*:

1. https://github.com/Physton/sd-webui-prompt-all-in-one#q-%E6%98%BE%E7%A4%BA%E9%94%99%E8%AF%AF%E6%B6%88%E6%81%AF%E8%BF%9E%E6%8E%A5%E5%88%B0%E5%90%8E%E5%8F%B0%E6%8E%A5%E5%8F%A3%E6%9C%8D%E5%8A%A1%E5%A4%B1%E8%B4%A5%E8%AF%B7%E6%89%8B%E5%8A%A8%E5%86%8D%E5%88%B7%E6%96%B0%E4%B8%80%E6%AC%A1%E7%BD%91%E9%A1%B5%E5%A6%82%E6%9E%9C%E8%BF%98%E6%98%AF%E4%B8%8D%E8%A1%8C%E8%AF%B7%E9%87%8D%E5%90%AFwebui
2. https://github.com/Physton/sd-webui-prompt-all-in-one#q-display-error-message-connection-to-backend-api-service-failed-please-manually-refresh-the-webpage-if-it-still-doesnt-work-please-restart-the-webui

In addition, the version of WebUI needs to be at or above `22bcc7b` (`22bcc7b`, `5ab7f21`).
*另外，webui的版本需要在`22bcc7b`及以上（`22bcc7b`、`5ab7f21`）*
