### ISSUE TITLE
安装插件后翻译需要设置API怎么办？

### ISSUE THREAD

**Issue by idesign2018** [Physton/sd-webui-prompt-all-in-one#36]
安装插件后翻译需要设置API，点击设置并没有弹出填写API的选项，没有一点反应，这个怎么处理？还有就是可以提供一个默认的翻译平台吗？现在相当于半成品，不能做到开箱即用体验，很麻烦就不想用了。希望能提供对应翻译平台的免费接口，如果有人需要单独设置API的话，也可以单独设置，这样体验更好

**Comment by idesign2018** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/42263070/e7e6d28d-7173-46ea-b902-1f8bf45c2454)
当有中文和英文的时候，我选择了翻译英文，就翻译不了了

**Comment by idesign2018** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/42263070/0b0ef150-d4c7-4002-a183-66fde02d4ec6)
既然是中文的，建议提示也可以汉化一下，会更方便使用

**Comment by Physton** [comment]
1. 你选择了本地语言为英文，tooltip怎么会去显示中文？？？既然你选择了英文，所以为什么需要翻译？英文翻译到英文？软件默认就是选择中文的，不知道你为什么要去改。
2. 默认就是免费的阿里云翻译，开箱即用的，还提供了几十种免费翻译和APIkey的翻译接口！

**Comment by idesign2018** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/42263070/cfe1597a-a91b-40b1-aa5c-59686829f9e0)
输入的是中文，明明选择了翻译为英文，下面却没有翻译结果，是什么原因？初次使用全是bug，需要加油哦~

**Comment by idesign2018** [comment]
> 1. 你选择了本地语言为英文，tooltip怎么会去显示中文？？？既然你选择了英文，所以为什么需要翻译？英文翻译到英文？软件默认就是选择中文的，不知道你为什么要去改。
> 2. 默认就是免费的阿里云翻译，开箱即用的，还提供了几十种免费翻译和APIkey的翻译接口！

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/42263070/d2976032-7281-42f5-a965-5a80e969fd1d)
为什么这个却翻译不了？

**Comment by Physton** [comment]
仔细看设置中的每个按钮

**Comment by idesign2018** [comment]
> 仔细看设置中的每个按钮

我视乎找到了正确的打开方式，感谢感谢
