### ISSUE TITLE
BUG：拖拽提示词位置会使sdwebui原生输入框无法使用

### ISSUE THREAD

**Issue by MomoCyann** [Physton/sd-webui-prompt-all-in-one#37]
拖拽会在网页留下一个输入框的残影，影响使用，不知道截图看得清楚不，第一张图右边有残影的输入框滚动条
![QQ截图20230518172817](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/32864187/0d465c13-9f3d-4c34-8872-6460a4d76140)

![QQ截图20230518172807](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/32864187/d6ee1c49-f03d-4947-bcac-159d9346c108)

**Comment by Physton** [comment]
收到，会尽快修复

**Comment by Physton** [comment]
请问你使用的是什么浏览器，具体是怎么拖拽的，我没有复现出此问题。

**Comment by bikingfree1989** [comment]
拖拽功能不是很好使，压根就难以把鼠标放上去拖。

**Comment by Physton** [comment]
@bikingfree1989 不知道你为什么很难把鼠标放上去拖，没有人反应过这个问题。你鼠标放到关键词上，按住鼠标左键就可以拖了，不能先点击。如果还是不好拖，可能是是浏览器兼容问题，你可以换个浏览器再试。

**Comment by aaronkingdom** [comment]
我使用一切正常,chrome.. 请关闭你们的一些翻译或者其它软件的网页划词功能和快捷键,例如网页词典和谷歌翻译那些,有可能冲突
