### ISSUE TITLE
负面提示词部分会有一点问题

### ISSUE THREAD

**Issue by lxygodxj** [Physton/sd-webui-prompt-all-in-one#39]
昨天做了个什么操作我已经忘了， 大概是一下复制了非常多的提示词， 然后点击AB, EN,然后负面提示词的翻译栏就失效了。之后无论怎么重启都不会翻译负面提示词了。 请作者看看问题的原因。

**Comment by Physton** [comment]
无法复现你的问题，请给出详细的截图演示和控制台日志。
或者删除扩展重新安装
