### ISSUE TITLE
Avoid removing whitespace between prompts (trim)

### ISSUE THREAD

**Issue by steak3** [Physton/sd-webui-prompt-all-in-one#42]
Hello,

When the prompt input loses focus, the prompts currently changes from "masterpiece, best quality" to "masterpiece,best quality".
Doing like this helps improve prompt readablilty and leaves the user style unchanged.

Thanks !

**Comment by Physton** [comment]
At first there were spaces, but lost9999 mentioned that extra spaces consume token count. #10

**Comment by steak3** [comment]
I see. 
Then I’m wondering : shouldn’t we leave this optimisation responsibility to the user so he can format it as he used to ? He can always trim it by himself if he really needs to.

I believe it is not the goal of this extension, but I may be mistaken.

**Comment by Physton** [comment]
The extension has not been developed for long, and I am the only one, so I do not have much energy to develop many features that do not affect normal use. One is affecting token counting, and the other is just a matter of convenience for viewing. At present, I must prioritize developing features that affect functionality. This can only be done gradually, but it will definitely be done in the future. Others have also mentioned this issue.

**Comment by Physton** [comment]
A checkbox has been added to the settings to indicate whether to keep or remove spaces.
