### ISSUE TITLE
为什么不能设置谷歌翻译的国内镜像？像“划词翻译”插件里那样？

### ISSUE THREAD

**Issue by pendave** [Physton/sd-webui-prompt-all-in-one#43]
我去找到主目录下的 translate_apis.json

打开后添加了一个谷歌镜像进去，或者直接修改了里面的 Google 那个美国的 URL，保存后重启了但是还是不能用镜像来翻译啊！

参见我这里对沉浸式翻译的提问：
https://github.com/immersive-translate/immersive-translate/issues/307

得到了很好的解决，划词翻译那个插件里也是可以设置镜像的。

不知道大佬您的插件怎么玩转这样的国内谷歌翻译镜像？很想用啊！:)

**Comment by Physton** [comment]
通过测试，发现你所使用的镜像地址，只是网页的镜像，并不是官网api接口的镜像。
你在另一个扩展中可以使用是因为，他们是通过爬虫爬取的网页，而不是调用的官网API。
你如果可以提供谷歌API接口的镜像网址给我，我可以帮你开发到扩展中。（但任何第三方的接口镜像都有可能导致你的apikey泄露。）
我从不使用任何镜像，因为他们的服务我都可以访问到（省略一万字）。
