### ISSUE TITLE
什么时候能开放一下自定义CSS功能，现在界面好花，想自己优化一下。

### ISSUE THREAD

**Issue by strongshuai** [Physton/sd-webui-prompt-all-in-one#44]
<img width="1619" alt="微信截图_20230519211438" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/32892476/beecee57-6e30-40ff-b5f5-1a6af1c807ff">
画面真的挺花的。。需要弱化一下或者板块重新划分一下。
插件是很好用的，在B站看见有人觉得画面花都劝退了。。

**Comment by Physton** [comment]
开放了啊：https://github.com/Physton/sd-webui-prompt-all-in-one#custom-theme--%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%BB%E9%A2%98

**Comment by strongshuai** [comment]
> 

。。没仔细看介绍，赞
我先去研究下

**Comment by Physton** [comment]
> B站总有些人觉得自己是上帝。

你如果做了好的主题，可以提交PR做一份贡献。

**Comment by strongshuai** [comment]
<img width="1909" alt="微信截图_20230520013641" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/32892476/d0a9ad98-de71-4f70-ab7b-148ca8aa5dc7">
<img width="1920" alt="微信截图_20230520013656" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/32892476/e850c805-8fdf-424f-9bef-fdd3f5db7ddc">
初步调了下我自己喜欢的感觉，弱化多余的色彩。
好久没改CSS，太费劲了

**Comment by Physton** [comment]
任何修改都可以提交上来

**Comment by strongshuai** [comment]
<img width="1892" alt="微信截图_20230520020752" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/32892476/50022aab-7b87-42fb-a871-ec213cbbcb0f">
<img width="1896" alt="微信截图_20230520021019" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/32892476/d6a04926-1a46-43e0-8ada-c9a4c91183c7">
<img width="1891" alt="微信截图_20230520021005" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/32892476/b17f8039-366b-449f-9ffa-9d000bfd5c42">
尝试和自带的tag框结合，整体性更强

> 任何修改都可以提交上来
我不知道咋提交没用过这个。

**Comment by Physton** [comment]
需要使用git，你可以搜下git fork仓库和提交 PR
