### ISSUE TITLE
autoTranslateByCSV

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#45]
希望能增加自動以CSV翻譯

https://github.com/Physton/sd-webui-prompt-all-in-one/blob/727923e6f546d64dd95ec2a4ab7b0a27d13ecdef/src/src/components/phystonPrompt.vue#L1085

https://github.com/Physton/sd-webui-prompt-all-in-one/blob/727923e6f546d64dd95ec2a4ab7b0a27d13ecdef/src/src/mixins/languageMixin.js#L283

**Comment by Physton** [comment]
不知道你指的什么，
要是单词现在就已经是会尝试使用csv翻译了。
要是句子，那么支持不了。

**Comment by Physton** [comment]
https://github.com/Physton/sd-webui-prompt-all-in-one/blob/727923e6f546d64dd95ec2a4ab7b0a27d13ecdef/src/src/mixins/languageMixin.js#L70

**Comment by bluelovers** [comment]
意思是 就像開啟自動翻譯一樣 但是只單獨開啟 自動用csv 翻譯
而需要透過網路翻譯的則等到手動自己按才翻譯

現在的自動翻譯則是會包含用網路翻譯

**Comment by Physton** [comment]
你可以取消掉自动翻译框选，使用tag补全插件的功能来输入内容选择内容，需要的时候再手动点击翻译按钮

**Comment by Physton** [comment]
在翻译设置中增加了此功能。
<img width="716" alt="Snipaste_2023-05-22_00-23-06" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/30ee91d5-ae25-430d-8d64-e0f25c0c050d">
