### ISSUE TITLE
Please add tooltip descriptions on hover for buttons

### ISSUE THREAD

**Issue by ghostsquad** [Physton/sd-webui-prompt-all-in-one#46]
The buttons aren't always clear what they do/mean. It would be really nice if when hovering over a button, I got a tooltip that describes the action the button does.

**Comment by Physton** [comment]
you turned off the tooltip by yourself, the last one in the settings button.

**Comment by ghostsquad** [comment]
> you turned off the tooltip by yourself, the last one in the settings button.

I'm not sure what you mean. Maybe this setting should be _hidden_ inside the `settings` menu? I don't know which button I pressed that turned off tooltips, and now I don't have a way to see which button turns the tooltips back on. LOL

**Comment by Physton** [comment]
<img width="392" alt="Snipaste_2023-05-20_09-15-09" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/02c89e1c-56d6-4f6b-8e20-585f041a0633">

**Comment by ghostsquad** [comment]
oh interesting. I had to click it off then back on to get it to work. It appears that the checkbox is "checked" by default, but tooltips aren't enabled by default.

**Comment by ghostsquad** [comment]
it might be useful to not immediately close an issue only a couple minutes after it's opened, and maybe ask the user what's going on ;)

**Comment by Physton** [comment]
I reinstalled the plugin and by default, the tooltip option is checked and can be displayed normally. I'm not sure why you need to switch it manually, maybe it's a browser issue?
