### ISSUE TITLE
Delete all history also deletes favorites

### ISSUE THREAD

**Issue by ghostsquad** [Physton/sd-webui-prompt-all-in-one#47]
As I was playing around with this extension, I deleted all the history for a negative prompts, and I expected that my favorites would stay.

**Comment by Physton** [comment]
Deleting all browsing history does not delete the favorites.

**Comment by ghostsquad** [comment]
my eyes must deceive me! Do I need to prove this with a gif or something?

**Comment by ghostsquad** [comment]
Let me clarify. You use the history to _mark_ favorites. I expected that favorited items remained in history. It appears they will be removed from history, but remain in the favorites menu. So I guess we are both right.

**Comment by Physton** [comment]
The History only keeps the last 100 records, and any records beyond that will be deleted. However, the favorites won't be deleted automatically.

**Comment by Physton** [comment]
![c](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/1b20344b-7e25-4cf4-9def-0df6756c5fff)

**Comment by ghostsquad** [comment]
Thanks. Hopefully someone else will see this and not get as confused as I was!
