### ISSUE TITLE
Embedding 输入问题

### ISSUE THREAD

**Issue by angelineage** [Physton/sd-webui-prompt-all-in-one#50]
在默认输入框隐藏的时候，点击Embedding模型只会激活到正向提示框，即使先把光标放到负向提示框也不起作用，要把默认的负向提示词输入框打开，并且把光标放到默认输入框才能正常输入，为了界面简洁我会选择隐藏默认提示词输入框，希望能解决这个问题，谢谢。
<img width="1791" alt="截屏2023-05-20 13 08 41" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/128225199/4ea097d8-41cd-4f3e-8927-4c6fbb4caddb">

**Comment by Physton** [comment]
收到

**Comment by Physton** [comment]
已修复。
