### ISSUE TITLE
用该扩展无法生成正常的图像

### ISSUE THREAD

**Issue by swgljy** [Physton/sd-webui-prompt-all-in-one#53]
I just installed the sd-webui-prompt-all-in-one plugin. The translation works normally, but I found that the quality of the images generated by translating the prompt words with it was extremely poor (low resolution, blurry). Trying to adjust various parameters did not work, including changing the base model and sampling method. However, translating the same English prompt words with other translation software could generate images of normal quality.
Please teach me where the problem is?

**Comment by Physton** [comment]
Currently no one else has reported this issue, and I am not sure about it either. I need to investigate.

**Comment by Physton** [comment]
After adding the keyword with this extension, try manually adding another keyword in the input box of the WebUI to see if it takes effect.

**Comment by swgljy** [comment]
Today I tried again. If I only enter a girl without any additional prompt words, the generated image is normal. But after adding other prompts such as walking a dog in the garden, the faces of characters and animals in the generated image will be completely distorted and deformed. Without face repair, the generated image will be unbearable to look at, and it is very blurry.

**Comment by Physton** [comment]
The current issue is whether the use of plugin input can take effect. If it can take effect, then typing the same prompt in the input box on WebUI will result in the same outcome. However, if you enter "1girl" in the plugin and the resulting image is not that of a girl, it means that the input prompt of the plugin is not effective and there is a problem with the plugin.

**Comment by aaronkingdom** [comment]
用了这个夸张, 从获取png信息哪里生成的信息, 转不了文生图或者图生图
