### ISSUE TITLE
[feature request]请求在界面中按换行符分段

### ISSUE THREAD

**Issue by anne43983959** [Physton/sd-webui-prompt-all-in-one#54]
非常感激大佬更新了对换行符和各种分段标记的支持，但换行本身就是为了更清晰地分隔各段之间的内容，现在虽然有了换行符，但还是希望能在出现换行符的位置将卡片也换行，可以大大增加可读性，现在这个状态下对于这种长prompt依然不是很友好

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/115604775/8733aac8-ac59-47ce-9bfc-c22c555278c1)

**Comment by Physton** [comment]
这个会加开关支持，有些人不希望显示的太高

**Comment by anne43983959** [comment]
> 这个会加开关支持，有些人不希望显示的太高

下面那个翻译的标志其实可以隐藏起来，这样高度上会更紧凑一些

另外，希望加入LyCORIS的支持，使用<lyco:>的时候能像LoRA一样有蓝色标记就好了

**Comment by Physton** [comment]
你不需要的东西不代表别人都不需要。
你需要的东西不代表别人都需要。
所以每次这种改动，都要加开关。

Lycoris明天支持。

**Comment by Physton** [comment]
Lycoris 已支持

**Comment by Physton** [comment]
已在扩展主题中支持
<img width="473" alt="Snipaste_2023-05-21_23-05-51" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/dcce0f59-45a7-4fde-b95f-fb1c9d18a678">
