### ISSUE TITLE
theme setting is empty

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#55]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/f588c6f3-cbc5-4393-8525-3a275ee36a62)

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/9ea79719-7ace-43a8-9dfd-c0ce2c091573)

**Comment by Physton** [comment]
见 #49 最后一个回复。我需要你们的文件我才能修复。

**Comment by bluelovers** [comment]
[styles.zip](https://github.com/Physton/sd-webui-prompt-all-in-one/files/11522429/styles.zip)

**Comment by Physton** [comment]
[styles.zip](https://github.com/Physton/sd-webui-prompt-all-in-one/files/11522446/styles.zip)
我实在不清楚为什么是UTF-8编码，文件还是读取出错。
i18n.json、translate_apis.json同样也是utf-8编码，读取他们就没有出现过错误。
所以想请你帮忙试一下，把 styles.py 覆盖进 scripts，然后启动WebUI，看看还有没有报错，有什么报错信息。

**Comment by bluelovers** [comment]
有效

**Comment by Physton** [comment]
有空更新到最新版本，看下”简单一点【暗色主题】“这个主题有没有被加载进来，给我个回复，谢谢。

**Comment by bluelovers** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/1cf5c595-8c62-4fa3-9dad-f08d022026f2)

**Comment by Physton** [comment]
看到加载出来，最后一个。感谢，目前应该是没问题了。
