### ISSUE TITLE
移动端UI显示异常

### ISSUE THREAD

**Issue by MiyouQ** [Physton/sd-webui-prompt-all-in-one#57]
![B7B9D1F8-7A2C-408E-83A0-849F2E6A255D](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/64819178/7703663f-bda1-4ee2-a918-171d5fe63cac)
如图所示

**Comment by Physton** [comment]
已修复

**Comment by MiyouQ** [comment]
> 已修复

好快 大佬这是住github上了么
