### ISSUE TITLE
希望可以添加批量选择单词的功能

### ISSUE THREAD

**Issue by zengapa** [Physton/sd-webui-prompt-all-in-one#58]
插件非常好用,感谢作者大大,
只是发现没有批量选择单词的功能,希望可以加上,

或者双击换行符号可以选定换行符号后面所有单词,这样也很方便换词
![00](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/112471702/01e0a6bd-a592-495c-a0f6-2b7263ca612d)

**Comment by Physton** [comment]
你需要在批量选择后做哪些操作？排序？删除？或者？

**Comment by Physton** [comment]
给下具体要实现的功能，未来可以开发。

**Comment by zengapa** [comment]
主要是想添加排序操作,
批量选择单词拖动位置,

这样操作会方便一些

**Comment by Physton** [comment]
已开发完成
![](https://raw.githubusercontent.com/Physton/sd-webui-prompt-all-in-one-assets/main/images/demo.batch_operation.gif)

**Comment by zengapa** [comment]
感谢大佬
