### ISSUE TITLE
The keywords weight problem

### ISSUE THREAD

**Issue by tomstsai** [Physton/sd-webui-prompt-all-in-one#6]
Keyword weight can not be located to the second decimal point, will automatically round off,like the pixar stley model,it's have the trigger words:(pixarstyle:1.25), it automatically adjusts to (pixarstyle:1.3).

**Comment by Physton** [comment]
I have received the issue you submitted and I will fix it as soon as possible.

**Comment by Physton** [comment]
The issue has been fixed. Now, if you manually input 1.25 in the input box, it will not be rounded up to 1.3, and when using the adjustment buttons to increase or decrease the value, it will also retain two decimal places.
