### ISSUE TITLE
你好，英文tag无法批量翻译成中文

### ISSUE THREAD

**Issue by jackw111** [Physton/sd-webui-prompt-all-in-one#60]
你好，英文tag无法批量翻译成中文，我试了全部的免费翻译接口，也使用了百度的api接口，都无法翻译

**Comment by jackw111** [comment]
![1111111](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/127837373/58ed2008-50cd-4c9b-8b9b-8943b8c0fcde)
![2222222](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/127837373/da58469e-5474-42b0-94ed-6421bd46ed87)

**Comment by Physton** [comment]
你启用了tagcomplete增强是吧

**Comment by jackw111** [comment]
是的，需要关闭是吗

**Comment by Physton** [comment]
既然你启用了，那么你有没有点一下测试，并且测试通过呢？

**Comment by jackw111** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/127837373/8dab2138-33b0-48bd-a884-3cd62eba2559)
测试没有问题呢

**Comment by Physton** [comment]
启用了tagcomplete增强。有个测试按钮出现吗？

**Comment by jackw111** [comment]
关闭tagcomplete增强后，又重新打开，还是没有看到测试按钮的出现

**Comment by Physton** [comment]
我的意思是你启动了tagcomplete增强，那么你能看到一个测试按钮吗，你点过他测试吗，测试通过了吗？

**Comment by jackw111** [comment]
启动tagcomplete增强，没有看到测试按钮

**Comment by Physton** [comment]
你截个图

**Comment by jackw111** [comment]
截图哪个位置

**Comment by Physton** [comment]
算了你不要折腾了，你把tagcomplete增强关闭就好了。

**Comment by jackw111** [comment]
好吧

**Comment by jackw111** [comment]
了解了  ， 是wd1.4标签器反推的词语，无法通过此拓展翻译成中文，c站复制的可以翻译，不知道是什么原因

**Comment by jackw111** [comment]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/127837373/51d81442-f260-403e-af6f-c6e42cfac26c)
这是c站复制的tag，可以翻译
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/127837373/8a5018c6-8083-4fb9-ad33-e1d083ce3aee)
这是wd1.4标签器反推的词语，不能翻译

**Comment by Physton** [comment]
我不是让你关掉tagcomplete增强了吗，你又不会设置，又非要用它。

**Comment by jackw111** [comment]
关掉tagcomplete增强后，还是不能翻译wd1.4标签器反推的tag

**Comment by jackw111** [comment]
不好意思，我的理解错误了，我还以为是说关掉tagcomplete插件，现在已解决，谢谢大佬的解答
