### ISSUE TITLE
只有在 輸入框 內輸入的新詞 才會被自動csv翻譯

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#61]
只有在 (1)輸入框 內輸入的新詞 才會被自動csv翻譯

![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/61a161ea-2b43-4952-92bf-709c1242981f)

如果是在 (2)提示詞輸入框 輸入之後 才更新的 Tag 就不會被翻譯
(但是應該要自動翻譯)

**Comment by jackw111** [comment]
api设置
关闭最下面的选项
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/127837373/877cc9a2-b3f0-4584-b2cb-2fcc108e0dc5)

**Comment by Physton** [comment]
已修改。
