### ISSUE TITLE
支援翻譯被包覆的標籤

### ISSUE THREAD

**Issue by bluelovers** [Physton/sd-webui-prompt-all-in-one#65]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/167966/929ff90f-bdd7-448f-9d31-893475a4997f)

讓

`large breasts,[large breasts],{large breasts},((large breasts)),(large breasts:1.4),[(large breasts)]`

都視為 `large breasts` 被翻譯

**Comment by Physton** [comment]
我在全面优化翻译功能，准备重写，你这个需求稍微延后一下。

**Comment by Physton** [comment]
已支持
