### ISSUE TITLE
老板，你这个UI做的属实丑

### ISSUE THREAD

**Issue by Bavoch** [Physton/sd-webui-prompt-all-in-one#66]
功能很强，但这个界面有点受不了...

**Comment by Physton** [comment]
我并没有强迫任何人使用它。如果你不喜欢它，你完全可以删除它。

**Comment by zhaotianyu227711** [comment]
你这种人真让人无语，觉得ui不好看完全可以用委婉的方式表达让人家改好看一点，人家辛苦开发开源出来不容易，也不盈利；退一万步说，代码都给你摆在那儿，你自己不会动手把ui改好看了？

**Comment by zhaotianyu227711** [comment]
> 功能很强，但这个界面有点受不了...



> 功能很强，但这个界面有点受不了...

你这种人真让人无语，觉得ui不好看完全可以用委婉的方式表达让人家改好看一点，人家辛苦开发开源出来不容易，也不盈利；退一万步说，代码都给你摆在那儿，你自己不会动手把ui改好看了？

**Comment by zhaotianyu227711** [comment]
> 功能很强，但这个界面有点受不了...

你这种人真让人无语，觉得ui不好看完全可以用委婉的方式表达让人家改好看一点，人家辛苦开发开源出来不容易，也不盈利；退一万步说，代码都给你摆在那儿，你自己不会动手把ui改好看了？
