### ISSUE TITLE
为什么有些lora会不断的闪

### ISSUE THREAD

**Issue by langseheise** [Physton/sd-webui-prompt-all-in-one#71]

**Comment by Physton** [comment]
不存在你的lora列表中会闪烁

**Comment by langseheise** [comment]
但是我是直接点击LORA然后，自动提交的关键词，C助手。

**Comment by Physton** [comment]
请问你是否更新到了最新版本。

**Comment by Physton** [comment]
为什么关键词不一样我还真不知道。这样不一样，这个lora会生效吗？

**Comment by Physton** [comment]
我下了这个lora，点击的关键词就是<lora:blindbox_v1:0.5>

**Comment by langseheise** [comment]
我点击的不是，另外LORA无效，可能是我安装了Lycoris插件，一共有两个，有关系，我卸载测试一下

**Comment by langseheise** [comment]
https://github.com/KohakuBlueleaf/a1111-sd-webui-locon
https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

**Comment by Physton** [comment]
现在的lora检测确实有点问题，但你这个问题不属于其中。我稍后会修复目前的问题。

**Comment by langseheise** [comment]
刚试了，LORA不生效是LOCON，插件的问题，不过LORA参数还是一样的闪，不过不影响使用，

**Comment by langseheise** [comment]
我更新了，发现只要关键词和LORA和模型名称对称上，就不会闪，对不上就会闪，但是只要是直接点击模型自动提交的关键词，就算对不上，也是可以正确生成的。
![Snipaste_2023-05-23_17-52-42](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/43820174/3e32b3d8-6b01-4bfd-9cb3-c66a4d083126)
![Snipaste_2023-05-23_17-51-40](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/43820174/194a7fd1-017d-439d-b775-61bf31070ca5)

**Comment by Physton** [comment]
我估计你这个模型的.civitai.info文件有问题，你把他对应的.civitai.info删除了，再点击看看是不是名字和关键词都对的上。

**Comment by langseheise** [comment]
> 我估计你这个模型的.civitai.info文件有问题，你把他对应的.civitai.info删除了，再点击看看是不是名字和关键词都对的上。

我刚才有想过这个原因，把INFO删除了，点击名称还是和之前一样的，可能是模型的问题吧，可以用就行了。先不管。

**Comment by ftyh2005** [comment]
同样的问题
