### ISSUE TITLE
Yandex Translate

### ISSUE THREAD

**Issue by mikheys** [Physton/sd-webui-prompt-all-in-one#72]
Please add the Yandex Translate service. He translates very well.

**Comment by Physton** [comment]
Sure, I'll give it a try first.

**Comment by Physton** [comment]
I'm sorry that I can't apply for an API key, so I can't develop. Can you provide a test key? After I finish development, you can delete it.

**Comment by Physton** [comment]
Free services cannot be supported. Only the official API interface can be accessed. However, I do not have an API key.
