### ISSUE TITLE
Comma at the end of words

### ISSUE THREAD

**Issue by mikheys** [Physton/sd-webui-prompt-all-in-one#75]
It seems to me that it would be more convenient if the comma was placed not at the beginning, when you press the cursor in the input field, but after observing Enter. And then a comma with a space constantly hangs at the end, and in some cases it interferes with repeating some kind of prompt. i.e. perhaps it would be more convenient when you enter a word, press Enter, enter a comma, then a space, and then the entered word.

**Comment by Physton** [comment]
This feature has been enhanced. Please enable it according to your own needs.

![Snipaste_2023-05-24_11-18-17](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/35a282f7-4c13-4847-8d71-454799e0a8fd)
![Snipaste_2023-05-24_11-18-24](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/04e2872a-1345-4db9-9ffe-f2c514306069)
