### ISSUE TITLE
非常好用的插件，但會強迫自動修改提詞

### ISSUE THREAD

**Issue by gesen2egee** [Physton/sd-webui-prompt-all-in-one#76]
發現兩種提詞被修改的情況
一個是強度為0的提詞，可能是為了防呆，被自動修改為1
但實際上0的提詞是有意義的，可以做為特殊玩法
可以參考：
https://github.com/6DammK9/nai-anime-pure-negative-prompt/blob/main/ch01/prompt.md
(bad:0), (comic:0), (cropped:0), (error:0), (extra:0), (low:0), (lowres:0), (speech:0), (worst:0)

另外一種是提詞會在最後自動補,
但實際上,是一個token
例如使用75T的反向咒，補一個token之後變成76/150
跑出來結果跟預期不同

**Comment by Physton** [comment]
已增强此功能，根据自己的需要勾选开启。
![Snipaste_2023-05-24_11-16-44](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/605a142c-876d-482b-a144-7c06123630cb)
![Snipaste_2023-05-24_11-16-52](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/421f1dc3-8b50-468c-b226-b997f0ee49d0)

**Comment by gesen2egee** [comment]
謝謝大大
