### ISSUE TITLE
安装成功后看不到扩展的按钮 I can't see the extension's button after the installation is successful

### ISSUE THREAD

**Issue by AntiEntropySun** [Physton/sd-webui-prompt-all-in-one#77]
使用官方说明里的前3种安装方式安装好插件后，重启webui、重启电脑都试过，在extensions文件夹可以看到插件的目录，在已安装插件里也可以看到插件已安装，但在stablediffusion页面都看不到扩展的按钮，stablediffusion的页面还是与以前一样。不知道问题出在哪里？我使用的webui版本是novelai-webui-aki-v3A。不知道有没有人出现同样问题？怎么解决？

After installing the plug-in using the first three installation methods in the official instructions, I have tried restarting the webui and restarting the computer. You can see the directory of the plug-in in the extensions folder, and you can also see that the plug-in has been installed in the installed plug-ins, but in You can't see the extension button on the stablediffusion page, and the stablediffusion page is still the same as before. Do not know where the problem lies? The webui version I am using is novelai-webui-aki-v3A. I don't know if anyone has the same problem? How to deal with it?

**Comment by Physton** [comment]
常见问题列表：https://github.com/Physton/sd-webui-prompt-all-in-one#faq--%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8

Q: 为什么扩展安装成功了，控制台也没有错误输出，但网页中就是没有扩展的面板？
A: 你需要确保你的WebUI版本是 22bcc7b（2023年第13周） 及更高。如果你的WebUI版本低于此版本，你需要更新WebUI。

**Comment by AntiEntropySun** [comment]
刚更新了webui到最新版，问题解决，谢谢！
