### ISSUE TITLE
自动翻译不起作用，手动点击翻译很多次会被翻译成0

### ISSUE THREAD

**Issue by Anna-Shcherbakova** [Physton/sd-webui-prompt-all-in-one#78]
作者您好，我使用了双语翻译插件和标签自动补全插件，在tagger反推提示词发送到文生图之后无法被翻译，显示都为0，手动输入一些标签也会被翻译成0，不知道是不是插件冲突的问题，像“蓝眼睛”这个词我第一次点击翻译会被翻译成blue eyes，第二次再点翻译就会变成0
然后，输入新的关键词敲回车之后，也不会自动翻译成英文
不知道是我哪里设置错了，期待您的回复
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/54620837/1ad090b3-ebf9-4be1-9920-abf2addf432c)

**Comment by Physton** [comment]
常见问题列表：https://github.com/Physton/sd-webui-prompt-all-in-one#faq--%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8

**Comment by Anna-Shcherbakova** [comment]
> 常见问题列表：https://github.com/Physton/sd-webui-prompt-all-in-one#faq--%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8

我使用了问题列表中的csv，但是仍然会被翻译成0，且自动翻译不起作用呢

**Comment by Physton** [comment]
把你的翻译设置截个图发送上来。api key记得打码

**Comment by Anna-Shcherbakova** [comment]
成功了！十分感谢，我翻译设置里TagComplete的文件选择错了
现在还有一个问题，在输入新关键词按回车之后没法自动翻译，我开启了自动翻译按钮

**Comment by Physton** [comment]
你自己看看翻译界面你是不是勾选错了什么功能！

**Comment by Physton** [comment]
![~@_`L$6422 R)WZV4KLM@3A](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/12066768/127e1d8c-b360-4d34-babf-0f7b18e8f7e7)

**Comment by Physton** [comment]
如果解决了请回复或者关闭问题。
如果没解决请加QQ群：820700336。

**Comment by Anna-Shcherbakova** [comment]
设置我都逐个试过了，但是都不起作用……目前还不清楚是哪里的问题，但是重装了之后就好了
