### ISSUE TITLE
[Bug] Extension change size of Extra Network thumbnail

### ISSUE THREAD

**Issue by LLKoder** [Physton/sd-webui-prompt-all-in-one#79]
The extension change size of Extra Network thumbnail. They become smaller.

**Comment by Physton** [comment]
You may have enabled a theme style developed by other developers for this extension.

**Comment by LLKoder** [comment]
Thanks. :) You are right...

**Comment by lalamax3d** [comment]
fresh install all good. Q. is it possible to make thumbnails smaller (settings somewhere)?

**Comment by Physton** [comment]
> fresh install all good. Q. is it possible to make thumbnails smaller (settings somewhere)?

In SD-WebUI settings
