### ISSUE TITLE
一个位移导致的点击问题

### ISSUE THREAD

**Issue by todpeng707** [Physton/sd-webui-prompt-all-in-one#83]
我想这是我用过的最好的tag工具，特别是暂时失效的的设计，简直太有用了，可以检测一个prompt的有效性。

在使用初始我遇到一个小问题，不知道是否可以修改-----在正反向提示词后面有一个计数单位0/150  或者150/150, 这会导致那一排按钮会因为拷贝了prompt后突然往后移动位置，常常是正好一个按钮的位置，导致我本来想点AN健，发现自己点在了前面的健，，，，

另外有一点想法，为什么不把那些tag做成单点选中，双击才是输入呢，这样就可以把加权，暂时失效这些固定在上面了，现在的操作比较考验我的手法，一不小心就从那些弹出的选项中滑出去了，因为必须鼠标放置，上移，右移，点击，如果可以是选择prompt,然后去点击固定在上面的按钮，或许会更简单？

**Comment by todpeng707** [comment]
赞👍！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Physton ***@***.***&gt;
发送时间: 2023年5月25日 00:14
收件人: Physton/sd-webui-prompt-all-in-one ***@***.***&gt;
抄送: todpeng707 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Physton/sd-webui-prompt-all-in-one] 一个位移导致的点击问题 (Issue #83)





 
TOKEN计数，我稍后改改给它固定的宽度。
 至于下面的操作方式，目前有很多人用习惯了，不方便修改。你稍微再习惯下，我也看看能不能再优化下，能更好的把鼠标移动上去。

**Comment by Physton** [comment]
已经设置了固定宽度

**Comment by todpeng707** [comment]
赞！！感觉越来越好用了

**Comment by todpeng707** [comment]
那大佬会不会考虑增加一种样式？就是这样的中英横列的，我是从其他编辑器里看到的，似乎也比较整齐的样子
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/125846768/f722bed1-c9d0-4843-9219-8898a9c08b8c)
