### ISSUE TITLE
[bug] curser keeps hopping to the end while typing in de middle of a promt tag field

### ISSUE THREAD

**Issue by JaysonPhoenix** [Physton/sd-webui-prompt-all-in-one#86]
yesterday it was still working and since today when typing somewhere in the middle of a prompt tag field (the ones you can drag around) my cursor keeps hopping to the end of the field after about 1sec in the middle of typing a word and when it does that the edits made in the middle get reverted to what it was before editing and the typing continues at the end where the cursor then doesnt keep hopping and reverting edits. this wont happen in the original webui prompt field and when i make changes there they extensions prompt tags show the correct edits (after clicking somewhere in an empty spot near the tags), also typing in the extensions prompt field still works as intended. i noticed you made a recent update so id guess thats probably what broke it

**Comment by Physton** [comment]
Hi, this issue has been fixed. Please update the extension version.
