### ISSUE TITLE
是否会有随机与可选tag？

### ISSUE THREAD

**Issue by todpeng707** [Physton/sd-webui-prompt-all-in-one#88]
大佬我又来了，今天看到一个 运用是关于随机提示词的，很有趣，但是一下子把整个文字框都撑大了（如图），所以是否能有这样一种功能，把同类词组归到一个tag里面，这样我可以随时选择集合中的某一个，也可以设置成随机？（如图）
![随机语句](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/125846768/7d8998b3-81f0-4cc0-b2ce-a9e16997ad8c)
![335](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/125846768/8c0af684-b406-4aa3-aa1b-35eb005766d8)

**Comment by Physton** [comment]
这个做起来太复杂了，暂时不会考虑。等未来再看吧。

**Comment by todpeng707** [comment]
嗯嗯！

**Comment by todpeng777** [comment]
确实是太复杂了，而且我找到了一个别的插件，是专门提供prompt可选集合的，

**Comment by vicyaosketch** [comment]
> 確實是太複雜了，而且我找到了一個別樣的插件，是專門提供提示可選集合的，而且各位大佬你這個還不衝突

请问是哪个插件这么好用，还跟这个大佬的插件不冲突~  愿意告知分享下载位置吗?
