### ISSUE TITLE
Suggestions about UI and hotkeys

### ISSUE THREAD

**Issue by Sefrautic** [Physton/sd-webui-prompt-all-in-one#89]
Hi, this extension is fire! I've been dreaming about this functionality since February.
I have couple of suggestions:

Would be nice to have some dark grey theme for this popout window, like the rest of the interface. It feels too bright.
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/61527866/30bd913e-0407-4af1-b9eb-56488421f531)

Also would be cool to have hotkey like Alt+Left Click on keyword to "Disable\Enable Keyword". This is so needed because the disable button is too far on the right, and the workflow will be much faster.

Anyway, thanks for developing such a great extension, you're awesome!

**Comment by Physton** [comment]
Thank you very much for your suggestion.

I will make some modifications to this window under the dark theme.

Regarding disabling/enabling keywords, I've been considering using a double-click approach. If I were to use hotkeys, it would require setting up and binding the hotkeys, which can be quite complicated at the moment.

Additionally, there are some enhanced features in the expansion style that you can try, such as moving the keyword popup to the right side.

**Comment by Physton** [comment]
Dark theme pop-up window has been optimized.
New feature added: Double-click to disable/enable keyword.
