### ISSUE TITLE
为什么在google colab上运行的SD，下载这个插件后完全没有显示

### ISSUE THREAD

**Issue by WanZunGe** [Physton/sd-webui-prompt-all-in-one#91]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/100510668/6770f353-75d0-4a97-ab44-e735ac9adfe1)
![image](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/100510668/b26cc5a3-e3bb-4389-9462-47f9e09c7da2)
插件安装了，选取了，重启UI了，甚至重新启动了脚本都没有用，就是不显示插件的功能界面

**Comment by Physton** [comment]
https://github.com/Physton/sd-webui-prompt-all-in-one#faq--%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8

**Comment by WanZunGe** [comment]
> https://github.com/Physton/sd-webui-prompt-all-in-one#faq--%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8

好吧，谢谢，可能是我的版本过低了
