### ISSUE TITLE
无法一次批量翻译，需多次点击+删除prompt，不会实时更新到插件

### ISSUE THREAD

**Issue by gustavmilo** [Physton/sd-webui-prompt-all-in-one#92]
![2023-05-26_224722](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/129682674/e0c9cc54-0d87-49c2-a4e9-b2f499151d5b)
![2023-05-26_224932](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/129682674/b70b7aa9-0d63-441b-be7b-c535b19f2d00)
1、无法一次批量翻译，并有【invalid  access limit】提示，需多次点击方能~~~
2、删除[all-in-one]插件里的prompt，会实时更新到SD原生prompt输入框，但是在SD原生输入框中删除prompt，却不会实时更新到[all-in-one]插件的prompt，希望能改进~
3、希望有一键显示或隐藏prompt本地语言标签的按钮，现在即使没有翻译到本地语言，毕竟【A|B】标签会占行数呢

**Comment by Physton** [comment]
1.更换QPS更高的接口。
2.软件特性，故意这么做的。原生输入框任何更改都要点扩展面板再加载。
3.扩展等风格里找关闭隐藏翻译。

**Comment by gustavmilo** [comment]
> 1.更换QPS更高的接口。 2.软件特性，故意这么做的。原生输入框任何更改都要点扩展面板再加载。 3.扩展等风格里找关闭隐藏翻译。

多谢大佬解惑！
