### ISSUE TITLE
It doesn't start after the last update

### ISSUE THREAD

**Issue by thejohnd0e** [Physton/sd-webui-prompt-all-in-one#93]
Restarting doesn't help.

**Comment by Physton** [comment]
Without any more detailed instructions, screenshots, logs, etc., I am unable to solve your problem.

**Comment by thejohnd0e** [comment]
> Without any more detailed instructions, screenshots, logs, etc., I am unable to solve your problem.
I was getting an error starting the extension after the upgrade, but I found the reason. I deleted the "hystory" files and now it runs fine.

<img width="314" alt="Screenshot - 2023-05-27 12 21 03" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/115493464/73dc4a28-c918-4428-ac21-9c201a1bdd7c">
<img width="515" alt="Screenshot - 2023-05-27 12 40 43" src="https://github.com/Physton/sd-webui-prompt-all-in-one/assets/115493464/6394d9ad-e10d-4789-9b88-bf915cce9163">

**Comment by Physton** [comment]
This issue has been fixed before, and it shouldn't occur again in future updates.
