### ISSUE TITLE
我的webui更新到了v2.3了为什么还是出不来页面啊

### ISSUE THREAD

**Issue by lee-eel777** [Physton/sd-webui-prompt-all-in-one#94]
我是在colab上面部署的sd，装了插件以后一直重新启动，还是没看见插件的页面，也可能是因为我没有真正更新到新版本，有大佬可以指点一下云端部署的sd怎么更新到最新版本吗

**Comment by Physton** [comment]
webui目前最高1.3.0，哪来的2.3

**Comment by lee-eel777** [comment]
不好意思不是很懂，那可以请教一下大佬colab上该怎么更新webui吗

**Comment by Physton** [comment]
没用过，不清楚
