### ISSUE TITLE
It's about the weight of a prompt

### ISSUE THREAD

**Issue by armentix** [Physton/sd-webui-prompt-all-in-one#95]
It's not real issue here but i post it anyways.

When prompting (prompt:1.25) it works but when prompting (prompt:1.257) 3 digits or more it don't work.
It would be really appreciated if you can add more like 4-6 digits after the point.

Thank you in advance !

**Comment by Physton** [comment]
It is possible to modify and reserve more decimal places. But I am curious, is there really a difference between so many decimal places? I usually don't use that many decimal places.

**Comment by Physton** [comment]
Modified

**Comment by armentix** [comment]
Yes there is for fine-tuning some sizes of prompts for big or tiny, wide or thin, etc... well i don't go beyond 4 digits never had to.

**Comment by Physton** [comment]
It's alright, it already supports up to 6 decimal places and having either 6 or 4 decimal places won't affect the functionality.

**Comment by armentix** [comment]
Good thank you for the fast reply !
