### ISSUE TITLE
每当我移动提示词顺序的时候就会出现这种情况

### ISSUE THREAD

**Issue by doublle1** [Physton/sd-webui-prompt-all-in-one#96]
![微信截图_20230529004718](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/56800589/c05079d6-6535-4278-89c6-b9968203780b)
这是正常的提示词，当我移动了里面的提示词顺序的时候，就会变成这样
![微信截图_20230529004736](https://github.com/Physton/sd-webui-prompt-all-in-one/assets/56800589/89b830f6-a139-42c0-8a66-149b3f720255)
导致我后续无法输入提示词，只能重启webui

**Comment by Physton** [comment]
你装了哪些插件？

**Comment by Physton** [comment]
1. 换个浏览器试一下
2. 逐个禁用其他插件（从非著名的插件开始），看是不是哪个插件冲突了。

**Comment by doublle1** [comment]
我试试

**Comment by doublle1** [comment]
我用得谷歌浏览器，貌似是出现在浏览器的身上，换edge就可以，有没有办法解决一下在谷歌浏览器上的这种情况

**Comment by Physton** [comment]
好的，我测试一下。你把你谷歌浏览器的版本号发我一下。

**Comment by doublle1** [comment]
> 好的，我测试一下。你把你谷歌浏览器的版本号发我一下。

Chrome 已是最新版本
版本 113.0.5672.127（正式版本） （64 位）是这个

**Comment by Physton** [comment]
版本 112.0.5615.121（正式版本） （64 位）
版本 113.0.5672.127（正式版本） （64 位）

这两个版本下我测试都正常，你看下是否装了什么浏览器插件影响到了。

**Comment by doublle1** [comment]
> 版本 112.0.5615.121（正式版本） （64 位） 版本 113.0.5672.127（正式版本） （64 位）
> 
> 这两个版本下我测试都正常，你看下是否装了什么浏览器插件影响到了。

找到了，DEEPL翻译插件起冲突了
