### ISSUE TITLE
如何才能使用 [Free] Google, America  or [Free] Microsoft Bing 翻译接口。

### ISSUE THREAD

**Issue by vicyaosketch** [Physton/sd-webui-prompt-all-in-one#97]
您好,我不在中国内地, 使用内地的阿里翻译...等，都会出现卡顿的问题。过去曾用过其他的翻译插件, 是可以选用 Microsoft Bing 与  Google  免费翻译的，并且速度比较顺畅。但使用本插件却无法使用 [Free] Google, America 。会出现 Google service was offline in inland of China on Oct 2022.   使用 [Free] Microsoft Bing 会出现 Expecting value: line 1 column 1 (char 0) 。
 请问大佬, 在本插件要如何才能实现使用 Google  or  Microsoft Bing 翻译 ?  谢谢~

**Comment by Physton** [comment]
你选择下方API KEY的接口，按照教程申请。也是免费的，下方的基本都能设置所在国家区域用于网络加速。

**Comment by vicyaosketch** [comment]
感谢回覆~ 谢谢~

**Comment by Physton** [comment]
刚更新了一版，免费的接口加上了Region区域选择。Google选择EN可以使用。China不行。
但还是不推荐用免费的

**Comment by vicyaosketch** [comment]
了解~ 您辛苦了，十分感謝~
