### ISSUE TITLE
The extension has stopped working

### ISSUE THREAD

**Issue by LLKoder** [Physton/sd-webui-prompt-all-in-one#98]
sd-webui-prompt-all-in-one
Connection to backend API service failed. Please manually refresh the webpage. If it still doesn't work, please restart the WebUI.
连接到后台接口服务失败，请手动再刷新一次网页。如果还是不行，请重启WebUI。

**Comment by sxsrobin0822** [comment]
同样的情况，新版的bug，退回到0528版本后回归正常。

**Comment by Physton** [comment]
@sxsrobin0822 
最新版无法正常工作吗？我目前没有发现问题，问了一些人也没有这个问题。我不知道这个问题是怎么产生的？能否加我QQ：94126162。我想远程看一下。
*Does the latest version not work properly? I haven't found any issues so far, and I asked some people and they didn't have this issue either. I don't know how this problem arose. Could you add me on QQ: 94126162? I would like to take a look at it remotely.*

**Comment by Physton** [comment]
I just submitted a version that will display the specific reason for connection failures when this error message appears again. Please take a screenshot or copy and send me the specific error message.

**Comment by wzgrx** [comment]
> @sxsrobin0822 最新版无法正常工作吗？我目前没有发现问题，问了一些人也没有这个问题。我不知道这个问题是怎么产生的？能否加我QQ：94126162。我想远程看一下。 _Does the latest version not work properly? I haven't found any issues so far, and I asked some people and they didn't have this issue either. I don't know how this problem arose. Could you add me on QQ: 94126162? I would like to take a look at it remotely._

https://github.com/adieyal/sd-dynamic-prompts/issues/469

**Comment by wzgrx** [comment]
Does it conflict with this plugin？

**Comment by Physton** [comment]
I saw the error log you posted here https://github.com/adieyal/sd-dynamic-prompts/issues/469. It seems that this extension was looking for the wrong path when importing the Python package, but it has now been corrected. Please try again to see if it's working properly.

**Comment by wzgrx** [comment]
> 我看到了你在这里发布的错误日志 [adieyal/sd-dynamic-prompts#469](https://github.com/adieyal/sd-dynamic-prompts/issues/469)。似乎此扩展在导入 Python 包时寻找错误的路径，但现在已更正。请重试以查看它是否正常工作。

Thank you, it can now work normally

**Comment by Physton** [comment]
If it is working properly, I will optimize the code a bit more. Could you please try it again after I submit a new version later? Thank you!

**Comment by wzgrx** [comment]
> 如果它工作正常，我将进一步优化代码。稍后我提交新版本后，您能否再试一次？谢谢！

okay

**Comment by Physton** [comment]
Please try again after the update, thank you.

**Comment by wzgrx** [comment]
> Please try again after the update, thank you.
Error reported in the latest version
Error loading script: on_app_started.py
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "G:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\on_app_started.py", line 18, in <module>
    from scripts.packages import get_packages_state, install_package
  File "G:\stable-diffusion-webui\extensions\sd-webui-prompt-all-in-one\scripts\packages.py", line 8, in <module>
    packages = install.packages
AttributeError: module 'install' has no attribute 'packages'

**Comment by Physton** [comment]
It seems there are indeed some issues. Everything is normal in my environment. I've reverted the code to its previous version.

**Comment by wzgrx** [comment]
> 看来确实存在一些问题。在我的环境中一切都很正常。我已将代码恢复到以前的版本。

https://github.com/Physton/sd-webui-prompt-all-in-one/commit/5ff1732e5df1b8bde7075233cb14b3f04a7317a7
This version can be used normally

**Comment by Physton** [comment]
I have just reverted the code to commit 5ff1732.

**Comment by Physton** [comment]
> 同样的情况，新版的bug，退回到0528版本后回归正常。

已修复。

**Comment by Physton** [comment]
@wzgrx 
Everything is working properly now, right?

**Comment by wzgrx** [comment]
> @wzgrx Everything is working properly now, right?

yes，Can be used normally

**Comment by xiansk** [comment]
全部更新一下 相关就可以了：

> cd ~/sd-webui-forge
> cd repositories

git clone 以下四个（已经有的，就先删除，git下来最新版本的）
git clone https://github.com/salesforce/BLIP.git 
git clone https://github.com/lllyasviel/huggingface_guess.git 
git clone https://github.com/lllyasviel/google_blockly_prototypes.git
git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets.git

其中第四个是不显示的关键

然后
重装一下 all in one:  已经有的，就先删除，git下来最新版本的）
cd ~/sd-webui-forge/extensions
git clone https://github.com/Physton/sd-webui-prompt-all-in-one.git

这样就搞定啦


附日志：

<img width="2488" height="1450" alt="Image" src="https://github.com/user-attachments/assets/9f46c050-6136-418b-b5a9-f6bb903293ba" />
